const DB='tariq-driver-offline-v1';
export const OFFLINE_TTL=12*60*60*1000;
let opening;
function open(){if(!opening)opening=new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('records');r.onsuccess=()=>resolve(r.result);r.onerror=()=>{opening=null;reject(Error('Offline-Speicher ist nicht verfügbar.'))}});return opening}
export const driverOfflineStore={async read(key){const db=await open();return new Promise((resolve,reject)=>{const r=db.transaction('records').objectStore('records').get(key);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})},async update(key,change){const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction('records','readwrite'),s=tx.objectStore('records'),r=s.get(key);let next;r.onsuccess=()=>{try{next=change(r.result||null);if(next===null)s.delete(key);else s.put(next,key)}catch(e){tx.abort();reject(e)}};tx.oncomplete=()=>{window.dispatchEvent(new Event('driver-offline-change'));resolve(next)};tx.onerror=()=>reject(Error('Offline-Speichern fehlgeschlagen. Keine Änderung bestätigt.'))})}};
export const driverScope=user=>user?.id&&user?.driverId&&user?.businessUnitId?`${user.businessUnitId}:${user.id}:${user.driverId}`:null;
export async function rememberOfflineDriver(user){if(!driverScope(user)||user.role!=='driver')return;const previous=await driverOfflineStore.read('identity');if(previous&&driverScope(previous.user)!==driverScope(user))await forgetOfflineIdentity();await driverOfflineStore.update('identity',()=>({user,verifiedAt:Date.now()}))}
export async function restoreOfflineDriver(){const r=await driverOfflineStore.read('identity');if(r&&r.user.role==='driver'&&driverScope(r.user)&&Date.now()-r.verifiedAt>=0&&Date.now()-r.verifiedAt<OFFLINE_TTL)return r;if(r)await forgetOfflineIdentity();return null}
export async function forgetOfflineIdentity(){const identity=await driverOfflineStore.read('identity');const scope=driverScope(identity?.user);if(scope)await driverOfflineStore.update(scope,r=>r?{...r,trips:[],shiftReport:null,savedAt:null,shiftSavedAt:null,queue:(r.queue||[]).map(e=>({...e,label:'Fahrtmeldung '+e.tripId}))}:null);await driverOfflineStore.update('identity',()=>null)}
