import {OFFLINE_TTL} from './driverOfflineStore.js';
export const STATUS_ORDER=['geplant','auf_dem_weg','angekommen','in_fahrt','abgeschlossen'];
export function driverTripSnapshot(t){const keys=['id','date','time','direction','type','from','to','driverId','driver','vehicleId','vehicle','patient','wheelchair','status','assignedAt','onTheWayAt','arrivedAt','startedAt','completedAt','cancelledAt','updatedAt'];return Object.fromEntries(keys.map(k=>[k,t[k]]))}
export function offlineTrips(trips,user,now=Date.now()){
 const day=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Berlin'}).format(new Date(now)),tomorrow=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Berlin'}).format(new Date(now+86400000));

 return trips.filter(t=>t.driverId===user.driverId&&(t.date===day||t.date===tomorrow||['auf_dem_weg','angekommen','in_fahrt'].includes(t.status))).slice(0,200).map(driverTripSnapshot);
}
export function effectiveTrips(trips,queue){return trips.map(t=>{let r={...t};for(const e of queue.filter(q=>q.tripId===t.id)){if(e.state==='blocked')break;r={...r,status:e.status,offlinePending:true,[{auf_dem_weg:'onTheWayAt',angekommen:'arrivedAt',in_fahrt:'startedAt',abgeschlossen:'completedAt'}[e.status]]:e.recordedAt}}return r})}
export function createDriverOffline({store,scope,send,now=()=>Date.now(),uuid=()=>crypto.randomUUID()}){
 const lock=fn=>typeof navigator!=='undefined'&&navigator.locks?navigator.locks.request('driver-offline:'+scope,fn):fn();
 let draining=false;
 const read=async()=>await store.read(scope)||{queue:[],trips:[],shiftReport:null};
 return {read,async snapshot(trips,shiftReport){return store.update(scope,r=>({...r,queue:r?.queue||[],trips:r?.queue?.length?r.trips:trips,shiftReport:shiftReport===undefined?r?.shiftReport:shiftReport,savedAt:r?.queue?.length?r.savedAt:now()}))},async enqueue(trip,status,shift){return store.update(scope,r=>{if(!r?.savedAt||now()-r.savedAt>=OFFLINE_TTL||now()<r.savedAt)throw Error('Offline-Daten sind veraltet. Online aktualisieren.');if(!shift||shift.state!=='active'||shift.vehicle_id!==trip.vehicleId)throw Error('Aktive Schicht mit passendem Fahrzeug erforderlich.');const queue=r.queue||[];if(queue.length>=200)throw Error('Offline-Speicher für Fahrtmeldungen voll. Zuerst übertragen.');if(queue.some(e=>e.state==='blocked'))throw Error('Offenen Übertragungskonflikt zuerst mit dem Büro klären.');const current=effectiveTrips(r.trips,queue).find(t=>t.id===trip.id);if(!current||current.status!==trip.status||STATUS_ORDER.indexOf(status)!==STATUS_ORDER.indexOf(current.status)+1)throw Error('Fahrtstatus wurde geändert. Neu laden.');const previous=queue.filter(e=>e.tripId===trip.id).at(-1);queue.push({requestId:uuid(),tripId:trip.id,shiftId:shift.id,expectedStatus:trip.status,status,baseVersion:previous?null:current.updatedAt,predecessorId:previous?.requestId||null,recordedAt:new Date(now()).toISOString(),state:'pending',label:`${trip.date} ${trip.time} · ${trip.patient||'Fahrt'}`});return {...r,queue}})},async drain(){return lock(async()=>{if(draining)return read();draining=true;try{for(;;){const r=await read(),e=r.queue[0];if(!e||e.state==='blocked')return r;let result;try{result=await send(e)}catch{return r}if(!result.ok){if([400,403,404,409].includes(result.httpStatus)){return store.update(scope,current=>({...current,queue:current.queue.map(q=>q.requestId===e.requestId?{...q,state:'blocked',error:result.message}:q)}))}return {...r,transportError:result.message||'Verbindung oder Anmeldung prüfen. Meldungen bleiben gespeichert.'}}await store.update(scope,current=>({...current,trips:current.trips.map(t=>t.id===e.tripId?{...t,...result.trip}:t),queue:current.queue.filter(q=>q.requestId!==e.requestId)}))}}finally{draining=false}})},async discard(){return lock(async()=>{if(draining)throw Error('Übertragung läuft. Bitte warten.');return store.update(scope,r=>({...r,queue:[],trips:[],shiftReport:null,savedAt:null}))})}};
}
