import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {transform} from 'esbuild';
import * as rules from '../supabase/functions/_shared/documents.js';
const pdf=new Blob(['%PDF-1.7\nExample'],{type:'application/pdf'});
function setup(){
 const rows={app_profiles:[{id:'user',organization_id:'org',active:true}],business_units:[{id:'unit',organization_id:'org',code:'fahrdienst',active:true}],memberships:[{user_id:'user',business_unit_id:'unit',role:'office',active:true}],customers:[{id:'customer',organization_id:'org'}],customer_business_units:[{customer_id:'customer',business_unit_id:'unit'}],customer_authorizations:[{id:'approval',customer_id:'customer',authorization_type:'approval'}],trips:[{id:'trip',customer_id:'customer',business_unit_id:'unit'}],accounting_documents:[]};
 rows.accounting_entries=[{id:'entry',business_unit_id:'unit',kind:'expense'}];
 const writes=[],storageCalls=[];let file=pdf;let race=false,denied=false;const db={rpc:async()=>({error:denied?{message:'Denied'}:null}),auth:{getUser:async()=>({data:{user:{id:'user'}}})},storage:{from(bucket){assert.equal(bucket,'fahrdienst-expense-documents');return {download:async path=>{storageCalls.push(['download',path]);return {data:file}},remove:async paths=>{storageCalls.push(['remove',paths]);return {error:null}},createSignedUrl:async(path,seconds)=>{storageCalls.push(['sign',path,seconds]);return {data:{signedUrl:'https://example.test/private.pdf'}}}}}},from(table){let filters=[],insert,patch,single=false;const q={select(){return q},eq(k,v){filters.push(r=>r[k]===v);return q},maybeSingle(){single=true;return q},insert(v){insert=v;return q},update(v){patch=v;return q},then(resolve,reject){try{let data=(rows[table]||[]).filter(r=>filters.every(f=>f(r)));if(insert){writes.push({table,insert});rows[table].push(insert);data=[insert]}if(patch&&race){race=false;data=[]}if(patch){writes.push({table,patch});data.forEach(r=>Object.assign(r,patch))}return Promise.resolve({data:single?data[0]||null:data,error:null}).then(resolve,reject)}catch(e){return Promise.reject(e).then(resolve,reject)}}};return q}};
 return {db,rows,writes,storageCalls,setFile:v=>file=v,setRace:()=>race=true,setDenied:()=>denied=true};
}
async function call(s,body){const source=fs.readFileSync('supabase/functions/manage-accounting-documents/index.ts','utf8').replace(/^import .*;\n/gm,'');const {code}=await transform(source,{loader:'ts'});let handle;new Function('Deno','createClient',...Object.keys(rules),code)({env:{get:()=> 'test'},serve:f=>handle=f},()=>s.db,...Object.values(rules));const response=await handle(new Request('https://example.test',{method:'POST',headers:{Authorization:'Bearer token','Content-Type':'application/json'},body:JSON.stringify({businessUnitCode:'fahrdienst',...body})}));return {status:response.status,body:await response.json()};}
const input={action:'prepare',entryId:'entry',mimeType:'application/pdf',size:pdf.size,fileName:'expense.pdf'};
async function prepare(s){const r=await call(s,input);assert.equal(r.status,200);return r.body.id;}
test('authorization and unit scope precede all expense storage operations',async()=>{for(const change of [s=>s.setDenied(),s=>s.rows.app_profiles[0].active=false,s=>s.rows.business_units[0].organization_id='foreign']){const s=setup();change(s);assert.equal((await call(s,input)).status,403);assert.equal(s.writes.length,0);assert.equal(s.storageCalls.length,0)}});
test('only active expenses prepare originals and cannot forge unit, creator or path',async()=>{for(const change of [s=>s.rows.accounting_entries[0].kind='payment_date',s=>s.rows.accounting_entries[0].cancelled_at='now',s=>s.rows.accounting_entries[0].business_unit_id='foreign']){const s=setup();change(s);assert.equal((await call(s,input)).status,409);assert.equal(s.writes.length,0)}const s=setup();const r=await call(s,{...input,storage_path:'foreign',created_by:'other',business_unit_id:'foreign'});assert.equal(r.status,200);const d=s.rows.accounting_documents[0];assert.equal(d.created_by,'user');assert.equal(d.business_unit_id,'unit');assert.match(d.storage_path,/^unit\/[a-f0-9-]+\.pdf$/)});
test('finalize hashes actual original bytes, is idempotent and returns checked preview metadata',async()=>{const s=setup(),id=await prepare(s);assert.equal((await call(s,{action:'finalize',documentId:id})).status,200);const d=s.rows.accounting_documents[0];assert.match(d.sha256,/^[a-f0-9]{64}$/);const count=s.storageCalls.length;s.rows.accounting_entries[0].cancelled_at='now';assert.equal((await call(s,{action:'finalize',documentId:id})).status,200);assert.equal(s.storageCalls.length,count);const r=await call(s,{action:'preview',documentId:id});assert.equal(r.body.sha256,d.sha256);assert.equal(r.body.sizeBytes,pdf.size);assert.deepEqual(s.storageCalls.at(-1),['sign',d.storage_path,120])});
test('invalid MIME and size mark failed and remove only pending files',async()=>{for(const file of [new Blob(['<html>Not a PDF</html>']),new Blob(['%PDF-wrong-size'])]){const s=setup(),id=await prepare(s);s.setFile(file);assert.equal((await call(s,{action:'finalize',documentId:id})).status,400);assert.equal(s.rows.accounting_documents[0].status,'failed');assert.equal(s.storageCalls.at(-1)[0],'remove');assert.equal((await call(s,{action:'preview',documentId:id})).status,409)}});
test('creator/cancelled expense protections reject finalize; foreign documents never sign',async()=>{for(const change of [s=>s.rows.accounting_documents[0].created_by='other',s=>s.rows.accounting_entries[0].cancelled_at='now']){const s=setup(),id=await prepare(s);change(s);assert.equal((await call(s,{action:'finalize',documentId:id})).status,409);assert.equal(s.storageCalls.length,0)}const s=setup(),id=await prepare(s);s.rows.accounting_documents[0].business_unit_id='foreign';assert.equal((await call(s,{action:'preview',documentId:id})).status,404);assert.equal(s.storageCalls.length,0)});
test('archive/restore keeps originals available after expense correction; archives cannot sign',async()=>{const s=setup(),id=await prepare(s);await call(s,{action:'finalize',documentId:id});s.rows.accounting_entries[0].cancelled_at='now';assert.equal((await call(s,{action:'archive',documentId:id})).status,200);assert.equal((await call(s,{action:'preview',documentId:id})).status,409);assert.equal((await call(s,{action:'restore',documentId:id})).status,200);assert.equal((await call(s,{action:'preview',documentId:id})).status,200);assert.ok(!s.storageCalls.some(c=>c[0]==='remove'))});
test('abort only own or stale uploads; conditional failure never deletes a concurrently finalized original',async()=>{const s=setup(),id=await prepare(s);s.rows.accounting_documents[0].created_by='other';s.rows.accounting_documents[0].created_at=new Date().toISOString();assert.equal((await call(s,{action:'abort',documentId:id})).status,409);s.rows.accounting_documents[0].created_at=new Date(Date.now()-3600001).toISOString();s.setRace();assert.equal((await call(s,{action:'abort',documentId:id})).status,409);assert.equal(s.storageCalls.length,0);assert.equal((await call(s,{action:'abort',documentId:id})).status,200);assert.equal(s.storageCalls.at(-1)[0],'remove')});
