import {test} from 'node:test';import assert from 'node:assert/strict';
import {accountingReport,accountingCsv,validateAccountingInput,accountingToday} from '../src/lib/accounting.js';
const month='2026-09',inv={id:'i',document_type:'invoice',status:'paid',paid_at:'2026-10-01',gross_total:100,payer_name:'Patient',invoice_number:'RE-1'};
test('cashflow follows actual payment date, includes unallocated insurer cash, excludes void records and does not invent paid dates',()=>{const r=accountingReport({invoices:[inv],insurer_payment_entries:[{id:'k',amount:100,payment_date:'2026-09-10'},{id:'void',amount:999,payment_date:'2026-09-10',cancelled_at:'x'}],patient_invoice_payments:[{id:'p',invoice_id:'other',amount:10,payment_date:'2026-10-01',method:'cash'}],accounting_entries:[{id:'e',kind:'expense',category:'fuel',amount:20,payment_date:'2026-09-15',method:'card'}]},{month});assert.deepEqual(r.totals,{income:10000,expense:2000,refund:0,balance:8000});assert.equal(r.pending.length,1)});
test('receipt overlap cannot double count a patient or insurer allocation and is disclosed',()=>{const r=accountingReport({insurer_payment_entries:[{id:'k',amount:90,payment_date:'2026-09-10'}],insurer_payment_allocations:[{payment_id:'k',invoice_id:'i',amount:90}],patient_invoice_payments:[{id:'p',invoice_id:'own',amount:10,payment_date:'2026-09-10',method:'cash'}],receipts:[{id:'r1',invoice_id:'i',amount:90,payment_date:'2026-09-10'},{id:'r2',invoice_id:'own',amount:10,payment_date:'2026-09-10'},{id:'r3',amount:5,payment_date:'2026-09-10',payment_method:'cash'}]},{month});assert.equal(r.totals.income,10500);assert.equal(r.conflicts.length,2)});
test('dated legacy payment remains after document cancellation; actual refund date subtracts once and pending refund is not guessed',()=>{const st={id:'st',document_type:'cancellation',refund_status:'refunded',refund_amount:100,refunded_at:'2026-10-01',invoice_number:'ST-1'};const data={invoices:[{...inv,status:'cancelled'},st],accounting_entries:[{id:'a',kind:'payment_date',invoice_id:'i',amount:100,payment_date:'2026-09-01',method:'bank'},{id:'b',kind:'refund_date',invoice_id:'st',amount:100,payment_date:'2026-09-15',method:'bank'}]};const r=accountingReport(data,{month});assert.equal(r.totals.income,10000);assert.equal(r.totals.refund,10000);assert.equal(r.totals.balance,0);assert.equal(r.pending.length,0);data.accounting_entries.pop();assert.equal(accountingReport(data,{month}).pending[0].kind,'refund_date')});
test('later automatic source or amount change invalidates dated supplement and requires review',()=>{const data={invoices:[inv],accounting_entries:[{id:'a',kind:'payment_date',invoice_id:'i',amount:100,payment_date:'2026-09-01',method:'bank'}],receipts:[{id:'r',invoice_id:'i',amount:100,payment_date:'2026-09-01'}]};const r=accountingReport(data,{month});assert.equal(r.totals.income,10000);assert.equal(r.conflicts.length,1)});
test('filters and totals use all rows, correction audit retained and original input immutable',()=>{const data={receipts:Array.from({length:125},(_,n)=>({id:String(n),amount:.1,payment_date:'2026-09-01',payment_method:'cash'})),accounting_entries:[{id:'cancel',kind:'expense',amount:1,payment_date:'2026-09-01',cancelled_at:'x'}]};const before=JSON.stringify(data),r=accountingReport(data,{month,method:'cash'});assert.equal(r.totals.income,1250);assert.equal(r.rows.length,125);assert.equal(r.audit.length,1);assert.equal(accountingReport(data,{month,flow:'expense'}).rows.length,0);assert.equal(JSON.stringify(data),before)});
test('CSV exports all rows, quotes delimiter/newlines and neutralizes spreadsheet formula text',()=>{const csv=accountingCsv([{date:'2026-09-01',flow:'income',source:'Quelle',reference:'=HYPERLINK("evil")',recipient:'+123',description:'Line;\n"quoted"',method:'bank',cents:1050}]);assert.ok(csv.startsWith('\ufeff'));assert.match(csv,/'=HYPERLINK/);assert.match(csv,/'\+123/);assert.match(csv,/"10,50"/);assert.match(csv,/""quoted""/)});
test('expense input requires actual date, recipient, reference and exact positive cents',()=>{const input={kind:'expense',date:accountingToday(),amount:'12,50',category:'fuel',method:'cash',recipient:'Tankstelle',reference:'BELEG-1',description:'Tanken'};assert.equal(validateAccountingInput(input),'');for(const patch of [{date:''},{date:'2099-01-01'},{amount:'1.001'},{amount:'-1'},{amount:'abc'},{recipient:''},{reference:'x'}])assert.ok(validateAccountingInput({...input,...patch}));assert.throws(()=>accountingReport({receipts:[{id:'x',amount:1}]},{month}))});
import {readPages} from '../src/data/readPages.js';
test('composite payment allocation pagination retains rows and detects duplicates',async()=>{const all=[{payment_id:'p',invoice_id:'a'},{payment_id:'p',invoice_id:'b'}];const query=()=>({range:async(start)=>({count:2,data:all.slice(start,start+1)})});assert.equal((await readPages(query,r=>r.payment_id+':'+r.invoice_id)).length,2);await assert.rejects(readPages(()=>({range:async()=>({count:2,data:[all[0],all[0]]})}),r=>r.payment_id+':'+r.invoice_id),/geändert/)});

test('paid legacy invoice without a timestamp can receive an actual date; saved date survives cancellation',()=>{const base={...inv,paid_at:null};assert.equal(accountingReport({invoices:[base]},{month}).pending.length,1);const r=accountingReport({invoices:[{...base,status:'cancelled'}],accounting_entries:[{id:'a',kind:'payment_date',invoice_id:'i',amount:100,payment_date:'2026-09-01',method:'bank'}]},{month});assert.equal(r.totals.income,10000)});

import fs from 'node:fs';
test('accounting adapter sends a boolean confirmation even when an HTML form contains on',async()=>{let captured;const supabase={functions:{invoke:async(_name,{body})=>{captured=body;return{data:{ok:true}}}}};const source=fs.readFileSync('src/data/accounting.js','utf8').replace(/^import .*;\n/gm,'').replaceAll('export ','');const api=new Function('supabase','APP_CONFIG','readPages',source+';return accountingApi')(supabase,{businessUnitCode:'fahrdienst'},()=>{});const r=await api.record({kind:'expense',confirmed:'on',reference:'TEST-1'});assert.equal(r.ok,true);assert.equal(captured.confirmed,true);assert.equal(captured.action,'record_accounting_entry')});
