import test from 'node:test';
import assert from 'node:assert/strict';
import {unzipSync,strFromU8} from 'fflate';
import {buildAccountingPackage,expenseExportPlan,accountingExportSnapshot,MAX_EXPORT_BYTES} from '../src/lib/accountingExport.js';
const bytes=new TextEncoder().encode('%PDF-1.7\noriginal expense');
const sha=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(x=>x.toString(16).padStart(2,'0')).join('');
function fixture(){const entry={id:'expense1',business_unit_id:'unit',kind:'expense',payment_date:'2026-10-01',amount:25,method:'card',category:'fuel',recipient:'=UNTRUSTED()',reference:'REF1',description:'Fuel'};return {data:{accounting_entries:[entry],accounting_documents:[{id:'doc1',business_unit_id:'unit',entry_id:entry.id,status:'ready',size_bytes:bytes.length,sha256:sha,mime_type:'application/pdf',file_name:'../../original.pdf'}]},report:{rows:[{flow:'expense',entryId:entry.id,date:'2026-10-01',cents:2500,method:'card',recipient:entry.recipient,reference:'REF1',source:'Ausgabe',description:'Fuel'}],conflicts:[],pending:[]}}}
test('ZIP keeps original bytes, safe paths, checksum manifest and untrusted CSV cells; exports every row',async()=>{const {data,report}=fixture();report.rows.push(...Array.from({length:60},()=>({...report.rows[0]})));let verified=false;const pack=await buildAccountingPackage({data,report,month:'2026-10',download:async()=>bytes,verifySnapshot:async()=>verified=true});const zip=unzipSync(pack.bytes);assert.deepEqual(zip['Belege/expense1/doc1.pdf'],bytes);assert.equal(Object.keys(zip).length,6);assert.ok(verified);assert.equal(strFromU8(zip['Zahlungen.csv']).split('\r\n').length,62);assert.match(strFromU8(zip['Ausgaben.csv']),/'=UNTRUSTED/);assert.match(strFromU8(zip['Belegverzeichnis.csv']),new RegExp(sha));assert.match(strFromU8(zip['Hinweise.txt']),/keine DATEV-Buchungssätze/);assert.equal(pack.missingCount,0)});
test('archives remain in manifest, never in original folder; missing originals are explicit',async()=>{const {data,report}=fixture();data.accounting_documents[0].status='archived';const pack=await buildAccountingPackage({data,report,month:'2026-10',download:()=>{throw Error('Archive must not download')}});const zip=unzipSync(pack.bytes);assert.equal(pack.fileCount,0);assert.equal(pack.missingCount,1);assert.equal(Object.keys(zip).length,5);assert.match(strFromU8(zip['Belegverzeichnis.csv']),/archived/);assert.match(strFromU8(zip['Klaerungen.csv']),/Ausgabenbeleg fehlt/)});
test('size, actual MIME, checksum or mid-export data change prevents package completion',async()=>{for(const bad of [bytes.slice(1),new Uint8Array(bytes.length),new TextEncoder().encode('%PDF-1.7\noriginal expensX')]){const f=fixture();await assert.rejects(()=>buildAccountingPackage({...f,month:'2026-10',download:async()=>bad}),/Format|Prüfsumme/)}const f=fixture();await assert.rejects(()=>buildAccountingPackage({...f,month:'2026-10',download:async()=>bytes,verifySnapshot:async()=>{throw Error('Changed')}}),/Changed/)});
test('open uploads, metadata mismatch, wrong unit, oversized and excessive packages reject before download',()=>{for(const change of [d=>d.status='pending',d=>d.sha256=null,d=>d.business_unit_id='foreign',d=>d.size_bytes=MAX_EXPORT_BYTES+1,d=>d.mime_type='text/html']){const f=fixture();change(f.data.accounting_documents[0]);assert.throws(()=>expenseExportPlan(f.data,f.report))}const f=fixture();f.data.accounting_documents=Array.from({length:101},(_,n)=>({...f.data.accounting_documents[0],id:'doc'+n}));assert.throws(()=>expenseExportPlan(f.data,f.report),/100 Original/)});
test('filtered or cancelled expenses exclude their originals and snapshots ignore row/key order',()=>{const f=fixture();const a=accountingExportSnapshot(f.data),reordered=JSON.parse(JSON.stringify(f.data));reordered.accounting_documents[0]=Object.fromEntries(Object.entries(reordered.accounting_documents[0]).reverse());assert.equal(accountingExportSnapshot(reordered),a);reordered.accounting_documents[0].status='archived';assert.notEqual(accountingExportSnapshot(reordered),a);f.report.rows=[];assert.equal(expenseExportPlan(f.data,f.report).ready.length,0);f.data.accounting_entries[0].cancelled_at='2026-10-02';f.report.rows=[{flow:'expense',entryId:'expense1'}];assert.throws(()=>expenseExportPlan(f.data,f.report),/Zuordnung/)});
