import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {transform} from 'esbuild';
import * as contractRules from '../supabase/functions/_shared/contracts.js';
import * as tariffRules from '../supabase/functions/_shared/tariffs.js';
import * as businessRules from '../supabase/functions/_shared/businessProfile.js';
import * as correctionRules from '../supabase/functions/_shared/financeCorrections.js';
import * as copayRules from '../supabase/functions/_shared/copay.js';
const rules={...contractRules,...tariffRules,...businessRules,...correctionRules,...copayRules};
const unit='unit',org='org',day='2026-10-07';
const group={id:'group',business_unit_id:unit,active:true,contract_scope:'group',contract_group:'ersatzkassen',base_fee:2.4,price_per_km:2.1};
function database(contracts=[]){
 const rows={billing_profiles:[{business_unit_id:unit,company_name:'Testunternehmen',street:'Teststraße 1',postal_code:'12345',city:'Teststadt'}],app_profiles:[{id:'user',organization_id:org,active:true}],business_units:[{id:unit,organization_id:org,code:'fahrdienst',active:true}],memberships:[{user_id:'user',business_unit_id:unit,active:true,role:'admin'}],health_insurers:[{id:'tk',name:'Techniker',organization_id:org,active:true}],payer_contracts:contracts.map(c=>structuredClone(c)),customer_insurances:[{id:'insurance',customer_id:'customer',exempt:false}],trips:[{id:'trip',business_unit_id:unit,service_date:day,trip_type:'Dialyse',status:'abgeschlossen',from_address:'A',to_address:'B'}],customers:[{id:'customer',first_name:'Test',last_name:'Patient'}],contract_rates:[{contract_id:'group',active:true,position_code:'5130XX',sort_order:0}],trip_billing_cases:[{id:'case',trip_id:'trip',customer_id:'customer',business_unit_id:unit,insurance_id:'insurance',insurer_id:'tk',contract_id:'group',billing_status:'ready',payer_type:'insurer',invoice_id:null,copay_rule_version:1,gross_amount:33.9,own_share_amount:5,billable_km:15,insurer_amount:28.9,tariff_breakdown:tariffRules.calculateTariff(group,[],{date:day,km:15,positionCode:'5130XX',treatmentCode:'52'}).lines,position_code:'5130XX',treatment_code:'52',billing_position:'513052'}]};
 const writes=[];
 const db={async rpc(name,args){writes.push({rpc:name,args});if(name==='issue_case_finance_invoice'){writes.push({table:'invoices',insert:{...args.p_header,issuer_snapshot:args.p_header.issuerSnapshot}});writes.push({table:'invoice_items',insert:args.p_items});writes.push({table:'trip_billing_cases',patch:{billing_status:'invoiced'}});}return {data:{ok:true,id:'new',invoiceNumber:'RE-TEST'},error:null};},auth:{getUser:async()=>({data:{user:{id:'user'}}})},from(table){let filters=[],single=false,patch=null,insert=null,upsertOptions=null;
 const q={is(k,v){filters.push(r=>(r[k]??null)===v);return q},or(){return q},ilike(k,v){filters.push(r=>String(r[k]).toLowerCase()===String(v).toLowerCase());return q},select(){return q},eq(k,v){filters.push(r=>r[k]===v);return q},not(k,op,v){filters.push(r=>r[k]!==v);return q},order(){return q},limit(){return q},maybeSingle(){single=true;return q},single(){single=true;return q},update(v){patch=v;return q},upsert(v,options){insert=v;upsertOptions=options;return q},insert(v){insert=v;return q},delete(){return q},then(resolve,reject){try{let data=(rows[table]||[]).filter(r=>filters.every(f=>f(r)));if(patch){writes.push({table,patch});data=data.map(r=>Object.assign(r,patch));}if(insert){writes.push({table,insert,upsertOptions});data=[{id:'new',document_seq:1,...insert}];}return Promise.resolve({data:single?data[0]||null:data,error:null}).then(resolve,reject);}catch(e){return Promise.reject(e).then(resolve,reject)}}};return q}};
 return {db,writes,rows};
}
async function handler(name,db){const source=fs.readFileSync(`supabase/functions/${name}/index.ts`,'utf8').replace(/^import .*;\n/gm,'');const {code}=await transform(source,{loader:'ts'});let handle;const Deno={env:{get:()=> 'test'},serve:f=>handle=f};new Function('Deno','createClient',...Object.keys(rules),code)(Deno,()=>db,...Object.values(rules));return handle;}
async function call(name,setup,body){const handle=await handler(name,setup.db);const response=await handle(new Request('https://example.test',{method:'POST',headers:{Authorization:'Bearer test','Content-Type':'application/json'},body:JSON.stringify({businessUnitCode:'fahrdienst',caseId:'case',...body})}));return {status:response.status,body:await response.json()};}
test('Taxi insurer invoices use the same mandatory contract validation as Fahrdienst',async()=>{
 const setup=database([]);setup.rows.business_units[0].code='taxi';
 const r=await call('manage-finance',setup,{businessUnitCode:'taxi',action:'create_invoice',payerType:'insurer',insurerId:'tk',serviceDate:day,items:[{description:'Krankenfahrt',quantity:1,unitGross:30}]});
 assert.equal(r.status,409);assert.equal(setup.writes.length,0);
});
test('invoice cannot use stale ready status when contract is absent, inactive or expired',async()=>{for(const contracts of [[],[{...group,active:false}],[{...group,valid_until:'2026-10-06'}]]){const setup=database(contracts);const r=await call('manage-trip-billing',setup,{action:'invoice'});assert.equal(r.status,409);assert.equal(setup.writes.length,0);}});
test('new individual contract forces recalculation instead of billing old group',async()=>{const setup=database([group,{...group,id:'own',insurer_id:'tk',contract_scope:'individual'}]);const r=await call('manage-trip-billing',setup,{action:'invoice'});assert.equal(r.status,409);assert.match(r.body.error,/neu berechnen/);});
test('server recalculates against group and generates correct AOK-style position',async()=>{const setup=database([group]);const r=await call('manage-trip-billing',setup,{action:'recalculate',billableKm:15,positionCode:'5130XX',treatmentCode:'52',ownShareAmount:5});assert.equal(r.status,200);assert.equal(r.body.case.billing_status,'ready');assert.equal(r.body.case.billing_position,'513052');assert.equal(r.body.case.gross_amount,33.9);assert.equal(r.body.case.insurer_amount,28.9);});
test('server blocks recalculation without contract and incomplete template stays review',async()=>{let setup=database([]);let r=await call('manage-trip-billing',setup,{action:'recalculate'});assert.equal(r.body.case.billing_status,'blocked');setup=database([group]);r=await call('manage-trip-billing',setup,{action:'recalculate',treatmentCode:''});assert.equal(r.body.case.billing_status,'review');assert.equal(r.body.case.billing_position,null);});
test('valid case creates insurer invoice and links billing case',async()=>{const setup=database([group]);const r=await call('manage-trip-billing',setup,{action:'invoice'});assert.equal(r.status,200);assert.ok(setup.writes.some(w=>w.table==='invoices'));assert.ok(setup.writes.some(w=>w.table==='trip_billing_cases'&&w.patch?.billing_status==='invoiced'));});
test('manual insurer invoice cannot bypass missing contract',async()=>{const setup=database([]);const r=await call('manage-finance',setup,{action:'create_invoice',payerType:'insurer',insurerId:'tk',serviceDate:day,items:[{description:'Krankenfahrt',quantity:1,unitGross:30}]});assert.equal(r.status,409);assert.equal(setup.writes.length,0);});

const tariffLines=[
 {id:'base',position_code:'611200',label:'Grundpauschale',kind:'base',unit:'ride',price:2.4,vehicle_class:'mietwagen',journey_kind:'single'},
 {id:'km',position_code:'613000',label:'Besetzt-km',kind:'km',unit:'km',price:2.35,vehicle_class:'mietwagen',journey_kind:'single'},
 {id:'short',position_code:'612900',label:'Kurzstrecke',kind:'surcharge',unit:'ride',price:2.2,vehicle_class:'mietwagen',journey_kind:'single',max_km:5}
];
test('server uses every matching tariff price and creates separate invoice items plus copay deduction',async()=>{
 const setup=database([{...group,tariff_lines:tariffLines}]);
 const r=await call('manage-trip-billing',setup,{action:'recalculate',billableKm:4,vehicleClass:'mietwagen',journeyKind:'single',ownShareAmount:5});
 assert.equal(r.status,200);assert.equal(r.body.case.gross_amount,14);assert.equal(r.body.case.insurer_amount,9);assert.equal(r.body.case.tariff_breakdown.length,3);
 assert.deepEqual(r.body.case.tariff_breakdown.map(l=>l.position_code),['611200','613000','612900']);
 const i=await call('manage-trip-billing',setup,{action:'invoice'});assert.equal(i.status,200);
 const lines=setup.writes.find(w=>w.table==='invoice_items').insert;assert.equal(lines.length,4);assert.equal(lines[1].quantity,4);assert.equal(lines[1].unit_gross,2.35);assert.equal(lines[3].unit_gross,-5);assert.equal(lines.reduce((s,l)=>s+l.gross_total,0),9);
});
test('changed tariff prices invalidate a ready case before invoice',async()=>{
 const setup=database([{...group,tariff_lines:tariffLines}]);await call('manage-trip-billing',setup,{action:'recalculate',billableKm:4,vehicleClass:'mietwagen',journeyKind:'single'});
 setup.rows.payer_contracts[0].tariff_lines=tariffLines.map(l=>({...l,price:l.kind==='km'?9:l.price}));
 const r=await call('manage-trip-billing',setup,{action:'invoice'});assert.equal(r.status,409);assert.match(r.body.error,/Tarifpositionen/);
});
test('wheelchair billing cannot use a standard contract even with stale ready status',async()=>{
 const setup=database([group]);setup.rows.trips[0].customer_mobility='wheelchair';
 const r=await call('manage-trip-billing',setup,{action:'invoice'});assert.equal(r.status,409);
 const recalc=await call('manage-trip-billing',setup,{action:'recalculate'});assert.equal(recalc.body.case.billing_status,'blocked');assert.equal(recalc.body.case.gross_amount,0);
});
test('wheelchair recalculation uses its own contract and no normal wheelchair surcharge',async()=>{
 const setup=database([group,{...group,id:'wheel',service_type:'wheelchair',wheelchair_surcharge:999,tariff_lines:tariffLines}]);setup.rows.trips[0].customer_mobility='wheelchair';
 const r=await call('manage-trip-billing',setup,{action:'recalculate',billableKm:4,vehicleClass:'mietwagen',journeyKind:'single'});
 assert.equal(r.body.case.contract_id,'wheel');assert.equal(r.body.case.gross_amount,14);assert.equal(r.body.case.wheelchair_surcharge_applied,false);
});
test('contract saves its whole normalized tariff table in one write',async()=>{
 const setup=database([group]);
 const r=await call('manage-contracts',setup,{action:'save_contract',contractId:'group',contractName:'Ersatzkassen',contractScope:'group',contractGroup:'ersatzkassen',serviceType:'wheelchair',tariffLines});
 assert.equal(r.status,200);assert.equal(setup.writes.length,1);assert.equal(setup.writes[0].patch.service_type,'wheelchair');assert.equal(setup.writes[0].patch.tariff_lines.length,3);
});
test('invalid tariff table produces no partial contract writes',async()=>{
 const setup=database([group]);
 const r=await call('manage-contracts',setup,{action:'save_contract',contractId:'group',contractName:'Ersatzkassen',contractScope:'group',contractGroup:'ersatzkassen',tariffLines:[...tariffLines,tariffLines[0]]});
 assert.equal(r.status,400);assert.equal(setup.writes.length,0);
});
test('only admins can save company data and scope comes from authenticated unit',async()=>{
 const setup=database();setup.rows.memberships[0].role='office';
 let r=await call('manage-finance',setup,{action:'save_company_profile',profile:{company_name:'Other'}});assert.equal(r.status,403);assert.equal(setup.writes.length,0);
 setup.rows.memberships[0].role='admin';r=await call('manage-finance',setup,{action:'save_company_profile',profile:{company_name:'Test',business_unit_id:'foreign'}});assert.equal(r.status,200);assert.equal(setup.writes[0].insert.business_unit_id,unit);
});
test('new invoices require issuer address and capture issuer independently of later settings',async()=>{
 const setup=database();const body={action:'create_invoice',payerName:'Test',serviceDate:day,items:[{description:'Fahrt',quantity:1,unitGross:10}]};
 let r=await call('manage-finance',setup,body);assert.equal(r.status,200);
 const invoice=setup.writes.find(w=>w.table==='invoices'&&w.insert).insert;assert.equal(invoice.service_date,day);assert.equal(invoice.issuer_snapshot.company_name,'Testunternehmen');
 setup.rows.billing_profiles[0].company_name='Neuer Name';assert.equal(invoice.issuer_snapshot.company_name,'Testunternehmen');
 setup.rows.billing_profiles=[];r=await call('manage-finance',setup,body);assert.equal(r.status,409);
});
test('invoice and receipt billing paths snapshot the issuer',async()=>{
 const setup=database([{...group,service_type:'standard',tariff_lines:null}]);assert.equal((await call('manage-trip-billing',setup,{action:'invoice'})).status,200);
 assert.equal(setup.writes.find(w=>w.table==='invoices'&&w.insert).insert.issuer_snapshot.street,'Teststraße 1');
 assert.equal((await call('manage-finance',setup,{action:'create_receipt',amount:5,receivedFrom:'Test',receiptType:'own_share'})).status,200);
 assert.equal(setup.writes.find(w=>w.table==='receipts'&&w.insert).insert.issuer_snapshot.company_name,'Testunternehmen');
});
test('profile rejects invalid banking and IK fields while permitting incomplete drafts',()=>{
 assert.throws(()=>businessRules.normalizeProfile({iban:'DE00123456789012345678'}),/IBAN/);
 assert.throws(()=>businessRules.normalizeProfile({ik_number:'123'}),/IK/);
 assert.throws(()=>businessRules.normalizeProfile({bic:'123'}),/BIC/);
 assert.equal(businessRules.normalizeProfile({iban:'DE89 3704 0044 0532 0130 00'}).iban,'DE89370400440532013000');
 assert.equal(businessRules.normalizeProfile({}).company_name,null);
});

test('cancellation requires reason and scopes actor from verified membership',async()=>{const setup=database();let r=await call('manage-finance',setup,{action:'cancel_invoice',invoiceId:'original',reason:'x'});assert.equal(r.status,400);assert.equal(setup.writes.length,0);r=await call('manage-finance',setup,{action:'cancel_invoice',invoiceId:'original',reason:'Falscher Betrag',actor:'foreign',unit:'foreign'});assert.equal(r.status,200);assert.equal(setup.writes[0].args.p_actor,'user');assert.equal(setup.writes[0].args.p_unit,'unit');});
test('old status cancellation cannot bypass cancellation document',async()=>{const setup=database();const r=await call('manage-finance',setup,{action:'set_invoice_status',invoiceId:'original',status:'cancelled'});assert.equal(r.status,400);assert.equal(setup.writes.length,0);});
test('correction rejects invalid money and dates',()=>{assert.throws(()=>correctionRules.correctionItems([{description:'Fahrt',quantity:1,unitGross:''}]),/ungültig/);assert.throws(()=>correctionRules.correctionItems([{description:'Fahrt',quantity:1,unitGross:-5}]),/ungültig/);assert.throws(()=>correctionRules.correctionHeader({serviceDate:'2026-02-30'}, {},{}),/Leistungsdatum/);assert.equal(correctionRules.correctionItems([{description:'Fahrt',quantity:2,unitGross:2.345}])[0].unitGross,2.35);});
test('copay input cannot bypass automatic 10 percent and upper limit',async()=>{const setup=database([{...group,base_fee:0,price_per_km:8}]);let r=await call('manage-trip-billing',setup,{action:'recalculate',billableKm:15,ownShareAmount:0});assert.equal(r.status,200);assert.equal(r.body.case.gross_amount,120);assert.equal(r.body.case.own_share_amount,10);assert.equal(r.body.case.insurer_amount,110);assert.equal(r.body.case.copay_rule_version,1);});
test('5148 meter amount drives tariff and always five euros of copay',async()=>{const setup=database([group]);setup.rows.contract_rates[0].position_code='5148XX';setup.rows.trip_billing_cases[0].position_code='5148XX';const r=await call('manage-trip-billing',setup,{action:'recalculate',meterAmount:120,ownShareAmount:99});assert.equal(r.status,200);assert.equal(r.body.case.gross_amount,120);assert.equal(r.body.case.own_share_amount,5);assert.equal(r.body.case.insurer_amount,115);assert.equal(r.body.case.billing_position,'514852');});
test('valid exemption removes copay but expired exemption does not',async()=>{for(const [until,expected] of [[day,0],['2026-10-06',5]]){const setup=database([group]);Object.assign(setup.rows.customer_insurances[0],{exempt:true,exempt_until:until});const r=await call('manage-trip-billing',setup,{action:'recalculate'});assert.equal(r.status,200);assert.equal(r.body.case.own_share_amount,expected);}});
test('issued copay receipt cannot be silently changed by new calculation',async()=>{const setup=database([{...group,base_fee:120,price_per_km:0}]);Object.assign(setup.rows.trip_billing_cases[0],{receipt_id:'receipt',own_share_paid:true,own_share_amount:5});const r=await call('manage-trip-billing',setup,{action:'recalculate'});assert.equal(r.status,409);assert.equal(setup.writes.length,0);});
test('old ready cases and changed exemption require recalculation before invoices',async()=>{const setup=database([group]);setup.rows.trip_billing_cases[0].copay_rule_version=0;assert.equal((await call('manage-trip-billing',setup,{action:'invoice'})).status,409);setup.rows.trip_billing_cases[0].copay_rule_version=1;setup.rows.customer_insurances[0].exempt=true;assert.equal((await call('manage-trip-billing',setup,{action:'invoice'})).status,409);assert.equal(setup.writes.length,0);});
test('private case calculates full patient fare without insurance or contract and invoices tax snapshot',async()=>{const setup=database([]);Object.assign(setup.rows.trip_billing_cases[0],{payer_type:'private',insurance_id:null,insurer_id:null,contract_id:null});setup.rows.customer_insurances=[];let r=await call('manage-trip-billing',setup,{action:'recalculate',privateAmount:119,privateVatRate:19});assert.equal(r.status,200);assert.equal(r.body.case.gross_amount,119);assert.equal(r.body.case.own_share_amount,0);assert.equal(r.body.case.insurer_amount,0);r=await call('manage-trip-billing',setup,{action:'invoice'});assert.equal(r.status,200);const args=setup.writes.find(w=>w.rpc==='issue_case_finance_invoice').args;assert.equal(args.p_header.payerName,'Test Patient');assert.equal(args.p_items[0].net_total,100);assert.equal(args.p_items[0].vat_total,19);assert.equal(args.p_items[0].gross_total,119);});
test('private invoice and receipt paths reject unfinished trips, missing prices and fake copays',async()=>{const setup=database([]);Object.assign(setup.rows.trip_billing_cases[0],{payer_type:'private',private_amount:20,gross_amount:20,own_share_amount:0,insurer_amount:0});setup.rows.trips[0].status='in_fahrt';assert.equal((await call('manage-trip-billing',setup,{action:'invoice'})).status,409);assert.equal((await call('manage-trip-billing',setup,{action:'own_share_receipt'})).status,409);assert.equal((await call('manage-trip-billing',setup,{action:'recalculate',privateAmount:''})).status,400);});
test('receipt creation uses atomic RPC, scoped actor, actual payment method and version guard',async()=>{const setup=database([group]);Object.assign(setup.rows.trip_billing_cases[0],{own_share_required:true});let r=await call('manage-trip-billing',setup,{action:'own_share_receipt',paymentMethod:'card'});assert.equal(r.status,200);assert.equal(setup.writes[0].rpc,'issue_case_own_share_receipt');assert.equal(setup.writes[0].args.p_header.paymentMethod,'card');assert.equal(setup.writes[0].args.p_actor,'user');setup.rows.trip_billing_cases[0].copay_rule_version=0;r=await call('manage-trip-billing',setup,{action:'own_share_receipt'});assert.equal(r.status,409);});

test('completed private trip creates a ready full-price case even when patient has insurance',async()=>{const setup=database([]);setup.rows.trip_billing_cases=[];Object.assign(setup.rows.trips[0],{status:'in_fahrt',billing_payer_type:'private',private_price:119,private_vat_rate:19});const r=await call('manage-dispatch',setup,{action:'update_status',tripId:'trip',status:'abgeschlossen'});assert.equal(r.status,200);const inserted=setup.writes.find(w=>w.table==='trip_billing_cases').insert;assert.equal(inserted.payer_type,'private');assert.equal(inserted.gross_amount,119);assert.equal(inserted.own_share_amount,0);assert.equal(inserted.private_vat_rate,19);assert.equal(inserted.billing_status,'ready');assert.ok(setup.writes.some(w=>w.upsertOptions?.ignoreDuplicates));});
test('private trip without price stays review; repeat completion keeps an existing case',async()=>{const setup=database([]);setup.rows.trip_billing_cases=[];Object.assign(setup.rows.trips[0],{status:'in_fahrt',billing_payer_type:'private',private_price:null});let r=await call('manage-dispatch',setup,{action:'update_status',tripId:'trip',status:'abgeschlossen'});assert.equal(r.status,200);assert.equal(setup.writes.find(w=>w.table==='trip_billing_cases').insert.billing_status,'review');setup.rows.trip_billing_cases=[{id:'case',trip_id:'trip'}];setup.writes.length=0;r=await call('manage-dispatch',setup,{action:'update_status',tripId:'trip',status:'abgeschlossen'});assert.equal(r.status,200);assert.equal(setup.writes.filter(w=>w.table==='trip_billing_cases').length,0);});

test('patient copay invoice uses atomic scoped RPC with no insurer invoice or paid state mutation',async()=>{const setup=database([group]);Object.assign(setup.rows.trip_billing_cases[0],{own_share_required:true});const r=await call('manage-trip-billing',setup,{action:'own_share_invoice',dueDate:'2026-10-25',ownShareAmount:99,payerName:'Foreign'});assert.equal(r.status,200);assert.equal(setup.writes.length,1);const w=setup.writes[0];assert.equal(w.rpc,'issue_case_own_share_invoice');assert.equal(w.args.p_actor,'user');assert.equal(w.args.p_unit,unit);assert.equal(w.args.p_case,'case');assert.equal(w.args.p_header.dueDate,'2026-10-25');assert.equal(w.args.p_header.payerName,undefined);assert.equal(w.args.p_header.issuerSnapshot.company_name,'Testunternehmen');assert.equal(setup.rows.trip_billing_cases[0].invoice_id,null);});
test('copay invoice blocks paid, quittiert, unfinished, private and newly exempt cases',async()=>{for(const patch of [{own_share_paid:true},{receipt_id:'paid'},{payer_type:'private'},{copay_rule_version:0},{own_share_amount:0}]){const setup=database([group]);Object.assign(setup.rows.trip_billing_cases[0],patch);const r=await call('manage-trip-billing',setup,{action:'own_share_invoice'});assert(r.status>=400);assert.equal(setup.writes.length,0)}const setup=database([group]);setup.rows.trips[0].status='in_fahrt';assert.equal((await call('manage-trip-billing',setup,{action:'own_share_invoice'})).status,409);setup.rows.trips[0].status='abgeschlossen';setup.rows.customer_insurances[0].exempt=true;assert.equal((await call('manage-trip-billing',setup,{action:'own_share_invoice'})).status,409)});
test('own invoice prevents second receipt and recalculation and repeats safely through the RPC',async()=>{const setup=database([group]);Object.assign(setup.rows.trip_billing_cases[0],{own_share_invoice_id:'own',own_share_required:true});assert.equal((await call('manage-trip-billing',setup,{action:'own_share_receipt'})).status,409);assert.equal((await call('manage-trip-billing',setup,{action:'recalculate'})).status,409);assert.equal(setup.writes.length,0);const r=await call('manage-trip-billing',setup,{action:'own_share_invoice'});assert.equal(r.status,200);assert.equal(setup.writes[0].rpc,'issue_case_own_share_invoice')});
test('payment status uses a transaction with verified actor instead of a detached invoice update',async()=>{const setup=database([group]);const r=await call('manage-finance',setup,{action:'set_invoice_status',invoiceId:'own',status:'paid',actor:'foreign'});assert.equal(r.status,200);assert.equal(setup.writes.length,1);assert.deepEqual(setup.writes[0],{rpc:'mark_finance_invoice_paid',args:{p_invoice:'own',p_unit:unit,p_actor:'user'}})});

test('schedule RPC is scoped to authenticated office actor and keeps optional end date',async()=>{const setup=database();const r=await call('manage-schedules',setup,{action:'create_series',customerId:'customer',startDate:'2026-09-01',endDate:'',weekdays:[1,3,5],outboundTime:'08:00',returnTime:'13:00',directions:2});assert.equal(r.status,200);const w=setup.writes.find(w=>w.rpc==='manage_trip_series_schedule');assert.equal(w.args.p_unit,unit);assert.equal(w.args.p_actor,'user');assert.equal(w.args.p_payload.endDate,'');assert.equal(w.args.p_series,null);});
test('schedule changes and pause use one atomic RPC without detached trip deletion',async()=>{for(const action of ['update_series','set_series_active']){const setup=database();const r=await call('manage-schedules',setup,{action,seriesId:'series',active:false});assert.equal(r.status,200);assert.equal(setup.writes.length,1);assert.equal(setup.writes[0].args.p_series,'series');assert.equal(setup.writes[0].args.p_action,action);}});
test('driver cannot create or edit a series',async()=>{const setup=database();setup.rows.memberships[0].role='driver';const r=await call('manage-schedules',setup,{action:'create_series'});assert.equal(r.status,403);assert.equal(setup.writes.length,0);});

test('historical confirmation requires staff and explicit attestation',async()=>{let setup=database();setup.rows.memberships[0].role='driver';let r=await call('manage-dispatch',setup,{action:'record_history',confirmed:true,entries:[{id:'trip'}],decision:'abgeschlossen',note:'QA'});assert.equal(r.status,403);assert.equal(setup.writes.length,0);setup=database();r=await call('manage-dispatch',setup,{action:'record_history',entries:[{id:'trip'}],decision:'abgeschlossen',note:'Nachweis geprüft'});assert.equal(r.status,400);assert.equal(setup.writes.length,0);});
test('history sends only scoped server actor, trip version and decision to atomic RPC',async()=>{const setup=database();const r=await call('manage-dispatch',setup,{action:'record_history',confirmed:true,actor:'forged',unit:'forged',entries:[{id:'trip',updatedAt:'2026-09-02T08:00:00Z',amount:999,status:'paid'}],decision:'abgeschlossen',note:'Nachweis geprüft'});assert.equal(r.status,200);assert.deepEqual(setup.writes[0],{rpc:'record_historical_trips',args:{p_unit:unit,p_actor:'user',p_entries:[{id:'trip',updatedAt:'2026-09-02T08:00:00Z'}],p_decision:'abgeschlossen',p_note:'Nachweis geprüft'}});});
test('invalid historical selection creates no writes',async()=>{for(const patch of [{entries:[]},{entries:[{id:'t'},{id:'t'}]},{decision:'paid'},{note:''},{entries:Array.from({length:101},(_,i)=>({id:String(i)}))}]){const setup=database();const r=await call('manage-dispatch',setup,{action:'record_history',confirmed:true,entries:[{id:'t',updatedAt:'date'}],decision:'abgeschlossen',note:'Nachweis geprüft',...patch});assert.equal(r.status,400);assert.equal(setup.writes.length,0);}});

test('monthly invoice verifies each patient case and passes reviewed versions with authenticated actor only',async()=>{const setup=database([group]);setup.rows.trip_billing_cases[0].invoice_id='insurer-invoice';const r=await call('manage-trip-billing',setup,{action:'monthly_own_share_invoice',customerId:'customer',month:'2026-10',entries:[{id:'case',updatedAt:'reviewed-version',amount:999}],actor:'forged'});assert.equal(r.status,200);assert.equal(setup.writes[0].rpc,'issue_monthly_own_share_invoice');assert.equal(setup.writes[0].args.p_actor,'user');assert.deepEqual(setup.writes[0].args.p_entries,[{id:'case',updatedAt:'reviewed-version'}]);assert.equal(setup.writes[0].args.p_month,'2026-10-01');});
test('monthly invoice rejects mixed patient, period, paid receipt and changed tariff before writing',async()=>{for(const patch of [{customerId:'other'},{month:'2026-09'},{month:'2026-99'},{entries:[{id:'case'},{id:'case'}]},{paid:true},{receipt:true},{noContract:true}]){const setup=database(patch.noContract?[]:[group]);if(patch.paid)setup.rows.trip_billing_cases[0].own_share_paid=true;if(patch.receipt)setup.rows.trip_billing_cases[0].receipt_id='r';const r=await call('manage-trip-billing',setup,{action:'monthly_own_share_invoice',customerId:'customer',month:'2026-10',entries:[{id:'case'}],...patch});assert(r.status>=400);assert.equal(setup.writes.length,0);}});
test('ZAD register derives unit and actor from authentication and requires actual action confirmation',async()=>{
 const setup=database();
 let r=await call('manage-finance',setup,{action:'update_submission',id:'run',step:'web',date:'2026-10-08'});
 assert.equal(r.status,400);assert.equal(setup.writes.length,0);
 r=await call('manage-finance',setup,{action:'create_submission',p_actor:'forged',entries:[{id:'case'}]});
 assert.equal(r.status,200);assert.equal(setup.writes[0].rpc,'create_billing_submission');assert.equal(setup.writes[0].args.p_actor,'user');assert.equal(setup.writes[0].args.p_unit,'unit');
 setup.rows.memberships[0].role='driver';r=await call('manage-finance',setup,{action:'update_submission',id:'run',step:'post',confirmed:true});assert.equal(r.status,403);assert.equal(setup.writes.length,1);
});
test('document review requires confirmation, derives actor/unit and rejects driver inspection',async()=>{
 const s=database();let r=await call('manage-finance',s,{action:'save_billing_document_check',selection:{}});assert.equal(r.status,400);assert.equal(s.writes.length,0);
 r=await call('manage-finance',s,{action:'inspect_billing_documents',caseIds:['case']});assert.equal(r.status,200);assert.equal(s.writes[0].args.p_actor,'user');assert.equal(s.writes[0].args.p_unit,'unit');
 r=await call('manage-finance',s,{action:'save_billing_document_check',confirmed:true,selection:{approvalRequired:false,note:'Testvermerk'},versions:{}});assert.equal(r.status,200);assert.equal(s.writes[1].rpc,'save_billing_document_check');
 s.rows.memberships[0].role='driver';assert.equal((await call('manage-finance',s,{action:'inspect_billing_documents',caseIds:['case']})).status,403);
});
test('insurer payment register requires actual confirmation and scopes authenticated actor',async()=>{
 const s=database();let r=await call('manage-finance',s,{action:'record_insurer_payment',submissionId:'run',entries:[]});assert.equal(r.status,400);assert.equal(s.writes.length,0);
 r=await call('manage-finance',s,{action:'record_insurer_payment',submissionId:'run',confirmed:true,requestId:'id',date:'2026-10-08',amount:60,reference:'BANK',entries:[]});assert.equal(r.status,200);assert.equal(s.writes[0].rpc,'record_insurer_payment');assert.equal(s.writes[0].args.p_actor,'user');assert.equal(s.writes[0].args.p_unit,'unit');
 s.rows.memberships[0].role='driver';assert.equal((await call('manage-finance',s,{action:'insurer_payment_report',submissionId:'run'})).status,403);
});

test('reminder RPCs require verified office scope and explicit confirmation for writes',async()=>{
 const setup=database();setup.rows.memberships[0].role='driver';let r=await call('manage-finance',setup,{action:'prepare_patient_reminder',confirmed:true});assert.equal(r.status,403);
 setup.rows.memberships[0].role='office';r=await call('manage-finance',setup,{action:'prepare_patient_reminder'});assert.equal(r.status,400);
 r=await call('manage-finance',setup,{action:'update_patient_reminder',step:'sent'});assert.equal(r.status,400);
 const calls=[];setup.db.rpc=async(name,params)=>{calls.push({name,params});return{data:{id:'reminder'}}};
 r=await call('manage-finance',setup,{action:'prepare_patient_reminder',confirmed:true,requestId:'request',invoiceId:'invoice',expected:{id:'invoice'},deadline:'2026-10-23',message:'Bitte bezahlen.',p_actor:'forged',p_unit:'other'});assert.equal(r.status,200);assert.equal(calls[0].params.p_actor,'user');assert.equal(calls[0].params.p_unit,unit);
 r=await call('manage-finance',setup,{action:'inspect_patient_reminder',id:'reminder'});assert.equal(r.status,200);assert.equal(calls[1].name,'inspect_patient_reminder');
 r=await call('manage-finance',setup,{action:'update_patient_reminder',id:'reminder',step:'sent',confirmed:true,date:'2026-10-09',channel:'post',destination:'Teststraße 1'});assert.equal(r.status,200);assert.equal(calls[2].params.p_actor,'user');assert.equal(calls[2].params.p_step,'sent');
});

test('patient payment RPCs verify actor and scope and require actual-payment confirmation',async()=>{
 const s=database();assert.equal((await call('manage-finance',s,{action:'record_patient_payment',invoiceId:'invoice'})).status,400);assert.equal((await call('manage-finance',s,{action:'cancel_patient_payment',paymentId:'payment'})).status,400);
 const calls=[];s.db.rpc=async(name,params)=>{calls.push({name,params});return{data:{ok:true}}};
 let r=await call('manage-finance',s,{action:'record_patient_payment',confirmed:true,invoiceId:'invoice',requestId:'request',version:'v',date:'2026-10-09',amount:10,method:'bank',reference:'TEST',p_actor:'forged',p_unit:'other'});assert.equal(r.status,200);assert.equal(calls[0].params.p_actor,'user');assert.equal(calls[0].params.p_unit,unit);assert.equal(calls[0].params.p_amount,10);assert.equal(calls[0].params.p_version,'v');
 r=await call('manage-finance',s,{action:'patient_payment_report',invoiceId:'invoice'});assert.equal(r.status,200);assert.equal(calls[1].name,'patient_payment_report');s.rows.memberships[0].role='driver';assert.equal((await call('manage-finance',s,{action:'patient_payment_report',invoiceId:'invoice'})).status,403);
});

test('office can read reminder configuration but only admin can edit scoped settings',async()=>{const s=database();s.rows.memberships[0].role='office';assert.equal((await call('manage-finance',s,{action:'save_patient_reminder_settings',version:0,stages:[]})).status,403);assert.equal(s.writes.length,0);assert.equal((await call('manage-finance',s,{action:'patient_reminder_config'})).status,200);assert.equal(s.writes[0].args.p_actor,'user');s.rows.memberships[0].role='admin';assert.equal((await call('manage-finance',s,{action:'save_patient_reminder_settings',version:5,stages:[{days:7,message:'Text'}],p_unit:'forged',p_actor:'forged'})).status,200);assert.equal(s.writes[1].args.p_version,5);assert.equal(s.writes[1].args.p_unit,unit);assert.equal(s.writes[1].args.p_actor,'user');s.rows.memberships[0].role='driver';assert.equal((await call('manage-finance',s,{action:'patient_reminder_config'})).status,403)});
test('reminder preparation passes explicitly reviewed stage and settings version',async()=>{const s=database();assert.equal((await call('manage-finance',s,{action:'prepare_patient_reminder',confirmed:true,stage:2,settingsVersion:7})).status,200);assert.equal(s.writes[0].args.p_stage,2);assert.equal(s.writes[0].args.p_settings_version,7)});

test('shift endpoints derive actor/unit and reject office impersonation and missing mileage',async()=>{const s=database();assert.equal((await call('manage-driver-shifts',s,{action:'start',mileage:100})).status,403);s.rows.memberships[0].role='driver';s.rows.memberships[0].driver_id='driver';for(const mileage of [null,'',-1,1.5,'NaN'])assert.equal((await call('manage-driver-shifts',s,{action:'start',mileage})).status,400);assert.equal(s.writes.length,0);let r=await call('manage-driver-shifts',s,{action:'start',requestId:'request',vehicleId:'v',mileage:100,actor:'other',driverId:'other',p_unit:'other'});assert.equal(r.status,200);assert.equal(s.writes[0].args.p_actor,'user');assert.equal(s.writes[0].args.p_unit,unit);assert.equal(s.writes[0].args.p_mileage,100);assert.equal((await call('manage-driver-shifts',s,{action:'staff_report',month:'2026-10-01'})).status,403)});
test('office shift reports and vehicle assignments use scoped server RPCs',async()=>{const s=database();s.rows.memberships[0].role='office';let r=await call('manage-driver-shifts',s,{action:'staff_report',month:'2026-10-01',driverId:'d',offset:50});assert.equal(r.status,200);assert.equal(s.writes[0].rpc,'staff_shift_report');assert.equal(s.writes[0].args.p_offset,50);r=await call('manage-fleet',s,{action:'assign_vehicle',driverId:'d',vehicleId:'v',p_actor:'forged'});assert.equal(r.status,200);assert.equal(s.writes[1].rpc,'set_office_shift_vehicle');assert.equal(s.writes[1].args.p_actor,'user');assert.equal(s.writes[1].args.p_unit,unit);assert.equal(s.writes[1].args.p_vehicle,'v')});

test('accounting write requires confirmation, derives office actor/unit and ignores forged amount on dated invoice',async()=>{const setup=database([]);let called;setup.db.rpc=async(name,params)=>{called={name,params};return{data:{ok:true},error:null}};let r=await call('manage-finance',setup,{action:'record_accounting_entry',kind:'expense'});assert.equal(r.status,400);assert.equal(called,undefined);r=await call('manage-finance',setup,{action:'record_accounting_entry',confirmed:true,kind:'payment_date',invoiceId:'invoice',amount:999,unitId:'forged',actor:'forged',requestId:'request',date:'2026-09-01',method:'bank',description:'Confirmed date',reference:'BANK-1'});assert.equal(r.status,200);assert.equal(called.params.p_unit,unit);assert.notEqual(called.params.p_actor,'forged');assert.equal(called.params.p_amount,null)});
test('driver offline completion authenticates actor, invokes atomic RPC and keeps billing repeat-safe',async()=>{
 const setup=database([]);setup.rows.memberships[0].role='driver';setup.rows.memberships[0].driver_id='driver';setup.rows.trip_billing_cases=[];Object.assign(setup.rows.trips[0],{driver_id:'driver',customer_id:'customer',status:'in_fahrt',billing_payer_type:'private',private_price:50,private_vat_rate:0});const calls=[];setup.db.rpc=async(name,args)=>{calls.push({name,args});return{data:{ok:true,trip:{...setup.rows.trips[0],status:'abgeschlossen'}},error:null}};
 const body={action:'update_status',tripId:'trip',status:'abgeschlossen',requestId:'request',shiftId:'shift',expectedStatus:'in_fahrt',baseVersion:'version',predecessorId:'previous',recordedAt:'2026-10-10T12:00Z',p_actor:'forged',p_unit:'forged'};
 const r=await call('manage-dispatch',setup,body);assert.equal(r.status,200);assert.equal(calls[0].name,'sync_driver_trip_status');assert.equal(calls[0].args.p_actor,'user');assert.equal(calls[0].args.p_unit,unit);assert.equal(calls[0].args.p_event,body.recordedAt);assert.equal(setup.writes.filter(w=>w.table==='trips').length,0);assert.equal(setup.writes.find(w=>w.table==='trip_billing_cases').insert.gross_amount,50);
 setup.rows.trip_billing_cases=[{id:'already',trip_id:'trip'}];setup.writes.length=0;assert.equal((await call('manage-dispatch',setup,body)).status,200);assert.equal(setup.writes.length,0);
 setup.db.rpc=async()=>({error:{message:'Reassigned'}});assert.equal((await call('manage-dispatch',setup,body)).status,409);assert.equal(setup.writes.length,0);
});
