import test from 'node:test';
import assert from 'node:assert/strict';
import {buildBillingBatch,batchCsv,batchTotals,renderBillingBatch,validateBatch,batchFingerprint} from '../src/lib/billingBatch.js';
import {readPages,readByIds} from '../src/data/readPages.js';
function fixture(){const data={cases:[],trips:[],customers:[{id:'patient',first_name:'Erika',last_name:'Beispiel'}],insurers:[{id:'kasse',name:'Testkasse'}]},finance={invoices:[],invoiceItems:[]};for(const [id,direction,own] of [['hin','outbound',10],['back','return',5],['exempt','outbound',0]]){data.cases.push({id,trip_id:id,customer_id:'patient',insurer_id:'kasse',payer_type:'insurer',copay_rule_version:1,direction_count:1,billing_status:'invoiced',invoice_id:id,gross_amount:120,own_share_amount:own,insurer_amount:120-own,billing_position:own===5?'514852':'513052'});data.trips.push({id,service_date:'2026-10-08',direction,status:'abgeschlossen',from_address:'=Danger',to_address:'Test B'});finance.invoices.push({id,invoice_number:'RE-'+id,payer_type:'insurer',insurer_id:'kasse',customer_id:'patient',customer_name:'Erika <script>',service_date:'2026-10-08',status:'open',gross_total:120-own,issuer_snapshot:{company_name:'Testbetrieb'}});finance.invoiceItems.push({invoice_id:id,trip_id:id,gross_total:120-own})}return {data,finance}}
test('batch separates directions, fixed copay and exemption with exact cent sums',()=>{const f=fixture(),rows=buildBillingBatch(f.data,f.finance);assert(rows.every(r=>!r.reason));assert.equal(rows.find(r=>r.id==='back').direction,'Rückfahrt');assert.deepEqual(batchTotals(rows),{count:3,gross:36000,copay:1500,insurer:34500});assert.match(batchCsv(rows),/"5,00";"115,00"/);assert.match(batchCsv(rows),/'=Danger/);const html=renderBillingBatch(rows);assert(!html.includes('<script>'));assert.match(html,/Erika &lt;script&gt;/);assert.match(html,/345,00/)});
test('private cases and dates outside requested range are excluded',()=>{const f=fixture();f.data.cases[0].payer_type='private';assert.equal(buildBillingBatch(f.data,f.finance).length,2);assert.equal(buildBillingBatch(f.data,f.finance,{from:'2026-10-09'}).length,0);assert.equal(buildBillingBatch(f.data,f.finance,{insurerId:'other'}).length,0)});
for(const [name,mutate] of [
 ['missing invoice',f=>f.finance.invoices.shift()],['cancelled',f=>f.finance.invoices[0].status='cancelled'],['paid',f=>f.finance.invoices[0].status='paid'],['unfinished trip',f=>f.data.trips[0].status='planned'],['wrong payer',f=>f.finance.invoices[0].insurer_id='foreign'],['wrong patient',f=>f.finance.invoices[0].customer_id='foreign'],['wrong date',f=>f.finance.invoices[0].service_date='2026-10-09'],['missing issuer',f=>f.finance.invoices[0].issuer_snapshot=null],['old copay',f=>f.data.cases[0].copay_rule_version=0],['both directions case',f=>f.data.cases[0].direction_count=2],['wrong totals',f=>f.data.cases[0].insurer_amount=120],['missing amount',f=>f.data.cases[0].gross_amount=null],['missing invoice items',f=>f.finance.invoiceItems.shift()],['foreign trip item',f=>f.finance.invoiceItems[0].trip_id='other'],['item sum wrong',f=>f.finance.invoiceItems[0].gross_total=109]
])test('batch blocks '+name,()=>{const f=fixture();mutate(f);const row=buildBillingBatch(f.data,f.finance).find(r=>r.id==='hin');assert(row.reason);assert.throws(()=>batchCsv([row]));});
test('duplicate invoice rejects both cases',()=>{const f=fixture();f.data.cases.push({...f.data.cases[0],id:'duplicate'});const rows=buildBillingBatch(f.data,f.finance);assert(rows.find(r=>r.id==='hin').reason);assert(rows.find(r=>r.id==='duplicate').reason)});
test('selection cannot mix insurers or issuer snapshots and empty is rejected',()=>{const f=fixture(),rows=buildBillingBatch(f.data,f.finance);assert.throws(()=>validateBatch([]));rows[0].insurerId='other';assert.throws(()=>validateBatch(rows));rows[0].insurerId='kasse';rows[0].invoice.issuer_snapshot={company_name:'Other'};assert.throws(()=>validateBatch(rows))});
test('fingerprint detects cancellation, item changes and paid copay',()=>{const f=fixture(),rows=buildBillingBatch(f.data,f.finance),before=batchFingerprint(rows);f.data.cases[0].own_share_paid=true;assert.notEqual(before,batchFingerprint(buildBillingBatch(f.data,f.finance)))});
test('pages exceed API limit and handle a lower configured row cap',async()=>{const rows=Array.from({length:1201},(_,id)=>({id}));let calls=0;const result=await readPages(()=>({range:async(from,to)=>{calls++;return {data:rows.slice(from,Math.min(to+1,from+200)),count:rows.length}}}));assert.equal(result.length,1201);assert.equal(calls,7)});
test('page failure, duplicate, incomplete response and changing count block export data',async()=>{await assert.rejects(readPages(()=>({range:async()=>({error:Error('denied')})})),/denied/);await assert.rejects(readPages(()=>({range:async()=>({data:[],count:3})})),/vollständig/);await assert.rejects(readPages(()=>({range:async()=>({data:[{id:1}],count:3})})),/geändert/);let n=0;await assert.rejects(readPages(()=>({range:async()=>({data:[{id:n++}],count:n===1?3:4})})),/geändert/)});
test('ID batches stay within request size',async()=>{const ids=Array.from({length:205},(_,id)=>id),sizes=[];const rows=await readByIds(ids,group=>{sizes.push(group.length);return {range:async()=>({data:group.map(id=>({id})),count:group.length})}});assert.equal(rows.length,205);assert.deepEqual(sizes,[100,100,5])});
test('actual database status abgeschlossen is accepted; English completed is rejected',()=>{const f=fixture();assert.equal(buildBillingBatch(f.data,f.finance).filter(r=>!r.reason).length,3);f.data.trips[0].status='completed';assert(buildBillingBatch(f.data,f.finance).find(r=>r.id==='hin').reason)});
