import test from 'node:test';import assert from 'node:assert/strict';
import {calculateOwnShare,privateFare,insuranceValidOn} from '../supabase/functions/_shared/copay.js';
const insurance={exempt:false},date='2026-10-08';
const own=(gross,extra={})=>calculateOwnShare({gross,insurance,date,positionCode:'513052',...extra}).amount;
test('copay clamps each direction to 5..10 euros with cent precision',()=>{assert.equal(own(30),5);assert.equal(own(50),5);assert.equal(own(65.43),6.54);assert.equal(own(100),10);assert.equal(own(120),10);assert.equal(own(1000),10);assert.equal(own(120)+own(120),20);assert.equal(own(3),3);assert.equal(own(0),0);});
test('5148 uses five euros per direction regardless of high meter amount',()=>{assert.equal(own(120,{positionCode:'514852'}),5);assert.equal(own(120,{positionCode:'5148XX'}),5);assert.equal(own(120,{positionCode:null,lines:[{position_code:'514830',kind:'meter'}]}),5);assert.equal(own(120,{positionCode:'514852'})+own(120,{positionCode:'514852'}),10);});
test('exemption validity is evaluated at the service date',()=>{assert.equal(own(120,{insurance:{exempt:true}}),0);assert.equal(own(120,{insurance:{exempt:true,exempt_until:date}}),0);assert.equal(own(120,{insurance:{exempt:true,exempt_until:'2026-10-07'}}),10);assert.equal(own(120,{insurance:{exempt:false,exempt_until:'2027-01-01'}}),10);assert.equal(insuranceValidOn({valid_from:'2026-10-09'},date),false);assert.equal(insuranceValidOn({valid_until:'2026-10-07'},date),false);});
test('private gross prices have consistent tax amounts and reject missing/invalid inputs',()=>{assert.deepEqual(privateFare({amount:119,vatRate:19}),{gross:119,net:100,vat:19,vatRate:19});for(const amount of ['',null,-1,0,Infinity,'abc'])assert.throws(()=>privateFare({amount}));assert.throws(()=>privateFare({amount:10,vatRate:12}));});

test('every cent amount rounds 10 percent identically to decimal database arithmetic',()=>{for(let cents=0;cents<=10000;cents++){const expected=Math.min(cents/100,Math.max(5,Math.min(10,Math.floor((cents+5)/10)/100)));assert.equal(own(cents/100),expected,`${cents} cents`);}});
