import test from 'node:test';import assert from 'node:assert/strict';
import {createDriverOffline,effectiveTrips,offlineTrips} from '../src/lib/driverOffline.js';
import {OFFLINE_TTL} from '../src/lib/driverOfflineStore.js';
function setup(send=async e=>({ok:true,trip:{status:e.status,updatedAt:'new-version'}})){
 const records=new Map(),store={read:async k=>structuredClone(records.get(k)||null),update:async(k,f)=>{const r=f(structuredClone(records.get(k)||null));records.set(k,structuredClone(r));return structuredClone(r)}};let time=Date.parse('2026-10-10T12:00:00Z'),n=0;const c=createDriverOffline({store,scope:'u:a:d',send,now:()=>time,uuid:()=>`request-${++n}`});return {c,store,setTime:t=>time=t,trip:{id:'trip',date:'2026-10-10',time:'14:00',driverId:'d',vehicleId:'v',status:'geplant',updatedAt:'old-version'},shift:{id:'shift',vehicle_id:'v',state:'active'},time};
}
test('offline roster contains only this driver and near dates; excludes notes and billing fields',()=>{const rows=offlineTrips([{id:'own',driverId:'d',date:'2026-10-10',notes:'private',customerId:'private',privatePrice:80},{id:'other',driverId:'other',date:'2026-10-10'},{id:'far',driverId:'d',date:'2026-11-10'},{id:'active',driverId:'d',date:'2026-10-09',status:'in_fahrt'}],{driverId:'d'},Date.parse('2026-10-10T12:00Z'));assert.deepEqual(rows.map(r=>r.id),['own','active']);assert.ok(!Object.hasOwn(rows[0],'notes'));assert.ok(!Object.hasOwn(rows[0],'privatePrice'))});
test('queued workflow survives controller restart, preserves time, predecessor and request ID',async()=>{const s=setup(),sent=[];await s.c.snapshot([s.trip],null);let t=s.trip;for(const status of ['auf_dem_weg','angekommen','in_fahrt','abgeschlossen']){await s.c.enqueue(t,status,s.shift);t=effectiveTrips([s.trip],(await s.c.read()).queue)[0]}const queue=(await s.c.read()).queue;assert.equal(queue.length,4);assert.equal(queue[1].predecessorId,queue[0].requestId);assert.equal(queue[0].recordedAt,'2026-10-10T12:00:00.000Z');const restart=createDriverOffline({store:s.store,scope:'u:a:d',send:async e=>{sent.push(e);return{ok:true,trip:{status:e.status,updatedAt:'new'}}}});assert.equal((await restart.drain()).queue.length,0);assert.deepEqual(sent.map(e=>e.requestId),queue.map(e=>e.requestId));assert.equal((await restart.read()).trips[0].status,'abgeschlossen');assert.equal((await createDriverOffline({store:s.store,scope:'another',send:async()=>{throw Error()}}).read()).queue.length,0)});
test('lost acknowledgement retries same request; transport errors retain queue and server conflict blocks following changes',async()=>{let attempts=0;const seen=[],s=setup(async e=>{seen.push(e.requestId);return++attempts===1?{ok:false,httpStatus:503,message:'No acknowledgement'}:{ok:true,trip:{status:e.status,updatedAt:'new'}}});await s.c.snapshot([s.trip],null);await s.c.enqueue(s.trip,'auf_dem_weg',s.shift);assert.equal((await s.c.drain()).queue.length,1);assert.equal((await s.c.drain()).queue.length,0);assert.equal(seen[0],seen[1]);const conflict=setup(async()=>({ok:false,httpStatus:409,message:'Reassigned'}));await conflict.c.snapshot([conflict.trip],null);await conflict.c.enqueue(conflict.trip,'auf_dem_weg',conflict.shift);assert.equal((await conflict.c.drain()).queue[0].state,'blocked');await assert.rejects(()=>conflict.c.enqueue({...conflict.trip,status:'auf_dem_weg'},'angekommen',conflict.shift),/konflikt/);assert.equal((await conflict.c.drain()).queue.length,1)});
test('stale caches, wrong shift, skipped steps and unavailable storage never acknowledge local status',async()=>{const s=setup();await s.c.snapshot([s.trip],null);await assert.rejects(()=>s.c.enqueue(s.trip,'abgeschlossen',s.shift),/status/);await assert.rejects(()=>s.c.enqueue(s.trip,'auf_dem_weg',{...s.shift,state:'paused'}),/Schicht/);s.setTime(s.time+OFFLINE_TTL);await assert.rejects(()=>s.c.enqueue(s.trip,'auf_dem_weg',s.shift),/veraltet/);assert.equal((await s.c.read()).queue.length,0);const c=createDriverOffline({store:{update:async()=>{throw Error('Quota')}},scope:'scope',send:async()=>({ok:true})});await assert.rejects(()=>c.snapshot([],null),/Quota/)});
test('queue snapshots cannot overwrite pending base status or renew an old cache; discard clears locally without sending',async()=>{let sent=0;const s=setup(async()=>{sent++;return{ok:true}});await s.c.snapshot([s.trip],null);await s.c.enqueue(s.trip,'auf_dem_weg',s.shift);s.setTime(s.time+1000);await s.c.snapshot([{...s.trip,status:'storniert'}],undefined);assert.equal((await s.c.read()).trips[0].status,'geplant');assert.equal((await s.c.read()).savedAt,s.time);await s.c.discard();assert.equal((await s.c.read()).queue.length,0);assert.equal((await s.c.read()).trips.length,0);assert.equal(sent,0)});
