import {test} from 'node:test';import assert from 'node:assert/strict';
import {financeReport} from '../src/lib/financeReports.js';
const invoice=(id,extra={})=>({id,document_type:'invoice',status:'open',issue_date:'2026-09-30',payer_type:'insurer',insurer_id:'kasse',payer_name:'Testkasse',net_total:'90.00',vat_total:'0.00',gross_total:'90.00',...extra});
test('insurer net of copay plus separate patient invoice counts each amount exactly once',()=>{const data={invoices:[invoice('k'),invoice('p',{payer_type:'private',customer_id:'patient',insurer_id:null,own_share_month:'2026-09-01',payer_name:'Patient',net_total:'10',gross_total:'10'})],receipts:[{amount:10}],invoiceBalances:[{id:'k',open_amount:'50.00'}],patientBalances:[{id:'p',open_amount:'6.50'}]};const r=financeReport(data,{month:'2026-09'});assert.equal(r.totals.gross,10000);assert.equal(r.totals.open,5650);assert.equal(r.groups.length,2);assert.equal(financeReport(data,{month:'2026-09',category:'own_share'}).totals.gross,1000)});
test('cancellation belongs to its issue month; original and replacement do not disappear',()=>{const data={invoices:[invoice('old',{status:'cancelled'}),invoice('st',{document_type:'cancellation',reversal_of_id:'old',issue_date:'2026-10-02',gross_total:'-90',net_total:'-90',refund_status:'due',refund_amount:'40'}),invoice('new',{issue_date:'2026-10-03',gross_total:'95',net_total:'95',reference_invoice_number:'OLD'})]};const september=financeReport(data,{month:'2026-09'}),october=financeReport(data,{month:'2026-10'});assert.equal(september.totals.gross,9000);assert.equal(september.totals.open,0);assert.equal(october.totals.gross,500);assert.equal(october.totals.open,9500);assert.equal(october.totals.cancellations,1);assert.equal(october.totals.refundDue,4000)});
test('legacy cancellations disclose exclusion, paid invoice has zero open, all-month remainder honors filters',()=>{const data={invoices:[invoice('legacy',{status:'cancelled'}),invoice('paid',{status:'paid'}),invoice('older',{issue_date:'2026-08-01'}),invoice('other',{insurer_id:'other',payer_name:'Andere'})]};const r=financeReport(data,{month:'2026-09',payer:'insurer:kasse'});assert.equal(r.legacy.length,1);assert.equal(r.totals.gross,9000);assert.equal(r.totals.open,0);assert.equal(r.totals.allOpen,9000)});
test('complete totals do not depend on 50-row display, cents sum exactly and report preserves snapshots',()=>{const data={invoices:Array.from({length:125},(_,n)=>invoice(String(n),{gross_total:'0.10',net_total:'0.09',vat_total:'0.01'}))};const before=JSON.stringify(data);const r=financeReport(data,{month:'2026-09'});assert.equal(r.rows.length,125);assert.equal(r.totals.gross,1250);assert.equal(r.totals.net+r.totals.vat,r.totals.gross);assert.equal(JSON.stringify(data),before)});
test('invalid amounts and month fail explicitly, empty month returns zero totals',()=>{assert.throws(()=>financeReport({},{month:'2026-13'}));assert.throws(()=>financeReport({invoices:[invoice('bad',{gross_total:null})]},{month:'2026-09'}));assert.equal(financeReport({invoices:[]},{month:'2026-10'}).totals.gross,0)});

test('other payers group by recipient, not the transported patient or a leftover insurer ID',()=>{const invoices=[invoice('one',{payer_type:'other',customer_id:'same-patient',payer_name:'Klinik A'}),invoice('two',{payer_type:'other',customer_id:'same-patient',payer_name:'Klinik B'})];assert.equal(financeReport({invoices},{month:'2026-09'}).groups.length,2)});
