import {test} from 'node:test';import assert from 'node:assert/strict';
import {monthlyCopayRows} from '../src/lib/monthlyCopay.js';
import {renderInvoice} from '../src/lib/printFinanceDocuments.js';
const make=(id,own,extra={})=>({id,trip_id:id,customer_id:'c',payer_type:'insurer',billing_status:'ready',copay_rule_version:1,own_share_amount:own,direction_count:1,...extra});
const cases=[make('hin',10),make('return',10),make('meter-hin',5),make('meter-return',5),make('paid',10,{own_share_paid:true}),make('receipt',10,{receipt_id:'r'}),make('issued',10,{own_share_invoice_id:'i'}),make('exempt',0),make('review',10,{billing_status:'review'}),make('private',10,{payer_type:'private'}),make('foreign',10,{customer_id:'other'})];
const trips=cases.map(c=>({id:c.trip_id,service_date:'2026-09-02',scheduled_time:'09:00',status:'abgeschlossen',direction:c.id.includes('return')?'return':'outbound'}));
test('monthly selection totals normal and 5148 Hin/Rück and excludes paid, receipted, issued, exempt and private cases',()=>{const rows=monthlyCopayRows({cases,trips},'c','2026-09'),allowed=rows.filter(r=>!r.reason);assert.equal(allowed.length,4);assert.equal(allowed.reduce((s,r)=>s+r.cents,0),3000);assert.equal(rows.length,10);assert.equal(monthlyCopayRows({cases,trips},'c','2026-08').length,0);});
test('unfinished and combined directions never enter monthly invoice',()=>{for(const patch of [{direction_count:2},{copay_rule_version:0}])assert(monthlyCopayRows({cases:[make('hin',10,patch)],trips},'c','2026-09')[0].reason);assert(monthlyCopayRows({cases:[make('hin',10)],trips:[{...trips[0],status:'offen'}]},'c','2026-09')[0].reason);});
test('monthly patient PDF preserves every date/direction, total, period and excludes unrelated insurer amounts',()=>{const invoice={id:'month',invoice_number:'RE-MONTH',own_share_month:'2026-09-01',payer_name:'Patient',gross_total:30,net_total:30,vat_total:0};const items=['Hinfahrt','Rückfahrt','Hinfahrt','Rückfahrt'].map((dir,i)=>({invoice_id:'month',description:`2026-09-0${i+1} · ${dir}`,quantity:1,unit:'Fahrt',gross_total:i<2?10:5}));const html=renderInvoice(invoice,[...items,{invoice_id:'kasse',description:'FREMDE KASSENFORDERUNG',gross_total:110}]);assert.match(html,/Monatliche Patientenrechnung/);assert.match(html,/September 2026/);assert.match(html,/30,00/);assert.equal((html.match(/Hinfahrt/g)||[]).length,2);assert.equal((html.match(/Rückfahrt/g)||[]).length,2);assert.doesNotMatch(html,/FREMDE KASSENFORDERUNG/);});
