import {test} from 'node:test';import assert from 'node:assert/strict';
import {reminderBlock,overdueDays,reminderDeadline,ownShareInvoice} from '../src/lib/patientReminders.js';
import {renderPatientReminder} from '../src/lib/printFinanceDocuments.js';
const day='2026-10-09',invoice={id:'own',document_type:'invoice',payer_type:'private',own_share_month:'2026-09-01',status:'open',gross_total:30,due_date:'2026-10-08',payer_name:'Test <script>',payer_address:'Teststraße 1',invoice_number:'RE-1',issue_date:'2026-09-25',issuer_snapshot:{company_name:'Testbetrieb',iban:'DE123'}};
test('reminders distinguish overdue, today, upcoming and missing dates without changing invoice',()=>{assert.equal(reminderBlock(invoice,[],day),'');assert.equal(overdueDays(invoice.due_date,day),1);assert.equal(reminderBlock({...invoice,due_date:day},[],day),'Noch nicht überfällig.');assert.match(reminderBlock({...invoice,due_date:null},[],day),/Fälligkeitsdatum/);assert.equal(reminderDeadline('2026-12-25'), '2027-01-08');assert.equal(overdueDays('2026-03-28','2026-03-30'),2);assert.equal(invoice.status,'open')});
test('only open own-share invoices qualify; drafts, active deadlines and incomplete snapshots block',()=>{for(const patch of [{status:'paid'},{status:'cancelled'},{document_type:'cancellation'},{payer_type:'insurer'},{own_share_month:null},{gross_total:0}])assert.ok(reminderBlock({...invoice,...patch},[],day));assert.equal(ownShareInvoice({...invoice,own_share_month:null,own_share_case_id:'case'}),true);assert.match(reminderBlock(invoice,[{invoice_id:'own',status:'draft'}],day),/Entwurf/);assert.match(reminderBlock(invoice,[{invoice_id:'own',status:'sent',deadline:day}],day),/läuft noch/);assert.equal(reminderBlock(invoice,[{invoice_id:'own',status:'sent',deadline:'2026-10-08'},{invoice_id:'own',status:'void'}],day),'');assert.match(reminderBlock({...invoice,issuer_snapshot:{}},[],day),/IBAN/)});
test('reminder print uses saved amounts, addresses, bank and escapes all free text without new fees',()=>{const html=renderPatientReminder({invoice_snapshot:invoice,reminder_number:1,letter_date:day,deadline:'2026-10-23',message:'Bitte <img src=x onerror=alert(1)> prüfen.'});assert.match(html,/Zahlungserinnerung/);assert.match(html,/30,00/);assert.match(html,/0,00/);assert.match(html,/DE123/);assert.match(html,/Test &lt;script&gt;/);assert.match(html,/Bitte &lt;img/);assert.doesNotMatch(html,/<script>/);assert.match(html,/23.10.2026/)});

test('reminder only requests saved remaining amount and shows original invoice and received total separately',()=>{const html=renderPatientReminder({invoice_snapshot:invoice,open_amount:20,credited_amount:10,reminder_number:2,letter_date:day,deadline:'2026-10-23',message:'Bitte den Rest bezahlen.'});assert.match(html,/<span>Zu zahlen<\/span><b>20,00/);assert.match(html,/<span>Bereits erhalten<\/span><b>10,00/);assert.match(html,/<span>Ursprüngliche Rechnung<\/span><b>30,00/);assert.match(html,/<span>Offener Restbetrag<\/span><b>20,00/)});

test('stages advance only through sent letters, not void attempts or draft counters',async()=>{const {nextReminderStage,reminderStageTitle}=await import('../src/lib/patientReminders.js');const rows=[{invoice_id:'own',stage:1,status:'void',reminder_number:8},{invoice_id:'other',stage:3,status:'sent'}];assert.equal(nextReminderStage('own',rows),1);rows.push({invoice_id:'own',stage:1,status:'sent'});assert.equal(nextReminderStage('own',rows),2);rows.push({invoice_id:'own',stage:2,status:'draft'});assert.equal(nextReminderStage('own',rows),2);rows.push({invoice_id:'own',stage:2,status:'sent'});assert.equal(nextReminderStage('own',rows),3);rows.push({invoice_id:'own',stage:3,status:'sent',deadline:'2026-10-01'});assert.match(reminderBlock(invoice,rows.filter(r=>r.status!=='draft'),day),/manuell klären/);assert.equal(reminderStageTitle(2),'Erste Mahnung');assert.equal(reminderStageTitle(3),'Zweite Mahnung')});
test('stage letter titles follow saved stage and retain original partial-payment snapshot',()=>{for(const [stage,title] of [[2,'Erste Mahnung'],[3,'Zweite Mahnung']]){const html=renderPatientReminder({invoice_snapshot:invoice,stage,open_amount:20,credited_amount:10,reminder_number:8,letter_date:day,deadline:'2026-10-23',message:'Bitte den Rest bezahlen.'});assert.match(html,new RegExp(`<h1>${title}</h1>`));assert.match(html,/<span>Zu zahlen<\/span><b>20,00/)}});
