import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {transform} from 'esbuild';
import {readPages,readByIds} from '../src/data/readPages.js';import {utilizationRange} from '../src/lib/utilization.js';
async function harness({role='office',fail=false}={}){
 const calls=[];const rows={business_units:[{id:'unit',code:'fahrdienst',active:true}],memberships:[{business_unit_id:'unit',user_id:'staff',active:true,role}],trips:Array.from({length:601},(_,n)=>({id:'t'+n,business_unit_id:'unit',service_date:'2026-09-01'})),driver_shifts:[{id:'s',business_unit_id:'unit',started_at:'2026-09-01T06:00:00Z'}],driver_business_units:[{driver_id:'d',business_unit_id:'unit'}],vehicle_business_units:[{vehicle_id:'v',business_unit_id:'unit'}],driver_shift_breaks:[{id:'b',business_unit_id:'unit',shift_id:'s'}],drivers:[{id:'d',full_name:'Test'}],vehicles:[{id:'v',registration:'TEST'}]};
 const db={auth:{getUser:async()=>({data:{user:{id:'staff'}}})},from(table){let filters=[],fields,range,single=false;const q={select(v){fields=v;return q},eq(k,v){filters.push(r=>r[k]===v);return q},gte(k,v){filters.push(r=>r[k]>=v);return q},lt(k,v){filters.push(r=>r[k]<v);return q},in(k,ids){filters.push(r=>ids.includes(r[k]));return q},order(){return q},single(){single=true;return q},range(a,b){range=[a,b];return q},then(resolve,reject){calls.push({table,fields,range});const all=(rows[table]||[]).filter(r=>filters.every(f=>f(r)));let data=range?all.slice(range[0],range[1]+1):all;data=data.map(r=>Object.fromEntries(fields.split(',').map(k=>[k,r[k]])));return Promise.resolve({data:single?data[0]:data,count:all.length,error:fail&&table==='driver_shift_breaks'?Error('Read failed'):null}).then(resolve,reject)}};return q}};
 const source=fs.readFileSync('src/data/utilization.js','utf8').replace(/^import .*;\n/gm,'');const {code}=await transform(source,{loader:'js',format:'cjs'});const module={exports:{}};new Function('module','exports','APP_CONFIG','requireSupabase','readPages','readByIds','utilizationRange',code)(module,module.exports,{businessUnitCode:'fahrdienst'},()=>db,readPages,readByIds,utilizationRange);return {...module.exports,calls};
}
test('complete month reads paginate trips, scope child pauses and resource labels without customer data',async()=>{const h=await harness(),d=await h.loadUtilization('2026-09');assert.equal(d.trips.length,601);assert.equal(d.breaks.length,1);assert.equal(d.drivers.length,1);assert.equal(d.vehicles.length,1);assert.deepEqual(h.calls.filter(c=>c.table==='trips').map(c=>c.range),[[0,499],[500,999]]);for(const c of h.calls)assert.doesNotMatch(c.fields,/customer|from_address|to_address|phone|email|notes|\*/)});
test('driver and unknown roles cannot start data reads; any source failure rejects the whole report',async()=>{for(const role of ['driver','unknown']){const h=await harness({role});await assert.rejects(()=>h.loadUtilization('2026-09'),/Nur Büro/);assert.ok(!h.calls.some(c=>c.table==='trips'||c.table==='driver_shifts'))}const h=await harness({fail:true});await assert.rejects(()=>h.loadUtilization('2026-09'),/Read failed/);const invalid=await harness();await assert.rejects(()=>invalid.loadUtilization('2026-13'),/Gültigen/);assert.equal(invalid.calls.length,0)});
