import ExpenseDocuments from './ExpenseDocuments.jsx';
import {expenseDocumentsApi} from '../data/accountingDocuments.js';
import {buildAccountingPackage,accountingExportSnapshot} from '../lib/accountingExport.js';
import React,{useEffect,useMemo,useRef,useState} from 'react';
import {accountingApi} from '../data/accounting.js';
import {accountingReport,accountingToday,accountingCsv,expenseCategories,paymentMethods,validateAccountingInput} from '../lib/accounting.js';
import {reportMoney} from '../lib/financeReports.js';
export default function AccountingManagement({api=accountingApi,documentsApi=expenseDocumentsApi}){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[month,setMonth]=useState(()=>accountingToday().slice(0,7)),[flow,setFlow]=useState(''),[method,setMethod]=useState(''),[page,setPage]=useState(0),[dialog,setDialog]=useState(null),[formError,setFormError]=useState('');const [documentEntry,setDocumentEntry]=useState(null),[exportProgress,setExportProgress]=useState('');const seq=useRef(0),request=useRef(null);
 async function refresh(){const n=++seq.current;setLoading(true);setError('');try{const d=await api.load();if(n===seq.current)setData(d)}catch(e){if(n===seq.current){setData(null);setError(e.message)}}finally{if(n===seq.current)setLoading(false)}}
 useEffect(()=>{refresh();return()=>{seq.current++}},[api]);
 const result=useMemo(()=>{if(!data||loading)return {};try{return {report:accountingReport(data,{month,flow,method})}}catch(e){return {reportError:e.message}}},[data,loading,month,flow,method]),r=result.report,maxPage=Math.max(0,Math.ceil((r?.rows.length||0)/50)-1),currentPage=Math.min(page,maxPage);
 function open(d){request.current=null;setFormError('');setDialog(d)}
 async function save(e){e.preventDefault();setFormError('');const f=Object.fromEntries(new FormData(e.currentTarget));if(f.confirmed!=='on'){setFormError('Tatsächliche Zahlung und Angaben bestätigen.');return}
  const input={kind:dialog.kind,invoiceId:dialog.invoice?.id,version:dialog.invoice?.updated_at,...f};delete input.confirmed;const problem=validateAccountingInput(input);if(problem){setFormError(problem);return}
  if(input.kind==='expense')input.amount=Number(String(input.amount).replace(',','.'));
  const signature=JSON.stringify(input);if(request.current?.signature!==signature)request.current={signature,id:crypto.randomUUID()};setBusy(true);
  try{const response=await api.record({...input,requestId:request.current.id});if(!response.ok)throw Error(response.message);setDialog(null);setNotice('Erfassung gespeichert.');await refresh()}catch(e){setFormError(e.message)}finally{setBusy(false)}
 }
 async function cancel(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));setFormError('');if(f.confirmed!=='on'||String(f.reason||'').trim().length<5){setFormError('Korrektur bestätigen und einen Grund mit mindestens 5 Zeichen eingeben.');return}setBusy(true);try{const response=await api.cancel(dialog.id,f.reason);if(!response.ok)throw Error(response.message);setDialog(null);setNotice('Fehlerhafte Erfassung aufgehoben. Der Verlauf bleibt erhalten.');await refresh()}catch(e){setFormError(e.message)}finally{setBusy(false)}}
 async function exportPackage(){setBusy(true);setError('');setExportProgress('Zahlungsdaten werden geprüft …');try{const latest=await api.load(),snapshot=accountingExportSnapshot(data);if(accountingExportSnapshot(latest)!==snapshot)throw Error('Zahlungen oder Belege haben sich geändert. Aktualisieren und Export erneut starten.');const report=accountingReport(latest,{month,flow,method});const pack=await buildAccountingPackage({data:latest,report,month,flow,method,download:documentsApi.download,onProgress:setExportProgress,verifySnapshot:async()=>{if(accountingExportSnapshot(await api.load())!==snapshot)throw Error('Zahlungen oder Belege wurden während des Exports geändert. Export abgebrochen.')}});const url=URL.createObjectURL(new Blob([pack.bytes],{type:'application/zip'})),a=document.createElement('a');a.href=url;a.download=`Steuerberaterpaket-${month}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice(`Steuerberaterpaket erstellt: ${pack.fileCount} Originaldatei(en), ${pack.missingCount} Ausgabe(n) ohne aktiven Beleg im Klärungsverzeichnis.`)}catch(e){setError(e.message)}finally{setBusy(false);setExportProgress('')}}
 function download(){const url=URL.createObjectURL(new Blob([accountingCsv(r.rows)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`Zahlungsuebersicht-${month}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className="batch-panel accounting-panel"><div className="batch-heading"><div><p className="eyebrow">BUCHHALTUNG</p><h2>Einnahmen & Ausgaben</h2><p>Tatsächliche Zahlungen nach Zahlungsdatum. Kassen- und Eigenanteilszahlungen werden aus dem Zahlungsabgleich übernommen; Quittungen zählen einmal.</p></div><div className="shift-buttons"><button className="secondary-button" disabled={loading||busy} onClick={refresh}>Aktualisieren</button><button className="primary-button" disabled={loading||busy||!r} onClick={()=>open({kind:'expense'})}>Ausgabe erfassen</button></div></div>
 <div className="form-grid"><label><span>Zahlungsmonat</span><input aria-label="Zahlungsmonat" type="month" disabled={busy} value={month} onChange={e=>{if(e.target.value){setMonth(e.target.value);setPage(0)}}}/></label><label><span>Zahlungsrichtung</span><select aria-label="Zahlungsrichtung" disabled={busy} value={flow} onChange={e=>{setFlow(e.target.value);setPage(0)}}><option value="">Alle Zahlungen</option><option value="income">Einnahmen</option><option value="expense">Ausgaben</option><option value="refund">Rückzahlungen</option></select></label><label><span>Zahlungsart filtern</span><select aria-label="Zahlungsart filtern" disabled={busy} value={method} onChange={e=>{setMethod(e.target.value);setPage(0)}}><option value="">Alle Zahlungsarten</option>{Object.entries(paymentMethods).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label></div>
 {notice&&<p role="status">{notice}</p>}{exportProgress&&<p role="status">{exportProgress}</p>}{(error||result.reportError)&&<p role="alert" className="users-error">{error||result.reportError}</p>}{loading&&<p role="status">Zahlungsübersicht wird geladen …</p>}
 {r&&<><div className="batch-summary"><span>Einnahmen <b>{reportMoney(r.totals.income)}</b></span><span>Ausgaben <b>{reportMoney(r.totals.expense)}</b></span><span>Rückzahlungen <b>{reportMoney(r.totals.refund)}</b></span><span>Zahlungsüberschuss <b>{reportMoney(r.totals.balance)}</b></span></div><p>Die Summen folgen den gewählten Filtern und enthalten nur Zahlungen mit erfasstem Zahlungsdatum. Kassenbeträge enthalten auch noch nicht zugeordnete Eingänge. Diese Übersicht ist kein Bankkontostand und berechnet keinen Vorsteuerabzug.</p><div className="shift-buttons"><button className="secondary-button" disabled={busy||!r.rows.length} onClick={download}>CSV herunterladen</button><button className="primary-button" disabled={busy||!r.rows.length} onClick={exportPackage}>Steuerberaterpaket herunterladen</button></div><p>ZIP für den gewählten Zahlungsmonat und die aktiven Filter: CSV-Übersichten, Belegverzeichnis und aktive Ausgabenoriginale. Fehlende Belege und offene Zuordnungen stehen im Klärungsverzeichnis. Allgemeines Übergabepaket; Kontierung erfolgt beim Steuerberater.</p>
 {!!r.conflicts.length&&<div role="alert" className="users-error"><h3>Zuordnungen prüfen</h3>{r.conflicts.map(c=><p key={c.id}>{c.message}</p>)}</div>}
 <h3>Zahlungen im Monat</h3>{!r.rows.length&&<p>Keine erfassten Zahlungen für diese Auswahl.</p>}<div className="batch-list">{r.rows.slice(currentPage*50,currentPage*50+50).map(row=><article className="batch-card" key={row.id}><div><h4>{row.reference} · {row.source}</h4><p>{row.date.split('-').reverse().join('.')} · {paymentMethods[row.method]} · {row.recipient}</p><p>{row.description}</p></div><div><strong>{row.flow==='income'?'+':'−'}{reportMoney(row.cents)}</strong>{row.flow==='expense'&&<button className="secondary-button" disabled={busy} onClick={()=>setDocumentEntry(row.entryId)}>Ausgabenbelege ({(data.accounting_documents||[]).filter(d=>d.entry_id===row.entryId&&d.status==='ready').length})</button>}{row.entryId&&<button className="text-button" disabled={busy} onClick={()=>open({kind:'cancel',id:row.entryId})}>Fehlerhafte Erfassung aufheben</button>}</div></article>)}</div><div className="shift-buttons"><button className="secondary-button" disabled={!currentPage} onClick={()=>setPage(currentPage-1)}>Vorherige Zahlungsseite</button><span>{r.rows.length?`${currentPage*50+1}–${Math.min((currentPage+1)*50,r.rows.length)} von ${r.rows.length}`:'0 Zahlungen'}</span><button className="secondary-button" disabled={currentPage>=maxPage} onClick={()=>setPage(currentPage+1)}>Nächste Zahlungsseite</button></div>
 {!!r.pending.length&&<><h3>Zahlungsdatum noch offen · alle Monate</h3><p>Diese bereits als bezahlt bzw. zurückgezahlt bestätigten Belege fehlen in den Monatssummen. Ergänzen Sie das tatsächliche Zahlungsdatum anhand Ihres Zahlungsnachweises.</p><div className="batch-list">{r.pending.slice(0,50).map(p=><article className="batch-card" key={p.kind+p.invoice.id}><div><h4>{p.invoice.invoice_number} · {p.invoice.payer_name}</h4><p>{p.kind==='refund_date'?'Rückzahlung':'Bezahlte Altrechnung'} · {reportMoney(p.amount)}</p></div><button className="secondary-button" disabled={busy} onClick={()=>open(p)}>Zahlungsdatum ergänzen</button></article>)}</div>{r.pending.length>50&&<p>50 von {r.pending.length} Belegen angezeigt. Nach Ergänzung erscheinen die nächsten.</p>}</>}
 {!!r.audit.length&&<><h3>Aufgehobene Erfassungen im Monat</h3><div className="batch-list">{r.audit.slice(0,50).map(e=><article className="batch-card" key={e.id}><div><h4>{e.reference} · {reportMoney(Math.round(e.amount*100))}</h4><p>{e.recipient} · {e.payment_date} · Korrektur: {e.cancel_reason}</p>{e.kind==='expense'&&<button className="secondary-button" disabled={busy} onClick={()=>setDocumentEntry(e.id)}>Ausgabenbelege ansehen</button>}<p>Aufgehoben {new Date(e.cancelled_at).toLocaleString('de-DE',{timeZone:'Europe/Berlin'})}</p></div></article>)}</div>{r.audit.length>50&&<p>50 von {r.audit.length} aufgehobenen Erfassungen angezeigt.</p>}</>}
 </>}
 {documentEntry&&data&&<ExpenseDocuments entry={data.accounting_entries.find(e=>e.id===documentEntry)} documents={(data.accounting_documents||[]).filter(d=>d.entry_id===documentEntry)} api={documentsApi} onClose={()=>setDocumentEntry(null)} onChanged={refresh}/> }
 {dialog&&<div className="modal-layer"><button className="modal-backdrop" disabled={busy} onClick={()=>setDialog(null)}/><section className="modal-card billing-check-modal" role="dialog" aria-modal="true" aria-label={dialog.kind==='cancel'?'Erfassung korrigieren':dialog.kind==='expense'?'Ausgabe erfassen':'Zahlungsdatum ergänzen'}><div className="batch-heading"><h2>{dialog.kind==='cancel'?'Erfassung korrigieren':dialog.kind==='expense'?'Ausgabe erfassen':'Zahlungsdatum ergänzen'}</h2><button className="secondary-button" disabled={busy} onClick={()=>setDialog(null)}>Schließen</button></div>{formError&&<p role="alert" className="users-error">{formError}</p>}
 {dialog.kind==='cancel'?<form noValidate onSubmit={cancel}><p>Nur eine fehlerhafte Erfassung aufheben. Dies führt keine Bankzahlung aus und ändert keinen Rechnungs-Zahlungsstatus.</p><label><span>Korrekturgrund</span><textarea name="reason" aria-label="Korrekturgrund" maxLength={1000}/></label><label className="refund-confirmation"><input name="confirmed" type="checkbox"/>Diese Erfassung ist falsch und soll aufgehoben werden.</label><button className="primary-button" disabled={busy}>Korrektur speichern</button></form>:<form noValidate onSubmit={save}>{dialog.invoice&&<p>{dialog.invoice.invoice_number} · {dialog.invoice.payer_name} · {reportMoney(dialog.amount)}</p>}<div className="form-grid">{dialog.kind==='expense'&&<><label><span>Betrag €</span><input name="amount" aria-label="Ausgabenbetrag €" inputMode="decimal" maxLength={20}/></label><label><span>Kategorie</span><select name="category" aria-label="Ausgabenkategorie">{Object.entries(expenseCategories).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label className="wide"><span>Zahlungsempfänger</span><input name="recipient" aria-label="Zahlungsempfänger" maxLength={180}/></label></>}<label><span>Zahlungsdatum</span><input name="date" aria-label="Tatsächliches Zahlungsdatum" type="date" min={dialog.invoice?.issue_date||'2000-01-01'} max={accountingToday()}/></label><label><span>Zahlungsart</span><select name="method" aria-label="Zahlungsart">{Object.entries(paymentMethods).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label className="wide"><span>Beleg- / Zahlungsreferenz</span><input name="reference" aria-label="Beleg- / Zahlungsreferenz" maxLength={180}/></label><label className="wide"><span>Beschreibung</span><textarea name="description" aria-label="Beschreibung der Zahlung" maxLength={500}/></label></div><label className="refund-confirmation"><input name="confirmed" type="checkbox"/>Die Zahlung ist tatsächlich erfolgt. Datum, Betrag und Zahlungsnachweis sind geprüft.</label><button className="primary-button" disabled={busy}>{dialog.kind==='expense'?'Ausgabe speichern':'Zahlungsdatum speichern'}</button></form>}
 </section></div>}
 </section>;
}
