import React,{useEffect,useState} from 'react';
import {loadBilling} from '../data/billing.js';
import {inspectBillingDocuments,saveBillingDocumentCheck} from '../data/submissions.js';
import DocumentManagement from './DocumentManagement.jsx';
import OriginalDocumentPreview from './OriginalDocumentPreview.jsx';
const kinds={prescription:'Verordnung',approval:'Genehmigung',transport_proof:'Transportnachweis'};
async function defaultLoad(caseIds){const ids=caseIds||(await loadBilling()).cases.filter(c=>c.payer_type==='insurer').map(c=>c.id);return inspectBillingDocuments(ids)}
export default function BillingDocumentReview({caseIds,clients=[],trips=[],load=defaultLoad,save=saveBillingDocumentCheck,loadPreview}){
 const [rows,setRows]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[target,setTarget]=useState(null),[selection,setSelection]=useState({}),[preview,setPreview]=useState(null),[documents,setDocuments]=useState(null),[search,setSearch]=useState(''),[onlyMissing,setOnlyMissing]=useState(true);
 const key=caseIds?.join(',')||'';
 async function refresh(){setBusy(true);setError('');try{setRows(await load(caseIds))}catch(e){setRows([]);setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{refresh()},[load,key]);
 function edit(row){setError('');setTarget(row);setSelection({...row.selection,approvalRequired:row.selection?.approvalRequired===true?'yes':row.selection?.approvalRequired===false?'no':'',prescription:row.selection?.prescription||'',approval:row.selection?.approval||'',transport_proof:row.selection?.transport_proof||'',note:row.selection?.note||''})}
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{if(!selection.approvalRequired)throw Error('Genehmigungspflicht prüfen.');await save(target,{...selection,approvalRequired:selection.approvalRequired==='yes',approval:selection.approvalRequired==='yes'?selection.approval:''});setTarget(null);setNotice('Belegprüfung gespeichert. Vor Weberfassung und Postversand wird sie erneut geprüft.');await refresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const shown=rows.filter(r=>(!onlyMissing||!r.complete)&&(!search||`${r.patient} ${r.date} ${r.direction}`.toLowerCase().includes(search.toLowerCase())));
 if(documents)return <section className="batch-panel"><button className="secondary-button" onClick={()=>{setDocuments(null);refresh()}}>Zurück zur Belegprüfung</button><p>{documents.patient} · {documents.date} · {documents.direction}</p><DocumentManagement customerId={documents.customerId} clients={clients} trips={[...trips.filter(t=>t.id!==documents.tripId),{id:documents.tripId,customerId:documents.customerId,date:documents.date,time:'',type:documents.tripType+' · '+documents.direction}]}/></section>;
 return <section className="batch-panel billing-document-panel"><div className="batch-heading"><div><p className="eyebrow">ABRECHNUNGSBELEGE</p><h2>Belegprüfung</h2></div><button className="secondary-button" disabled={busy} onClick={refresh}>Aktualisieren</button></div><p>Prüfe die Originalbelege für jede Fahrtrichtung. Ein Upload allein bestätigt weder den Inhalt noch die Unterschriften. Verordnung und erforderliche Genehmigung brauchen eine am Fahrtag gültige Zuordnung in der Kundenakte; der Transportnachweis gehört zur konkreten Fahrt.</p><div className="form-grid"><label><span>Patient oder Leistungsdatum suchen</span><input value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="checkbox-label"><input type="checkbox" checked={onlyMissing} onChange={e=>setOnlyMissing(e.target.checked)}/>Nur offene Belegprüfungen</label></div><p>{rows.filter(r=>r.complete).length} von {rows.length} Fällen geprüft und vollständig</p>{notice&&<p role="status">{notice}</p>}{error&&!target&&<p className="users-error" role="alert">{error}</p>}{busy&&<p role="status">Belege werden geprüft …</p>}<div className="batch-list">{shown.map(row=><article className="batch-card" key={row.caseId} data-document-case={row.caseId}><div><h3>{row.patient}</h3><p>{row.date} · {row.direction} · {row.tripType}</p><strong>{row.complete?'Geprüft und vollständig':'Belege prüfen'}</strong>{row.issues.map((issue,i)=><p className="batch-blocked" key={i}>{issue}</p>)}{Object.entries(kinds).map(([kind,label])=><p key={kind}>{label}: {kind==='approval'&&row.selection?.approvalRequired===false?'Nicht erforderlich · '+row.selection.note:row.candidates.find(d=>d.id===row.selection?.[kind])?.title||'Noch nicht zugeordnet / nicht aktiv'}</p>)}{row.reviewedAt&&<small>Zuletzt geprüft {new Date(row.reviewedAt).toLocaleString('de-DE')}</small>}</div><div className="batch-toolbar"><button className="primary-button" disabled={busy} onClick={()=>edit(row)}>Belege prüfen</button>{clients.some(c=>c.id===row.customerId)&&<button className="secondary-button" onClick={()=>setDocuments(row)}>Belege hochladen / zuordnen</button>}</div></article>)}</div>{!busy&&!shown.length&&<p>{rows.length?'Keine offenen Belegprüfungen für diese Auswahl.':'Noch keine Kassenfälle vorhanden.'}</p>}
 {target&&<div className="modal-layer"><button className="modal-backdrop" disabled={busy} onClick={()=>setTarget(null)}/><form role="dialog" aria-modal="true" aria-label="Belege für Fahrt prüfen" className="modal-card compact-modal billing-check-modal" onSubmit={submit}><h2>Belege für Fahrt prüfen</h2><p>{target.patient} · {target.date} · {target.direction}</p><label><span>Genehmigung erforderlich?</span><select aria-label="Genehmigung erforderlich?" required value={selection.approvalRequired} onChange={e=>setSelection({...selection,approvalRequired:e.target.value})} disabled={busy}><option value="">Ausdrücklich prüfen und wählen</option><option value="yes">Ja, erforderlich</option><option value="no">Nein, nicht erforderlich</option></select></label>{Object.entries(kinds).filter(([kind])=>kind!=='approval'||selection.approvalRequired==='yes').map(([kind,label])=><div key={kind}><label><span>{label}</span><select aria-label={label} required value={selection[kind]} disabled={busy} onChange={e=>setSelection({...selection,[kind]:e.target.value})}><option value="">Aktiven Beleg auswählen</option>{target.candidates.filter(d=>d.kind===kind&&(kind!=='transport_proof'||d.trip_id===target.tripId)).map(d=><option value={d.id} key={d.id}>{d.title}{d.authorization?' · '+d.authorization.status+' · '+(d.authorization.valid_from||'offen')+' bis '+(d.authorization.valid_until||'offen'):kind==='transport_proof'?'':' · Zuordnung zur Kundenakte fehlt'}</option>)}</select></label>{selection[kind]&&target.candidates.some(d=>d.id===selection[kind])&&<button className="text-button" type="button" onClick={()=>setPreview(target.candidates.find(d=>d.id===selection[kind]))}>{label} ansehen</button>}</div>)}<label><span>{selection.approvalRequired==='no'?'Begründung: Genehmigung nicht erforderlich':'Prüfvermerk (optional)'}</span><textarea aria-label={selection.approvalRequired==='no'?'Begründung: Genehmigung nicht erforderlich':'Prüfvermerk (optional)'} required={selection.approvalRequired==='no'} minLength={selection.approvalRequired==='no'?5:undefined} maxLength={1000} value={selection.note} onChange={e=>setSelection({...selection,note:e.target.value})} disabled={busy}/></label><label className="refund-confirmation"><input type="checkbox" required disabled={busy}/>Ich habe Inhalt, Patient, Leistungsdatum, Fahrtrichtung, erforderliche Unterschriften und die Genehmigungspflicht anhand der Originalbelege geprüft.</label>{error&&<p className="users-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="secondary-button" disabled={busy} onClick={()=>setTarget(null)}>Abbrechen</button><button className="primary-button" disabled={busy}>Belegprüfung speichern</button></div></form></div>}
 {preview&&<OriginalDocumentPreview document={preview} loadPreview={loadPreview} onClose={()=>setPreview(null)}/>}
 </section>
}
