import BillingDocumentReview from './BillingDocumentReview.jsx';
import React,{useEffect,useMemo,useState} from 'react';
import {BadgeEuro,CheckCircle2,FileWarning,ReceiptText,RefreshCw,Save,X} from 'lucide-react';
import {createCaseInvoice,createOwnShareReceipt,createOwnShareInvoice,recalculateCase} from '../data/billing.js';
import {tariffUnits} from '../../supabase/functions/_shared/tariffs.js';
import DocumentPreview from './DocumentPreview.jsx';
import BillingBatch from './BillingBatch.jsx';
import SubmissionRegister from './SubmissionRegister.jsx';
import MonthlyCopay from './MonthlyCopay.jsx';
import {renderInvoice,renderReceipt} from '../lib/printFinanceDocuments.js';
const actions={recalculate:recalculateCase,invoice:createCaseInvoice,receipt:createOwnShareReceipt,ownInvoice:createOwnShareInvoice};
const euro=v=>Number(v||0).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
const status={review:'Prüfen',ready:'Bereit',invoiced:'Abgerechnet',completed:'Erledigt',blocked:'Gesperrt'};
export default function BillingManagement({data,financeData,onFinanceRefresh,clients=[],trips=[],initialView='cases',api=actions}){
 const [ownInvoiceTarget,setOwnInvoiceTarget]=useState(null);
 const [view,setView]=useState(initialView);
 useEffect(()=>{setView(initialView)},[initialView]);
 const[payerType,setPayerType]=useState('insurer'),[pendingPreview,setPendingPreview]=useState(null),[preview,setPreview]=useState(null),[receiptTarget,setReceiptTarget]=useState(null),[paymentMethod,setPaymentMethod]=useState('cash');
 useEffect(()=>{if(!pendingPreview||!financeData)return;const docs=pendingPreview.kind==='receipt'?financeData.receipts:financeData.invoices;const doc=docs?.find(x=>x.id===pendingPreview.id);if(doc){setPreview({kind:pendingPreview.kind,doc});setPendingPreview(null)}},[pendingPreview,financeData]);
 const[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const tripById=useMemo(()=>Object.fromEntries(data.trips.map(x=>[x.id,x])),[data.trips]),customerById=useMemo(()=>Object.fromEntries(data.customers.map(x=>[x.id,x])),[data.customers]),insurerById=useMemo(()=>Object.fromEntries(data.insurers.map(x=>[x.id,x])),[data.insurers]);
 const totals=useMemo(()=>({review:data.cases.filter(x=>x.billing_status==='review').length,ready:data.cases.filter(x=>x.billing_status==='ready').length,gross:data.cases.reduce((s,x)=>s+Number(x.gross_amount||0),0)}),[data.cases]);
 async function recalc(e){e.preventDefault();setBusy(true);setError('');try{const fd=Object.fromEntries(new FormData(e.currentTarget).entries());const updated=await api.recalculate(selected,fd,data);setSelected(updated);await data.refresh();}catch(x){setError(x.message||'Berechnung fehlgeschlagen.')}finally{setBusy(false)}}
 async function invoice(item){setBusy(true);setError('');const r=await api.invoice(item,data);if(!r.ok)setError(r.message);else{await Promise.all([data.refresh(),onFinanceRefresh?.()]);setSelected(null);setPendingPreview({kind:'invoice',id:r.data?.id});}setBusy(false)}
 async function receipt(item){setBusy(true);setError('');const r=await api.receipt(item,data,paymentMethod);if(!r.ok)setError(r.message);else{await Promise.all([data.refresh(),onFinanceRefresh?.()]);setReceiptTarget(null);setPendingPreview({kind:'receipt',id:r.data?.id});}setBusy(false)}
 async function ownInvoice(e){e.preventDefault();setBusy(true);setError('');try{const dueDate=new FormData(e.currentTarget).get('dueDate');const r=await api.ownInvoice(ownInvoiceTarget,data,dueDate);if(!r.ok)throw Error(r.message);await Promise.all([data.refresh(),onFinanceRefresh?.()]);setOwnInvoiceTarget(null);setPendingPreview({kind:'invoice',id:r.data?.id});}catch(e){setError(e.message||'Eigenanteilsrechnung konnte nicht erstellt werden.')}finally{setBusy(false)}}
 return <section className="billing-page">
  <div className="batch-tabs"><button className={view==='cases'?'primary-button':'secondary-button'} aria-pressed={view==='cases'} onClick={()=>setView('cases')}>Einzelabrechnungen</button><button className={view==='batch'?'primary-button':'secondary-button'} aria-pressed={view==='batch'} onClick={()=>setView('batch')}>Sammelabrechnung</button><button className={view==='monthly'?'primary-button':'secondary-button'} aria-pressed={view==='monthly'} onClick={()=>setView('monthly')}>Monatliche Eigenanteile</button><button className={view==='zad'?'primary-button':'secondary-button'} aria-pressed={view==='zad'} onClick={()=>setView('zad')}>ZAD-Übersicht</button><button className={view==='documents'?'primary-button':'secondary-button'} aria-pressed={view==='documents'} onClick={()=>setView('documents')}>Belegprüfung</button></div>
  {view==='documents'?<BillingDocumentReview clients={clients} trips={trips}/>:view==='zad'?<SubmissionRegister clients={clients} trips={trips} onFinanceRefresh={()=>Promise.all([data.refresh(),onFinanceRefresh?.()])}/>:view==='monthly'?<MonthlyCopay onCreated={()=>Promise.all([data.refresh(),onFinanceRefresh?.()])}/>:view==='batch'?<BillingBatch/>:<>
  <div className="billing-kpis"><div><FileWarning/><span><strong>{totals.review}</strong>zu prüfen</span></div><div><CheckCircle2/><span><strong>{totals.ready}</strong>bereit</span></div><div><BadgeEuro/><span><strong>{euro(totals.gross)}</strong>Fahrtenwert</span></div></div>
  {error&&<div className="users-error">{error}</div>}{data.error&&<div className="users-error">{data.error}</div>}
  <div className="billing-table">
   <div className="billing-row billing-head"><span>Fahrt</span><span>Patient / Kasse</span><span>Position</span><span>km</span><span>Gesamt</span><span>Eigenanteil</span><span>Kasse / Privat</span><span>Status</span><span>Aktion</span></div>
   {data.loading?<div className="users-loading">Abrechnungsfälle werden geladen …</div>:data.cases.map(item=>{const t=tripById[item.trip_id]||{},c=customerById[item.customer_id]||{},i=insurerById[item.insurer_id]||{},issued=financeData?.invoices?.find(x=>x.id===item.invoice_id);return <div className="billing-row" data-case-id={item.id} key={item.id}>
    <div data-label="Fahrt">{item.last_cancelled_invoice_id&&<small className="correction-case-label">Korrektur nach Storno</small>}<b>{t.service_date||'—'}</b><small>{t.trip_type||'Krankenfahrt'} · {t.direction==='return'?'Rückfahrt':'Hinfahrt'}</small></div><div data-label="Patient / Kasse"><b>{[c.first_name,c.last_name].filter(Boolean).join(' ')||'—'}</b><small>{item.payer_type==='private'?'Privatfahrt':i.short_name||i.name||'Kasse offen'}</small></div><b data-label="Position">{item.tariff_breakdown?.length?item.tariff_breakdown.map(l=>l.position_code).join(' · '):item.billing_position||item.position_code||'—'}</b><span data-label="km">{item.billable_km??'—'}</span><b data-label="Gesamt">{euro(item.gross_amount)}</b><span data-label="Eigenanteil">{euro(item.own_share_amount)}<small>{item.own_share_paid?(item.receipt_id?'Bezahlt · quittiert':'Rechnung bezahlt'):item.own_share_invoice_id?'Patientenrechnung offen':item.own_share_required?'Noch offen':item.copay_note||'Neu berechnen'}</small></span><b data-label="Kasse / Privat">{euro(item.payer_type==='private'?item.gross_amount:item.insurer_amount)}{issued&&<small>{issued.status==='paid'?'Rechnung bezahlt':'Rechnung offen'}</small>}</b><span data-label="Status" className={'billing-status '+item.billing_status}>{status[item.billing_status]||item.billing_status}</span>
    <div className="billing-actions"><button className="text-button" onClick={()=>{setError('');setPayerType(item.payer_type||'insurer');setSelected(item)}}>Prüfen</button>{item.billing_status==='ready'&&!item.invoice_id&&<button className="text-button" disabled={busy} onClick={()=>invoice(item)}>Rechnung</button>}{item.own_share_invoice_id&&<button className="text-button" onClick={()=>{const doc=financeData?.invoices?.find(i=>i.id===item.own_share_invoice_id);if(doc)setPreview({kind:'invoice',doc});else setError('Rechnungsdaten zuerst neu laden.')}}>Eigenanteilsrechnung</button>}{item.payer_type==='insurer'&&item.copay_rule_version===1&&['ready','invoiced'].includes(item.billing_status)&&item.own_share_required&&!item.own_share_paid&&!item.receipt_id&&!item.own_share_invoice_id&&<button className="text-button" disabled={busy} onClick={()=>{setError('');setOwnInvoiceTarget(item)}}>Eigenanteil berechnen</button>}{item.payer_type==='insurer'&&item.copay_rule_version===1&&['ready','invoiced'].includes(item.billing_status)&&item.own_share_required&&!item.own_share_paid&&!item.own_share_invoice_id&&<button className="text-button" disabled={busy} onClick={()=>{setPaymentMethod('cash');setReceiptTarget(item)}}>Zuzahlung</button>}</div>
   </div>})}
   {!data.loading&&!data.cases.length&&<div className="module-empty"><ReceiptText/><h3>Noch keine Abrechnungsfälle</h3><p>Sobald eine Krankenfahrt abgeschlossen wird, erscheint sie hier automatisch zur Prüfung.</p></div>}
  </div>
  {selected&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setSelected(null)}/><form role="dialog" aria-modal="true" aria-label="Abrechnung prüfen" className="modal-card compact-modal billing-check-modal" onSubmit={recalc}><div className="modal-head"><div><p className="eyebrow">ABRECHNUNG PRÜFEN</p><h2>{customerById[selected.customer_id]?.first_name} {customerById[selected.customer_id]?.last_name}</h2></div><button type="button" className="icon-button" aria-label="Abrechnung schließen" disabled={busy} onClick={()=>setSelected(null)}><X/></button></div>
   <p className="billing-review-note">{payerType==='private'?'Privatfahrt: Preis gilt für diese Fahrtrichtung.':tripById[selected.trip_id]?.customer_mobility==='wheelchair'?'Rollstuhlfahrt – eigener Rollstuhlvertrag erforderlich.':'Sitzende Krankenfahrt.'} Tarifpositionen werden anhand des Fahrtags und dieser Angaben berechnet.</p>
   <div className="form-grid"><label><span>Kostenträger</span><select name="payerType" value={payerType} onChange={e=>setPayerType(e.target.value)} disabled={Boolean(selected.invoice_id||selected.receipt_id)}><option value="insurer">Krankenkasse</option><option value="private">Privatfahrt</option></select></label>{payerType==='private'?<><label><span>Privatpreis € je Fahrtrichtung</span><input name="privateAmount" type="number" min="0.01" step="0.01" required defaultValue={selected.private_amount??tripById[selected.trip_id]?.private_price??''}/></label><label><span>MwSt. Privatfahrt</span><select name="privateVatRate" defaultValue={selected.private_vat_rate??tripById[selected.trip_id]?.private_vat_rate??0}><option value="0">0 %</option><option value="7">7 %</option><option value="19">19 %</option></select></label></>:<><label><span>Besetzte Abrechnungs-km</span><input name="billableKm" type="number" min="0" step="0.1" defaultValue={selected.billable_km??''}/></label><label><span>Wartezeit Minuten</span><input name="waitingMinutes" type="number" min="0" defaultValue={selected.waiting_minutes||0}/></label>
   <label><span>Taxi / Mietwagen</span><select name="vehicleClass" defaultValue={selected.billing_vehicle_class||'unconfirmed'}><option value="unconfirmed">Bitte auswählen</option><option value="taxi">Taxi</option><option value="mietwagen">Mietwagen</option></select></label>
   <label><span>Einzel- / Serienfahrt</span><select name="journeyKind" defaultValue={selected.billing_journey_kind||(tripById[selected.trip_id]?.series_id?'series':'single')}><option value="single">Einzelfahrt</option><option value="series">Serienfahrt</option></select></label>
   <label><span>Pflichtfahrgebiet (Taxi)</span><select name="area" defaultValue={selected.billing_area||'unconfirmed'}><option value="unconfirmed">Nicht festgelegt / nicht erforderlich</option><option value="inside">Innerhalb</option><option value="outside">Fahrtbeginn oder -ende außerhalb</option></select></label>
   <label><span>Taxameterbetrag € (falls vereinbart)</span><input name="meterAmount" type="number" step="0.01" min="0" defaultValue={selected.meter_amount??''}/></label>
   <label><span>Positionsvorlage (bestehender Tarif)</span><input name="positionCode" defaultValue={selected.position_code||''}/></label><label><span>Behandlungscode für XX-Vorlagen</span><input name="treatmentCode" defaultValue={selected.treatment_code||''} placeholder="52 Dialyse · 05 ambulant"/></label><label><span>Eigenanteil € (automatisch)</span><input readOnly value={euro(selected.own_share_amount)}/></label><label><span>Status der Berechnung</span><input disabled value={status[selected.billing_status]||selected.billing_status}/></label></>}</div><p className="billing-review-note">{payerType==='private'?'Der Kunde zahlt den gesamten Privatpreis.':selected.copay_note||'5148: 5 €; andere Positionen: 10 %, mindestens 5 €, höchstens 10 € je Richtung. Befreiung gilt am Fahrtag.'}</p>
   {payerType==='insurer'&&selected.tariff_breakdown?.length>0&&<div className="billing-tariff-lines"><h3>Gespeicherte Berechnung</h3>{selected.tariff_breakdown.map((line,index)=><div key={index}><span><b>{line.position_code}</b> {line.label}<small>{Number(line.quantity).toLocaleString('de-DE',{maximumFractionDigits:4})} {tariffUnits[line.unit]||line.unit} × {euro(line.price)}</small></span><strong>{euro(line.amount)}</strong></div>)}<div><span>Fahrtenwert</span><strong>{euro(selected.gross_amount)}</strong></div><div><span>Abzug Eigenanteil</span><strong>− {euro(selected.own_share_amount)}</strong></div><div><b>Kassenbetrag</b><strong>{euro(selected.insurer_amount)}</strong></div></div>}
   {selected.review_message&&<div className="billing-review-note">{selected.review_message}</div>}{error&&<div className="users-error">{error}</div>}<div className="modal-actions"><span/><button type="button" className="secondary-button" onClick={()=>setSelected(null)}>Abbrechen</button><button className="primary-button" disabled={busy||Boolean(selected.invoice_id||selected.own_share_invoice_id)}><Save size={17}/>{busy?'Berechnet …':'Neu berechnen & speichern'}</button></div></form></div>}
 {receiptTarget&&<div className="modal-layer"><button className="modal-backdrop" disabled={busy} onClick={()=>setReceiptTarget(null)}/><form role="dialog" aria-modal="true" aria-label="Eigenanteil quittieren" className="modal-card compact-modal billing-check-modal" onSubmit={e=>{e.preventDefault();receipt(receiptTarget)}}><div className="modal-head"><h2>Eigenanteil quittieren</h2><button type="button" className="icon-button" disabled={busy} aria-label="Schließen" onClick={()=>setReceiptTarget(null)}><X/></button></div><p>{tripById[receiptTarget.trip_id]?.direction==='return'?'Rückfahrt':'Hinfahrt'}: <strong>{euro(receiptTarget.own_share_amount)}</strong></p><label><span>Zahlungsart</span><select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)} disabled={busy}><option value="cash">Bar</option><option value="card">Karte</option></select></label><label className="refund-confirmation"><input type="checkbox" required disabled={busy}/>Der Eigenanteil wurde vollständig bezahlt.</label>{error&&<div className="users-error" role="alert">{error}</div>}<div className="modal-actions"><span/><button type="button" disabled={busy} className="secondary-button" onClick={()=>setReceiptTarget(null)}>Abbrechen</button><button className="primary-button" disabled={busy}>{busy?'Speichert …':'Quittung erstellen'}</button></div></form></div>}
 {ownInvoiceTarget&&<div className="modal-layer"><button className="modal-backdrop" disabled={busy} onClick={()=>setOwnInvoiceTarget(null)}/><form role="dialog" aria-modal="true" aria-label="Eigenanteilsrechnung erstellen" className="modal-card compact-modal billing-check-modal" onSubmit={ownInvoice}><div className="modal-head"><h2>Eigenanteilsrechnung</h2><button type="button" className="icon-button" aria-label="Schließen" disabled={busy} onClick={()=>setOwnInvoiceTarget(null)}><X/></button></div><p>{customerById[ownInvoiceTarget.customer_id]?.first_name} {customerById[ownInvoiceTarget.customer_id]?.last_name} · {tripById[ownInvoiceTarget.trip_id]?.service_date} · {tripById[ownInvoiceTarget.trip_id]?.direction==='return'?'Rückfahrt':'Hinfahrt'}</p><p>Patientenbetrag: <strong>{euro(ownInvoiceTarget.own_share_amount)}</strong></p><p className="billing-review-note">Separate Patientenrechnung aus unserem System. Der Kassenbetrag bleibt getrennt. Die Rechnung ist nach Erstellung offen und kann über Drucken / PDF für Post oder E-Mail gespeichert werden.</p><label><span>Fällig am</span><input name="dueDate" type="date" required defaultValue={new Date(Date.now()+14*86400000).toLocaleDateString('en-CA')} min={new Date().toLocaleDateString('en-CA')} disabled={busy}/></label>{error&&<div className="users-error" role="alert">{error}</div>}<div className="modal-actions"><span/><button type="button" className="secondary-button" disabled={busy} onClick={()=>setOwnInvoiceTarget(null)}>Abbrechen</button><button className="primary-button" disabled={busy}>{busy?'Erstellt …':'Patientenrechnung erstellen'}</button></div></form></div>}
 </>}
 {preview&&<DocumentPreview title={preview.kind==='receipt'?`Quittung ${preview.doc.receipt_number}`:`Rechnung ${preview.doc.invoice_number}`} html={preview.kind==='receipt'?renderReceipt(preview.doc):renderInvoice(preview.doc,financeData?.invoiceItems||[])} onClose={()=>setPreview(null)}/>}
 </section>;
}
