import PatientReminderSettings from './PatientReminderSettings.jsx';
import React,{useEffect,useState} from 'react';
import {loadCompanyProfile,saveCompanyProfile} from '../data/finance.js';
import {renderInvoice} from '../lib/printFinanceDocuments.js';
import DocumentPreview from './DocumentPreview.jsx';
const groups=[['Unternehmen',[['company_name','Firmenname'],['owner_name','Inhaber / Rechtsform'],['street','Straße und Hausnummer'],['postal_code','Postleitzahl'],['city','Ort'],['country','Land'],['phone','Telefon'],['email','E-Mail'],['website','Website']]],['Abrechnungskennungen',[['ik_number','Institutionskennzeichen (9 Ziffern)'],['tax_number','Steuernummer'],['vat_id','Umsatzsteuer-ID']]],['Bankverbindung',[['bank_name','Bank'],['iban','IBAN'],['bic','BIC']]],['Hinweise auf der Rechnung',[['payment_note','Zahlungshinweis'],['tax_note','Steuerhinweis']]]];
export default function BusinessSettings({loadProfile=loadCompanyProfile,saveProfile=saveCompanyProfile,reminderSettingsApi}){
 const [profile,setProfile]=useState({country:'Deutschland'}),[loading,setLoading]=useState(true),[loadFailed,setLoadFailed]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[preview,setPreview]=useState(false);
 useEffect(()=>{let alive=true;loadProfile().then(p=>{if(alive)setProfile({country:'Deutschland',...p})}).catch(e=>{if(alive){setError(e.message);setLoadFailed(true)}}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[loadProfile]);
 async function submit(e){e.preventDefault();setSaving(true);setMessage('');setError('');const result=await saveProfile(profile);setSaving(false);if(!result.ok)setError(result.message);else setMessage('Unternehmensdaten gespeichert. Neue Belege übernehmen diese Angaben.');}
 const missing=[['company_name','Firmenname'],['street','Straße'],['postal_code','Postleitzahl'],['city','Ort']].filter(([key])=>!profile[key]?.trim()).map(x=>x[1]);
 return <section><div className="module-toolbar"><div><h2>Unternehmensdaten & Rechnungsvorlage</h2><p className="module-subtitle">Angaben für diesen Geschäftsbereich. Bereits erstellte Belege behalten ihre gespeicherten Firmendaten.</p></div><button className="secondary-button" disabled={loading||loadFailed} onClick={()=>setPreview(true)}>Vorlage ansehen</button></div>{error&&<div className="users-error" role="alert">{error}</div>}{message&&<p role="status">{message}</p>}{loading?<p>Lädt …</p>:loadFailed?<p>Bitte Einstellungen erneut öffnen, um die Unternehmensdaten zu laden.</p>:<form onSubmit={submit} className="business-settings">{missing.length>0&&<p>Für neue Belege fehlen noch: {missing.join(', ')}. Unvollständige Angaben können als Entwurf gespeichert werden.</p>}{groups.map(([title,fields])=><fieldset key={title}><legend>{title}</legend><div className="form-grid">{fields.map(([key,label])=><label key={key}><span>{label}</span>{key.endsWith('_note')?<textarea rows="3" maxLength={1000} value={profile[key]||''} onChange={e=>setProfile({...profile,[key]:e.target.value})}/>:<input type={key==='email'?'email':'text'} maxLength={180} value={profile[key]||''} onChange={e=>setProfile({...profile,[key]:e.target.value})}/>}</label>)}</div></fieldset>)}<p>Steuerhinweise und Kennungen gemäß den eigenen Unternehmensunterlagen eintragen.</p><button className="primary-button" disabled={saving}>{saving?'Speichert …':'Unternehmensdaten speichern'}</button></form>}<PatientReminderSettings api={reminderSettingsApi}/>{preview&&<DocumentPreview title="Rechnungsvorlage – Muster" onClose={()=>setPreview(false)} html={renderInvoice({id:'sample',invoice_number:'MUSTER – kein Zahlungsbeleg',status:'draft',issue_date:new Date().toISOString().slice(0,10),service_date:new Date().toISOString().slice(0,10),payer_name:'Musterempfänger',payer_address:'Musterstraße 1, 12345 Musterstadt',customer_name:'Musterpatient',net_total:100,vat_total:0,gross_total:100,issuer_snapshot:profile},[{invoice_id:'sample',description:'Musterfahrt',quantity:1,unit:'Fahrt',unit_gross:100,vat_rate:0,gross_total:100}])}/>}</section>
}
