import React,{useRef,useState} from 'react';
import OriginalDocumentPreview from './OriginalDocumentPreview.jsx';
import {expenseDocumentsApi} from '../data/accountingDocuments.js';
export default function ExpenseDocuments({entry,documents=[],onClose,onChanged,api=expenseDocumentsApi}){
 const [files,setFiles]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[progress,setProgress]=useState(''),[status,setStatus]=useState('ready'),[preview,setPreview]=useState(null);const completed=useRef(new Set());
 async function upload(e){e.preventDefault();setError('');if(!files.length){setError('PDF oder Foto auswählen.');return}setBusy(true);try{for(let n=0;n<files.length;n++){if(completed.current.has(n))continue;setProgress(`Datei ${n+1} von ${files.length} wird hochgeladen …`);await api.upload(files[n],entry.id);completed.current.add(n)}setFiles([]);completed.current.clear();await onChanged();setStatus('ready');setProgress('Originalbelege gespeichert.')}catch(e){setError((completed.current.size?`${completed.current.size} Datei(en) bereits gespeichert. `:'')+e.message);await onChanged()}finally{setBusy(false)}}
 async function change(doc,action){setBusy(true);setError('');try{await api[action](doc.id);await onChanged()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <><div className="modal-layer"><button className="modal-backdrop" disabled={busy} onClick={onClose}/><section className="modal-card billing-check-modal" role="dialog" aria-modal="true" aria-label="Ausgabenbelege"><div className="batch-heading"><h2>Ausgabenbelege</h2><button className="secondary-button" disabled={busy} onClick={onClose}>Schließen</button></div><p>{entry.reference} · {entry.recipient}</p>{error&&<p role="alert" className="users-error">{error}</p>}{progress&&<p role="status">{progress}</p>}{!entry.cancelled_at&&<form onSubmit={upload}><label className="document-file-input"><span>Originaldateien auswählen</span><input aria-label="Ausgabenbelege auswählen" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" multiple disabled={busy} onChange={e=>{setFiles([...e.target.files]);completed.current.clear();setProgress('')}}/><small>PDF, JPEG, PNG oder WebP · höchstens 10 MB je Datei. Kamera-/Fotoauswahl auf Mobilgeräten möglich.</small></label><button className="primary-button" disabled={busy}>Belege hochladen</button></form>}{entry.cancelled_at&&<p>Die Ausgabe wurde aufgehoben. Bereits gespeicherte Originale bleiben erhalten.</p>}<div className="shift-buttons"><button className="secondary-button" disabled={busy} onClick={()=>setStatus('ready')}>Aktive Belege</button><button className="secondary-button" disabled={busy} onClick={()=>setStatus('archived')}>Archiv</button></div><div className="batch-list">{documents.filter(d=>d.status===status).map(d=><article key={d.id} className="batch-card"><div><h3>{d.file_name}</h3><p>{(d.size_bytes/1024).toLocaleString('de-DE',{maximumFractionDigits:1})} KB · Original gespeichert</p><div className="shift-buttons">{status==='ready'&&<button className="secondary-button" disabled={busy} onClick={()=>setPreview(d)}>Vorschau</button>}<button className="text-button" disabled={busy} onClick={()=>change(d,status==='ready'?'archive':'restore')}>{status==='ready'?'Archivieren':'Wiederherstellen'}</button></div></div></article>)}</div>{!documents.some(d=>d.status===status)&&<p>{status==='ready'?'Noch keine aktiven Originalbelege.':'Archiv ist leer.'}</p>}{documents.filter(d=>d.status==='pending').map(d=><article className="batch-card" key={d.id}><div><h3>{d.file_name}</h3><p>Upload noch nicht abgeschlossen. Eigene oder mehr als eine Stunde alte Uploads können abgebrochen werden.</p><button className="text-button" disabled={busy} onClick={()=>change(d,'abort')}>Unvollständigen Upload abbrechen</button></div></article>)}</section></div>{preview&&<OriginalDocumentPreview document={preview} onClose={()=>setPreview(null)} loadPreview={api.preview}/>}</>;
}
