import React,{useMemo,useState} from 'react';
import {financeReport,reportCategories,reportMonth,reportMoney} from '../lib/financeReports.js';
const statusNames={open:'Offen',paid:'Bezahlt',cancelled:'Storniert'};
export default function FinanceReports({data}){
 const [month,setMonth]=useState(reportMonth),[category,setCategory]=useState(''),[payer,setPayer]=useState(''),[page,setPage]=useState(0);
 const {report,error}=useMemo(()=>{if(data.loading||data.error)return {};try{return {report:financeReport(data,{month,category,payer})}}catch(e){return {error:e.message}}},[data,month,category,payer]);
 const maxPage=Math.max(0,Math.ceil((report?.rows.length||0)/50)-1),currentPage=Math.min(page,maxPage),rows=report?.rows.slice(currentPage*50,currentPage*50+50)||[];
 return <section className="batch-panel finance-report"><div className="batch-heading"><div><p className="eyebrow">BERICHTE & STATISTIKEN</p><h2>Rechnungen & Kostenträger</h2><p>Rechnungsvolumen nach Ausstellungsmonat. Stornobelege zählen mit negativem Betrag im Monat ihrer Ausstellung; Original und Ersatzrechnung bleiben nachvollziehbar.</p></div><button className="secondary-button" disabled={data.loading} onClick={()=>data.refresh()}>Aktualisieren</button></div>
 <div className="form-grid"><label><span>Rechnungsmonat</span><input type="month" aria-label="Rechnungsmonat" value={month} onChange={e=>{if(e.target.value){setMonth(e.target.value);setPage(0)}}}/></label><label><span>Rechnungsart</span><select aria-label="Rechnungsart" value={category} onChange={e=>{setCategory(e.target.value);setPayer('');setPage(0)}}><option value="">Alle Rechnungsarten</option>{Object.entries(reportCategories).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label><label><span>Kostenträger</span><select aria-label="Kostenträger im Bericht" value={payer} onChange={e=>{setPayer(e.target.value);setPage(0)}}><option value="">Alle Kostenträger</option>{report?.payers.map(p=><option key={p.key} value={p.key}>{p.name}</option>)}</select></label></div>
 {(data.error||error)&&<p className="users-error" role="alert">{data.error||error}</p>}{data.loading&&<p role="status">Rechnungsbericht wird geladen …</p>}
 {report&&<><div className="batch-summary"><span>Rechnungen <b>{report.totals.invoices}</b></span><span>Stornobelege <b>{report.totals.cancellations}</b></span><span>Netto <b>{reportMoney(report.totals.net)}</b></span><span>MwSt. <b>{reportMoney(report.totals.vat)}</b></span><span>Rechnungsvolumen brutto <b>{reportMoney(report.totals.gross)}</b></span><span>Davon aktuell offen <b>{reportMoney(report.totals.open)}</b></span></div>
 <p>Offene Beträge zeigen den aktuellen Zahlungsstand der ausgewählten Rechnungen, einschließlich Teilzahlungen. Rechnungsvolumen ist kein Zahlungseingang. Quittungen werden nicht zusätzlich addiert. Kassenrechnungen enthalten bereits den Abzug des Eigenanteils.</p>
 <div className="batch-summary"><span>Aktuell offen aus allen Monaten (gleiche Filter) <b>{reportMoney(report.totals.allOpen)}</b></span><span>Noch zu bestätigende Rückzahlungen aus allen Monaten <b>{reportMoney(report.totals.refundDue)}</b></span></div>
 {!!report.legacy.length&&<p role="status">{report.legacy.length} ältere stornierte Rechnung(en) ohne eigenen Stornobeleg sind aus dem Rechnungsvolumen ausgeschlossen. Ihre ursprünglichen Belege bleiben in der Rechnungsliste erhalten.</p>}
 <h3>Nach Kostenträger</h3><div className="batch-list">{report.groups.map(g=><article className="batch-card" key={g.key}><div><h4>{g.name}</h4><p>{g.count} Belege · Netto {reportMoney(g.net)} · MwSt. {reportMoney(g.vat)}</p></div><div><strong>{reportMoney(g.gross)}</strong><p>Aktuell offen {reportMoney(g.open)}</p></div></article>)}</div>
 <h3>Belege im Monat</h3>{!rows.length&&<p>Keine Rechnungsbelege für diese Auswahl.</p>}<div className="batch-list">{rows.map(i=><article className="batch-card" key={i.id}><div><h4>{i.invoice_number} · {i.payer_name||i.customer_name}</h4><p>{i.issue_date.split('-').reverse().join('.')} · {i.document_type==='cancellation'?'Stornobeleg':`${reportCategories[i.category]} · ${statusNames[i.status]||i.status}`}</p>{i.reference_invoice_number&&<p>Bezug: {i.reference_invoice_number}</p>}</div><div><strong>{reportMoney(i.gross)}</strong><p>Aktuell offen {reportMoney(i.open)}</p></div></article>)}</div>
 <div className="shift-buttons"><button className="secondary-button" disabled={!currentPage} onClick={()=>setPage(currentPage-1)}>Vorherige Belegseite</button><span>{report.rows.length?`${currentPage*50+1}–${Math.min((currentPage+1)*50,report.rows.length)} von ${report.rows.length}`:'0 Belege'}</span><button className="secondary-button" disabled={currentPage>=maxPage} onClick={()=>setPage(currentPage+1)}>Nächste Belegseite</button></div></>}
 </section>;
}
