import React,{useEffect,useRef,useState} from 'react';
import {messagesApi} from '../data/messages.js';
const stamp=value=>new Date(value).toLocaleString('de-DE',{timeZone:'Europe/Berlin',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'});
export default function Messages({api=messagesApi}){
 const [inbox,setInbox]=useState(null),[selected,setSelected]=useState(''),[conversation,setConversation]=useState(null),[offset,setOffset]=useState(0),[before,setBefore]=useState(null),[text,setText]=useState(''),[loading,setLoading]=useState(true),[detailLoading,setDetailLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[detailError,setDetailError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0);const listSeq=useRef(0),detailSeq=useRef(0),request=useRef(null),drafts=useRef(new Map());
 useEffect(()=>{const seq=++listSeq.current;setLoading(true);setError('');Promise.resolve().then(()=>api.list(offset)).then(r=>{if(seq!==listSeq.current)return;setInbox(r);if(r.role==='driver')setSelected(r.driver_id)}).catch(e=>{if(seq===listSeq.current){setInbox(null);setError(e.message)}}).finally(()=>{if(seq===listSeq.current)setLoading(false)});return()=>{listSeq.current++}},[api,offset,revision]);
 useEffect(()=>{const seq=++detailSeq.current;if(!selected){setConversation(null);setDetailLoading(false);return}setDetailLoading(true);setDetailError('');Promise.resolve().then(()=>api.conversation(selected,before)).then(r=>{if(seq===detailSeq.current)setConversation(r)}).catch(e=>{if(seq===detailSeq.current){setConversation(null);setDetailError(e.message)}}).finally(()=>{if(seq===detailSeq.current)setDetailLoading(false)});return()=>{detailSeq.current++}},[api,selected,before,revision]);
 useEffect(()=>{const timer=setInterval(()=>{if(!document.hidden&&!busy)setRevision(n=>n+1)},30000);return()=>clearInterval(timer)},[busy]);
 function select(id){if(busy)return;drafts.current.set(selected,text);setSelected(id);setText(drafts.current.get(id)||'');setConversation(null);setBefore(null);setDetailError('');setNotice('');setRevision(n=>n+1)}
 async function send(e){e.preventDefault();setNotice('');setDetailError('');const content=text.trim();if(!content||content.length>5000){setDetailError('Nachricht mit 1 bis 5000 Zeichen eingeben.');return}if(!conversation?.can_send||loading||detailLoading||busy)return;const fingerprint=JSON.stringify([selected,content]);if(request.current?.fingerprint!==fingerprint)request.current={fingerprint,id:crypto.randomUUID()};setBusy(true);try{await api.send({driverId:selected,text:content,requestId:request.current.id});setText('');drafts.current.delete(selected);request.current=null;setBefore(null);setNotice('Nachricht gesendet.');setRevision(n=>n+1)}catch(e){setDetailError(e.message)}finally{setBusy(false)}}
 const last=conversation?.rows.at(-1)?.sequence||0,driverMode=inbox?.role==='driver',ownSide=driverMode?'driver':'office',readSequence=conversation?.thread?.[driverMode?'driver_read_sequence':'office_read_sequence']||0;
 async function read(){setBusy(true);setDetailError('');try{await api.read(selected,last);setNotice('Gelesener Nachrichtenstand bestätigt.');setRevision(n=>n+1)}catch(e){setDetailError(e.message)}finally{setBusy(false)}}
 const contacts=new Map((inbox?.contacts||[]).map(c=>[c.id,c]));for(const t of inbox?.threads||[])if(!contacts.has(t.driver_id))contacts.set(t.driver_id,{id:t.driver_id,name:t.driver_name});if(selected&&!contacts.has(selected))contacts.set(selected,{id:selected,name:conversation?.driver_name||'Ausgewähltes Gespräch'});
 return <section className="batch-panel messages-panel"><div className="batch-heading"><div><p className="eyebrow">NACHRICHTEN</p><h2>{driverMode?'Mein Gespräch mit dem Büro':'Büro & Fahrer'}</h2><p>Interne Textnachrichten. Geöffnete Ansicht aktualisiert sich alle 30 Sekunden. Lesebestätigung erfolgt ausdrücklich.</p></div><button className="secondary-button" disabled={busy||loading} onClick={()=>setRevision(n=>n+1)}>Nachrichten aktualisieren</button></div>{error&&<p role="alert" className="users-error">{error}</p>}{notice&&<p role="status">{notice}</p>}{loading&&<p role="status">Nachrichten werden geladen …</p>}
 {inbox&&<><p className="messages-unread">{inbox.unread} ungelesene Nachricht(en){!driverMode&&' · gemeinsamer Büro-Posteingang'}</p>{!driverMode&&<><label><span>Gespräch mit Fahrer wählen</span><select aria-label="Nachrichten Fahrer" value={selected} disabled={busy||loading} onChange={e=>select(e.target.value)}><option value="">Fahrer auswählen</option>{[...contacts.values()].map(c=><option key={c.id} value={c.id}>{c.name}{c.personnel_number?' · Personal-Nr. '+c.personnel_number:''}</option>)}</select></label><div className="messages-inbox">{inbox.threads.map(t=><button className={'message-thread '+(selected===t.driver_id?'active':'')} key={t.id} disabled={busy||loading} onClick={()=>select(t.driver_id)}><strong>{t.driver_name}</strong><span>{t.unread} ungelesen · {stamp(t.updated_at)}</span><small>{t.preview}</small></button>)}</div>{!inbox.threads.length&&<p>Noch keine Gespräche. Einen Fahrer mit aktivem App-Zugang auswählen.</p>}<div className="shift-buttons"><button className="secondary-button" disabled={!offset||busy||loading} onClick={()=>setOffset(n=>Math.max(0,n-50))}>Vorherige Gesprächsseite</button><span>{inbox.count?`${offset+1}–${Math.min(offset+50,inbox.count)} von ${inbox.count}`:'0 Gespräche'}</span><button className="secondary-button" disabled={offset+50>=inbox.count||busy||loading} onClick={()=>setOffset(n=>n+50)}>Nächste Gesprächsseite</button></div></>}
 {detailLoading&&<p role="status">Gespräch wird geladen …</p>}{detailError&&<p role="alert" className="users-error">{detailError}</p>}{selected&&conversation&&<div className="messages-conversation"><h3>{driverMode?'Büro':conversation.driver_name}</h3><div className="shift-buttons"><button className="secondary-button" disabled={!conversation.has_older||busy||detailLoading} onClick={()=>setBefore(conversation.rows[0]?.sequence)}>Ältere Nachrichten</button><button className="secondary-button" disabled={!before||busy||detailLoading} onClick={()=>setBefore(null)}>Neueste Nachrichten</button></div><p>Bis zu 50 Nachrichten je Seite. Gesendete Texte bleiben erhalten; Korrekturen als neue Nachricht senden.</p><div className="messages-history">{conversation.rows.map(m=>{const own=m.sender_side===ownSide,seen=m.sequence<=(conversation.thread?.[m.sender_side==='office'?'driver_read_sequence':'office_read_sequence']||0);return <article className={'message-bubble '+(own?'message-own':'')} key={m.id}><div><strong>{m.sender_name} · {m.sender_side==='office'?'Büro':'Fahrer'}</strong><small>Nr. {m.sequence} · {stamp(m.created_at)}</small></div><p>{m.body}</p>{own&&<small>{seen?(driverMode?'Vom Büro als gelesen bestätigt':'Vom Fahrer als gelesen bestätigt'):'Gesendet · noch keine Lesebestätigung'}</small>}</article>})}</div>{!conversation.rows.length&&<p>Noch keine Nachrichten in diesem Gespräch.</p>}<button className="secondary-button" disabled={!last||last<=readSequence||busy||detailLoading||loading} onClick={read}>Bis Nr. {last} als gelesen bestätigen</button><p>Bestätigt das gesamte Gespräch bis zu dieser Nummer, einschließlich älterer Nachrichten. Neue Nachrichten danach bleiben ungelesen.{!driverMode&&' Eine Bestätigung gilt für den gemeinsamen Büro-Posteingang.'}</p>{!conversation.can_send&&<p>Fahrerzugang derzeit inaktiv. Bestehendes Gespräch bleibt im Büro einsehbar.</p>}<form noValidate onSubmit={send}><label><span>Nachricht an {driverMode?'das Büro':conversation.driver_name}</span><textarea aria-label="Nachrichtentext" value={text} maxLength={5000} rows={4} disabled={busy} onChange={e=>{setText(e.target.value);drafts.current.set(selected,e.target.value)}}/></label><div className="shift-buttons"><span>{text.length} / 5000 Zeichen</span><button className="primary-button" disabled={busy||loading||detailLoading||!conversation.can_send}>Nachricht senden</button></div></form></div>}</>}
 </section>;
}
