import React,{useEffect,useState} from 'react';
import {loadPatientReminderSettings,savePatientReminderSettings} from '../data/finance.js';
import {reminderStageTitle} from '../lib/patientReminders.js';
const defaultApi={load:loadPatientReminderSettings,save:savePatientReminderSettings};
export default function PatientReminderSettings({api=defaultApi}){
 const [config,setConfig]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);setError('');try{setConfig(await api.load())}catch(e){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{let alive=true;api.load().then(c=>{if(alive)setConfig(c)}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[api]);
 async function save(e){e.preventDefault();setBusy(true);setError('');setNotice('');try{const result=await api.save(config);if(!result.ok)throw Error(result.message);setConfig(result.data);setNotice('Mahnstufen gespeichert. Neue Schreiben übernehmen diese Vorgaben.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 function edit(index,key,value){setConfig(c=>({...c,stages:c.stages.map((s,i)=>i===index?{...s,[key]:value}:s)}))}
 return <section className="batch-panel"><div className="batch-heading"><div><h2>Mahnstufen</h2><p>Texte und Zahlungsfristen für Eigenanteilsrechnungen. Die Frist zählt ab dem Datum des neuen Schreibens. Die nächste Stufe wird erst nach bestätigtem Versand und Ablauf der vorherigen Zahlungsfrist vorgeschlagen.</p></div><button type="button" className="secondary-button" disabled={busy} onClick={load}>Mahneinstellungen neu laden</button></div><p>Vor dem Vorbereiten kannst du Text und Zahlungsdatum noch anpassen. Bestehende Schreiben bleiben unverändert. Versand erfolgt manuell; Gebühren und Zinsen werden nicht ergänzt.</p>{error&&<p className="users-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{config?<form className="business-settings" onSubmit={save}>{config.stages.map((stage,index)=><fieldset key={index}><legend>{index+1}. Stufe · {reminderStageTitle(index+1)}</legend><div className="form-grid"><label><span>Zahlungsfrist in Tagen · Stufe {index+1}</span><input aria-label={`Zahlungsfrist in Tagen · Stufe ${index+1}`} type="number" min={1} max={90} step={1} required disabled={busy} value={stage.days} onChange={e=>edit(index,'days',e.target.value===''?'':Number(e.target.value))}/></label><label className="wide"><span>Text · Stufe {index+1}</span><textarea aria-label={`Text · Stufe ${index+1}`} rows={5} minLength={10} maxLength={2000} required disabled={busy} value={stage.message} onChange={e=>edit(index,'message',e.target.value)}/></label></div></fieldset>)}<button className="primary-button" disabled={busy}>{busy?'Speichert …':'Mahnstufen speichern'}</button></form>:!error&&<p role="status">Mahneinstellungen werden geladen …</p>}</section>
}
