import React,{useState}from'react';import{Plus,ReceiptText,Save,X}from'lucide-react';import{createReceipt}from'../data/finance.js';import{renderReceipt}from'../lib/printFinanceDocuments.js';import DocumentPreview from './DocumentPreview.jsx';
const euro=n=>Number(n||0).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
export default function ReceiptManagement({data,clients}){const[preview,setPreview]=useState(null);const[modal,setModal]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false);async function submit(e){e.preventDefault();setSaving(true);setError('');const r=await createReceipt(Object.fromEntries(new FormData(e.currentTarget).entries()));setSaving(false);if(!r.ok){setError(r.message);return;}setModal(false);await data.refresh();}
return <section><div className="module-toolbar"><div><h2>Quittungen</h2><p className="module-subtitle">Zuzahlungsbelege für Krankenfahrten – mit Konzessionsnummer, Strecke und Zahlungsart.</p></div><button className="primary-button" onClick={()=>setModal(true)}><Plus size={17}/> Quittung erstellen</button></div>
<div className="finance-table"><div className="finance-row receipt-row finance-head"><span>Nummer</span><span>Erhalten von</span><span>Art</span><span>Betrag</span><span>Zahlart</span></div>{data.receipts.map(r=><div className="finance-row receipt-row" key={r.id}><strong data-label="Nummer">{r.receipt_number}</strong><span data-label="Erhalten von">{r.received_from}</span><span data-label="Art">{r.receipt_type==='own_share'?'Eigener Anteil':r.purpose}</span><b data-label="Betrag">{euro(r.amount)}</b><span className="receipt-payment"><span>{r.payment_method==='cash'?'Bar':'Karte'}</span><button className="text-button" onClick={()=>setPreview(r)}><ReceiptText size={14}/> Vorschau</button></span></div>)}</div>
{!data.loading&&!data.receipts.length&&<div className="module-empty"><ReceiptText/><h3>Noch keine Quittungen</h3><p>Eigene Anteile für Krankenfahrten können hier quittiert werden.</p></div>}
{preview&&<DocumentPreview title={`Quittung ${preview.receipt_number||""}`} html={renderReceipt(preview)} onClose={()=>setPreview(null)}/>}
{modal&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setModal(false)}/><form className="modal-card compact-modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">ZAHLUNGSBELEG</p><h2>Quittung Krankenfahrt</h2></div><button type="button" className="icon-button" onClick={()=>setModal(false)}><X/></button></div>
<div className="form-grid"><label><span>Kunde</span><select name="customerId"><option value="">—</option>{clients.map(c=><option value={c.id} key={c.id}>{c.firstName} {c.lastName}</option>)}</select></label><label><span>Erhalten von</span><input name="receivedFrom" required/></label><label><span>Quittungsart</span><select name="receiptType" defaultValue="own_share"><option value="own_share">Eigener Anteil</option></select></label><label><span>Konzessionsnummer</span><input name="concessionNumber" placeholder="Konzessions-Nr."/></label><label className="wide"><span>Von</span><input name="fromAddress" placeholder="Abholadresse"/></label><label className="wide"><span>Nach</span><input name="toAddress" placeholder="Zieladresse"/></label><label><span>Betrag €</span><input name="amount" type="number" min="0.01" step="0.01" required/></label><label><span>Bezahlung</span><select name="paymentMethod"><option value="cash">Bar</option><option value="card">Karte</option></select></label><label><span>Zahlungsdatum</span><input name="paymentDate" type="date" defaultValue={new Date().toISOString().slice(0,10)}/></label></div>
{error&&<div className="users-error">{error}</div>}<div className="modal-actions"><span/><button type="button" className="secondary-button" onClick={()=>setModal(false)}>Abbrechen</button><button className="primary-button" disabled={saving}><Save size={17}/>{saving?'Speichert …':'Quittung speichern'}</button></div></form></div>}</section>}