import React,{useEffect,useRef,useState} from 'react';
import {loadShiftReport} from '../data/driverShifts.js';
import {shiftDate,shiftDuration} from '../lib/driverShifts.js';
const berlinMonth=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit'}).format(new Date()).slice(0,7);
export default function ShiftReports({drivers=[],load=loadShiftReport}){
 const [month,setMonth]=useState(berlinMonth),[driver,setDriver]=useState(''),[offset,setOffset]=useState(0),[report,setReport]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0);const latest=useRef(0);
 useEffect(()=>{const seq=++latest.current;setBusy(true);setError('');setReport(null);load({month:month+'-01',driverId:driver||null,offset}).then(r=>{if(seq!==latest.current)return;if(!r.ok)throw Error(r.message);setReport(r.data)}).catch(e=>{if(seq===latest.current)setError(e.message)}).finally(()=>{if(seq===latest.current)setBusy(false)});return()=>{latest.current++}},[load,month,driver,offset,revision]);
 const totals=report?.totals;
 return <section className="batch-panel"><div className="batch-heading"><div><p className="eyebrow">BERICHTE & STATISTIKEN</p><h2>Schichten & Kilometer</h2><p>Monat nach Schichtbeginn (Europe/Berlin). Abgeschlossene Schichten zählen in die Summen; offene Schichten stehen separat im Verlauf.</p></div><button className="secondary-button" disabled={busy} onClick={()=>setRevision(x=>x+1)}>Aktualisieren</button></div><div className="form-grid"><label><span>Berichtsmonat</span><input aria-label="Berichtsmonat" type="month" value={month} required onChange={e=>{if(e.target.value){setMonth(e.target.value);setOffset(0)}}}/></label><label><span>Fahrer filtern</span><select aria-label="Fahrer filtern" value={driver} onChange={e=>{setDriver(e.target.value);setOffset(0)}}><option value="">Alle Fahrer</option>{drivers.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div>{error&&<p className="users-error" role="alert">{error}</p>}{busy&&<p role="status">Schichtbericht wird geladen …</p>}{totals&&<><div className="batch-summary"><span>Abgeschlossene Schichten <b>{totals.closed_count}</b></span><span>Offene Schichten <b>{totals.open_count}</b></span><span>Gefahren <b>{Number(totals.km).toLocaleString('de-DE')} km</b></span><span>Zeit ohne erfasste Pausen <b>{shiftDuration(totals.working_seconds)}</b></span><span>Erfasste Pausen <b>{shiftDuration(totals.pause_seconds)}</b></span></div><p>Erfasste Schichtzeiten dienen der betrieblichen Übersicht. Diese Ansicht berechnet keine Löhne oder Zuschläge.</p><div className="batch-list">{report.rows.map(s=><article className="batch-card shift-report-card" key={s.id}><div><h3>{s.driver_name} · {s.vehicle_registration}</h3><p>{shiftDate(s.started_at)} → {s.ended_at?shiftDate(s.ended_at):s.state==='paused'?'Pause läuft':'Schicht läuft'}</p><p>Start {s.start_mileage.toLocaleString('de-DE')} km · Ende {s.end_mileage==null?'noch offen':s.end_mileage.toLocaleString('de-DE')+' km'}</p><p>Schichtdauer {shiftDuration(s.elapsed_seconds)} · Pausen {shiftDuration(s.pause_seconds)} · Ohne Pausen {shiftDuration(s.working_seconds)}</p></div><strong>{s.end_mileage==null?'Offene Schicht':(s.end_mileage-s.start_mileage).toLocaleString('de-DE')+' km'}</strong></article>)}</div>{!report.rows.length&&<p>Keine erfassten Schichten in diesem Monat.</p>}<div className="shift-buttons"><button className="secondary-button" disabled={offset===0||busy} onClick={()=>setOffset(o=>Math.max(0,o-50))}>Vorherige Seite</button><span>{totals.count?`${offset+1}–${Math.min(offset+50,totals.count)} von ${totals.count}`:'0 Schichten'}</span><button className="secondary-button" disabled={offset+50>=totals.count||busy} onClick={()=>setOffset(o=>o+50)}>Nächste Seite</button></div></>}</section>;
}
