import InsurerPaymentReconciliation from './InsurerPaymentReconciliation.jsx';
import BillingDocumentReview from './BillingDocumentReview.jsx';
import React,{useEffect,useState} from 'react';
import {loadSubmissionsWithDocuments,updateSubmission} from '../data/submissions.js';
import {batchCsv,batchTotals,renderBillingBatch} from '../lib/billingBatch.js';
import DocumentPreview from './DocumentPreview.jsx';
const labels={prepared:'Vorbereitet',web_entered:'In Weberfassung erfasst',posted:'Originalbelege versandt',discarded:'Vorbereitung verworfen'};
const euro=c=>(c/100).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export default function SubmissionRegister({load=loadSubmissionsWithDocuments,update=updateSubmission,clients=[],trips=[],onFinanceRefresh}){
 const [runs,setRuns]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[target,setTarget]=useState(null),[preview,setPreview]=useState(null),[filter,setFilter]=useState(''),[documentRun,setDocumentRun]=useState(null),[paymentRun,setPaymentRun]=useState(null);
 async function refresh(){setBusy(true);setError('');try{setRuns(await load())}catch(e){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{refresh()},[load]);
 async function submit(e){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await update(target.run.id,target.step,f.get('date'),f.get('reference'));setTarget(null);await refresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
 function csv(run){const url=URL.createObjectURL(new Blob([batchCsv(run.rows_snapshot)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`ZAD-Lauf_${run.number}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 if(paymentRun)return <><button className="secondary-button" onClick={()=>{setPaymentRun(null);refresh()}}>Zurück zur ZAD-Übersicht</button><InsurerPaymentReconciliation run={paymentRun} onChanged={onFinanceRefresh}/></>;
 if(documentRun)return <><button className="secondary-button" onClick={()=>{setDocumentRun(null);refresh()}}>Zurück zur ZAD-Übersicht</button><p>ZAD-Lauf {documentRun.number}</p><BillingDocumentReview caseIds={documentRun.rows_snapshot.map(r=>r.id)} clients={clients} trips={trips}/></>;
 return <section className="batch-panel"><div className="batch-heading"><div><p className="eyebrow">ZAD</p><h2>Erfassung und Postversand</h2></div><button className="secondary-button" disabled={busy} onClick={refresh}>Aktualisieren</button></div>
 <p>Speichere Rechnungen über die Sammelabrechnung als ZAD-Lauf. Die Übersicht hält deinen manuellen Erfassungs- und Versandstand fest. Vorschau und Download übermitteln keine Daten und bestätigen keine Zahlung.</p>
 <p className="billing-review-note">Eigenanteilsrechnungen erstellen wir selbst. Wähle bei ZAD „bereits bezahlt“ nur bei tatsächlich bezahlten Eigenanteilen. Bei offenen Patientenrechnungen die passende Erfassung mit ZAD klären.</p>
 <label><span>Status</span><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Alle Läufe</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
 {error&&!target&&<p className="users-error" role="alert">{error}</p>}{busy&&<p role="status">ZAD-Läufe werden geprüft …</p>}
 <div className="batch-list">{runs.filter(r=>!filter||r.status===filter).map(run=>{const total=batchTotals(run.rows_snapshot),documentsReady=run.documentReports?.length===run.rows_snapshot.length&&run.documentReports.every(r=>r.complete);return <article className="batch-card" key={run.id}><div><h3>ZAD-Lauf {run.number} · {run.rows_snapshot[0]?.insurerName}</h3><strong>{labels[run.status]}</strong>{['prepared','web_entered'].includes(run.status)&&run.documentReports&&<p className={documentsReady?'':'batch-blocked'}>{run.documentReports.filter(r=>r.complete).length} von {run.rows_snapshot.length} Belegprüfungen vollständig</p>}<p>Gespeichert {new Date(run.created_at).toLocaleString('de-DE')} · {total.count} Rechnungen · Kasse {euro(total.insurer)}</p><p>Fahrtenwert {euro(total.gross)} · Eigenanteile {euro(total.copay)}</p>{run.web_date&&<p>Erfasst am {run.web_date} {run.web_reference&&`· ${run.web_reference}`}</p>}{run.post_date&&<p>Per Post versandt am {run.post_date} {run.post_reference&&`· ${run.post_reference}`}</p>}{run.discard_reason&&<p>Begründung: {run.discard_reason}</p>}</div><div className="batch-toolbar">{['web_entered','posted'].includes(run.status)&&<button className="secondary-button" onClick={()=>setPaymentRun(run)}>Zahlungseingänge abgleichen</button>}{['prepared','web_entered'].includes(run.status)&&<button className="secondary-button" onClick={()=>setDocumentRun(run)}>Belege dieses Laufs prüfen</button>}<button className="secondary-button" onClick={()=>setPreview(renderBillingBatch(run.rows_snapshot))}>Gespeicherte Vorschau</button><button className="secondary-button" onClick={()=>csv(run)}>CSV herunterladen</button>{run.status==='prepared'&&<><button className="primary-button" disabled={busy||Boolean(run.documentReports&&!documentsReady)} onClick={()=>{setError('');setTarget({run,step:'web'})}}>Weberfassung bestätigen</button><button className="text-button" disabled={busy} onClick={()=>{setError('');setTarget({run,step:'discard'})}}>Vorbereitung verwerfen</button></>}{run.status==='web_entered'&&<button className="primary-button" disabled={busy||Boolean(run.documentReports&&!documentsReady)} onClick={()=>{setError('');setTarget({run,step:'post'})}}>Postversand bestätigen</button>}</div></article>})}</div>
 {!busy&&!runs.length&&<p>Noch keine ZAD-Läufe gespeichert.</p>}
 {target&&<div className="modal-layer"><button className="modal-backdrop" disabled={busy} onClick={()=>setTarget(null)}/><form className="modal-card compact-modal billing-check-modal" role="dialog" aria-modal="true" aria-label="ZAD-Status bestätigen" onSubmit={submit}><h2>{target.step==='web'?'Weberfassung bestätigen':target.step==='post'?'Postversand bestätigen':'Vorbereitung verwerfen'}</h2><p>ZAD-Lauf {target.run.number} · {target.run.rows_snapshot.length} Rechnungen</p>{target.step!=='discard'&&<label><span>Tatsächliches Datum</span><input type="date" name="date" required min={target.step==='post'?target.run.web_date:target.run.created_at.slice(0,10)} max={today()} defaultValue={today()} disabled={busy}/></label>}<label><span>{target.step==='discard'?'Begründung':'ZAD-Referenz / Versandhinweis (optional)'}</span><textarea name="reference" required={target.step==='discard'} minLength={target.step==='discard'?5:undefined} maxLength={500} disabled={busy}/></label><label><input type="checkbox" required disabled={busy}/>{target.step==='web'?'Ich habe alle Rechnungen dieses Laufs tatsächlich in ZAD erfasst.':target.step==='post'?'Ich habe die vollständigen Originalbelege geprüft und tatsächlich per Post versandt.':'Die Vorbereitung wurde noch nicht in ZAD erfasst. Ich möchte die Rechnungen für eine neue Auswahl freigeben.'}</label>{error&&<p className="users-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="secondary-button" disabled={busy} onClick={()=>setTarget(null)}>Abbrechen</button><button className="primary-button" disabled={busy}>Bestätigen und speichern</button></div></form></div>}
 {preview&&<DocumentPreview title="Gespeicherte ZAD-Sammelübersicht" html={preview} onClose={()=>setPreview(null)}/>}
 </section>
}
