import React,{useEffect,useRef,useState} from 'react';
import {CheckCircle2,RefreshCw,X} from 'lucide-react';
import {berlinToday,historyEligible,loadTripHistory,recordTripHistory} from '../data/tripHistory.js';
import {STATUS_LABELS} from '../domain/trips.js';
function previousMonth(){const [y,m]=berlinToday().split('-').map(Number);return new Date(Date.UTC(y,m-2,1)).toISOString().slice(0,7);}
const dateLabel=day=>new Date(day+'T12:00:00').toLocaleDateString('de-DE');
export default function TripHistory({clients=[],onRecorded=async()=>{},load=loadTripHistory,record=recordTripHistory}){
 const [month,setMonth]=useState(previousMonth),[customerId,setCustomer]=useState(''),[status,setStatus]=useState(''),[query,setQuery]=useState(''),[rows,setRows]=useState([]),[selected,setSelected]=useState(new Set()),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[dialog,setDialog]=useState(null),[busy,setBusy]=useState(false),[limit,setLimit]=useState(50);const request=useRef(0);
 async function refresh(){const current=++request.current;setLoading(true);setError('');setSelected(new Set());setDialog(null);try{const data=await load({month,customerId});if(current===request.current){setRows(data);setLimit(50);}}catch(e){if(current===request.current){setRows([]);setError(e.message||'Historie konnte nicht geladen werden.');}}finally{if(current===request.current)setLoading(false);}}
 useEffect(()=>{refresh();return()=>{request.current++};},[month,customerId,load]);
 const name=t=>t.customer_name||clients.find(c=>c.id===t.customer_id)?.fullName||'Kunde';
 const filtered=rows.filter(t=>(!status||t.status===status)&&(!query||[name(t),t.from_address,t.to_address,t.trip_type].join(' ').toLowerCase().includes(query.toLowerCase()))),visible=filtered.slice(0,limit),chosen=rows.filter(t=>selected.has(t.id));
 function toggle(t){setSelected(old=>{const next=new Set(old);if(next.has(t.id))next.delete(t.id);else if(next.size<100)next.add(t.id);return next});}
 function changeFilter(setter,value){setSelected(new Set());setLimit(50);setter(value);}
 function selectVisible(){const eligible=visible.filter(t=>historyEligible(t));if(eligible.every(t=>selected.has(t.id))){setSelected(old=>new Set([...old].filter(id=>!eligible.some(t=>t.id===id))));return;}setSelected(new Set(eligible.slice(0,100).map(t=>t.id)));}
 async function submit(event){event.preventDefault();if(busy)return;setBusy(true);setError('');try{const result=await record(dialog.trips,dialog.decision,new FormData(event.currentTarget).get('note'));setNotice(`${result.recorded||0} Fahrten ${dialog.decision==='abgeschlossen'?'als durchgeführt bestätigt':'als ausgefallen erfasst'}${result.alreadyRecorded?' · '+result.alreadyRecorded+' bereits erfasst':''}.`);setDialog(null);await refresh();await onRecorded();}catch(e){setError(e.message||'Speichern fehlgeschlagen.');}finally{setBusy(false);}}
 return <section className="history-page">
  <div className="panel history-toolbar"><div><p className="eyebrow">VERGANGENE FAHRTEN</p><h2>Fahrtenhistorie</h2><p>Durchführung prüfen, Ausfälle ausschließen und Abrechnung vorbereiten.</p></div><button className="secondary-button" disabled={loading||busy} onClick={refresh}><RefreshCw size={16}/> Neu laden</button></div>
  <div className="panel history-filters"><label><span>Monat</span><input aria-label="Monat" type="month" value={month} onChange={e=>e.target.value&&changeFilter(setMonth,e.target.value)} disabled={busy}/></label><label><span>Kunde</span><select aria-label="Kunde" value={customerId} onChange={e=>changeFilter(setCustomer,e.target.value)} disabled={busy}><option value="">Alle Kunden</option>{clients.map(c=><option key={c.id} value={c.id}>{c.fullName}</option>)}</select></label><label><span>Status</span><select aria-label="Status" value={status} onChange={e=>changeFilter(setStatus,e.target.value)} disabled={busy}><option value="">Alle Status</option>{Object.entries(STATUS_LABELS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label><span>Suche in diesem Monat</span><input type="search" value={query} onChange={e=>changeFilter(setQuery,e.target.value)} disabled={busy} placeholder="Name oder Strecke"/></label></div>
  {notice&&<div role="status" className="users-notice">{notice}</div>}{error&&<div role="alert" className="users-error">{error}</div>}
  <div className="panel history-actions"><span>{filtered.length} Fahrten · {selected.size} ausgewählt</span><button className="secondary-button" disabled={loading||busy||!visible.some(t=>historyEligible(t))} onClick={selectVisible}>Sichtbare offene auswählen</button><button className="primary-button" disabled={loading||busy||!chosen.length} onClick={()=>setDialog({decision:'abgeschlossen',trips:chosen})}><CheckCircle2 size={17}/> Durchführung bestätigen</button><button className="secondary-button" disabled={loading||busy||!chosen.length} onClick={()=>setDialog({decision:'storniert',trips:chosen})}>Als ausgefallen erfassen</button><small>Maximal 100 Fahrten pro Bestätigung. Nur vergangene offene oder geplante Fahrten sind auswählbar.</small></div>
  <div className="history-list">{loading?<div className="panel users-loading">Historie wird geladen …</div>:!filtered.length?<div className="panel users-loading">Keine Fahrten für diese Auswahl.</div>:visible.map(t=><article key={t.id} data-trip-id={t.id} className="panel history-card"><label className="history-select"><input type="checkbox" aria-label={`Fahrt ${dateLabel(t.service_date)} ${t.direction==='return'?'Rückfahrt':'Hinfahrt'} ${name(t)}`} checked={selected.has(t.id)} disabled={busy||!historyEligible(t)||(!selected.has(t.id)&&selected.size>=100)} onChange={()=>toggle(t)}/><span><strong>{name(t)}</strong><span>{dateLabel(t.service_date)} · {String(t.scheduled_time||'').slice(0,5)} · {t.direction==='return'?'Rückfahrt':'Hinfahrt'}</span></span></label><div className="history-route"><span>{t.from_address}</span><span>→ {t.to_address}</span><small>{t.trip_type}</small></div><div><span className={'status-pill status-'+t.status}>{STATUS_LABELS[t.status]||t.status}</span>{t.history_recorded_at&&<small>Nachträglich erfasst am {new Date(t.history_recorded_at).toLocaleDateString('de-DE')}<br/>{t.history_note}</small>}</div></article>)}</div>
  {!loading&&filtered.length>limit&&<button className="secondary-button" onClick={()=>setLimit(n=>n+50)}>Weitere Fahrten anzeigen</button>}
  {dialog&&<div className="modal-layer"><button className="modal-backdrop" disabled={busy} onClick={()=>setDialog(null)} aria-label="Dialog schließen"/><form className="modal-card history-dialog" role="dialog" aria-label={dialog.decision==='abgeschlossen'?'Durchführung bestätigen':'Ausfälle erfassen'} onSubmit={submit}><div className="modal-head"><h2>{dialog.decision==='abgeschlossen'?'Durchführung bestätigen':'Ausfälle erfassen'}</h2><button type="button" className="icon-button" disabled={busy} onClick={()=>setDialog(null)} aria-label="Schließen"><X/></button></div><p>{dialog.trips.length} ausgewählte Fahrten. Hin- und Rückfahrt werden einzeln erfasst.</p><ul className="history-confirm-list">{dialog.trips.map(t=><li key={t.id}>{dateLabel(t.service_date)} · {name(t)} · {t.direction==='return'?'Rückfahrt':'Hinfahrt'}</li>)}</ul><p>{dialog.decision==='abgeschlossen'?'Es entstehen prüfbare Abrechnungsfälle. Kilometer, Vertrag und Eigenanteil sind vor der Rechnung zu prüfen.':'Diese Fahrten werden storniert und erhalten keine Abrechnungsfälle.'}</p><label><span>{dialog.decision==='abgeschlossen'?'Nachweis / Notiz':'Grund des Ausfalls'}</span><textarea name="note" rows="2" minLength={3} maxLength={2000} required disabled={busy} defaultValue={dialog.decision==='abgeschlossen'?'Durchführung anhand Fahrtnachweis geprüft.':''}/></label><label className="history-attestation"><input type="checkbox" required disabled={busy}/><span>{dialog.decision==='abgeschlossen'?'Ich bestätige, dass alle ausgewählten Fahrten tatsächlich durchgeführt wurden.':'Ich bestätige, dass alle ausgewählten Fahrten ausgefallen sind.'}</span></label>{error&&<div className="users-error" role="alert">{error}</div>}<div className="modal-actions"><button type="button" className="secondary-button" disabled={busy} onClick={()=>setDialog(null)}>Abbrechen</button><button className="primary-button" disabled={busy}>{busy?'Wird gespeichert …':'Verbindlich speichern'}</button></div></form></div>}
 </section>;
}
