import React,{useEffect,useMemo,useRef,useState} from 'react';
import {loadUtilization} from '../data/utilization.js';
import {berlinDay,utilizationReport,utilizationCsv,utilizationRange} from '../lib/utilization.js';
import {shiftDuration} from '../lib/driverShifts.js';
export default function UtilizationReports({load=loadUtilization}){
 const [month,setMonth]=useState(()=>berlinDay(new Date()).slice(0,7)),[day,setDay]=useState(''),[driver,setDriver]=useState(''),[vehicle,setVehicle]=useState(''),[view,setView]=useState('days'),[page,setPage]=useState(0),[data,setData]=useState(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0);const latest=useRef(0);
 useEffect(()=>{const seq=++latest.current;setBusy(true);setData(null);setError('');Promise.resolve().then(()=>load(month)).then(d=>{if(seq===latest.current)setData(d)}).catch(e=>{if(seq===latest.current)setError(e.message)}).finally(()=>{if(seq===latest.current)setBusy(false)});return()=>{latest.current++}},[load,month,revision]);
 const result=useMemo(()=>{if(!data||busy)return {};try{return {base:utilizationReport(data,{month}),report:utilizationReport(data,{month,day,driver,vehicle})}}catch(e){return {error:e.message}}},[data,busy,month,day,driver,vehicle]),r=result.report,rows=r?.[view]||[],maxPage=Math.max(0,Math.ceil(rows.length/50)-1),current=Math.min(page,maxPage);
 const choose=(setter,value)=>{setter(value);setPage(0)};
 function download(){const url=URL.createObjectURL(new Blob([utilizationCsv(rows)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`Auslastung-${day||month}-${view}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 let lastDay='';try{lastDay=new Date(Date.parse(utilizationRange(month).next+'T12:00Z')-86400000).toISOString().slice(0,10)}catch{}
 return <section className="batch-panel utilization-panel"><div className="batch-heading"><div><p className="eyebrow">BERICHTE & STATISTIKEN</p><h2>Fahrer- & Fahrzeugauslastung</h2><p>Fahrten nach Fahrtdatum, Schichten nach ihrem Beginn in Europe/Berlin. Auch Schichten über Mitternacht zählen vollständig zum Starttag.</p></div><button className="secondary-button" disabled={busy} onClick={()=>setRevision(n=>n+1)}>Aktualisieren</button></div>
 <div className="form-grid"><label><span>Auslastungsmonat</span><input aria-label="Auslastungsmonat" type="month" min="2000-01" max="2100-12" value={month} onChange={e=>{if(e.target.value){setMonth(e.target.value);setDay('');setPage(0)}}}/></label><label><span>Einzelner Tag (optional)</span><input aria-label="Auslastungstag" type="date" min={month+'-01'} max={lastDay} value={day} onChange={e=>choose(setDay,e.target.value)}/></label><label><span>Fahrer</span><select aria-label="Auslastung Fahrer" disabled={busy} value={driver} onChange={e=>choose(setDriver,e.target.value)}><option value="">Alle Fahrer</option><option value="__unassigned__">Ohne Fahrerzuordnung</option>{driver&&driver!=='__unassigned__'&&!result.base?.drivers.some(d=>d.id===driver)&&<option value={driver}>Ausgewählter Fahrer (keine Daten im Monat)</option>}{result.base?.drivers.filter(d=>d.id!=='__unassigned__').map(d=><option key={d.id} value={d.id}>{d.label}</option>)}</select></label><label><span>Fahrzeug</span><select aria-label="Auslastung Fahrzeug" disabled={busy} value={vehicle} onChange={e=>choose(setVehicle,e.target.value)}><option value="">Alle Fahrzeuge</option><option value="__unassigned__">Ohne Fahrzeugzuordnung</option>{vehicle&&vehicle!=='__unassigned__'&&!result.base?.vehicles.some(v=>v.id===vehicle)&&<option value={vehicle}>Ausgewähltes Fahrzeug (keine Daten im Monat)</option>}{result.base?.vehicles.filter(v=>v.id!=='__unassigned__').map(v=><option key={v.id} value={v.id}>{v.label}</option>)}</select></label></div>
 {(error||result.error)&&<p className="users-error" role="alert">{error||result.error}</p>}{busy&&<p role="status">Auslastungsbericht wird geladen …</p>}
 {r&&<><div className="batch-summary" aria-label="Auslastung Summen"><span>Durchgeführt <b>{r.totals.completed}</b></span><span>Offen / geplant <b>{r.totals.planned}</b></span><span>Laufend <b>{r.totals.running}</b></span><span>Storniert <b>{r.totals.cancelled}</b></span><span>Nicht erschienen <b>{r.totals.noShow}</b></span><span>Kilometer <b>{r.totals.km.toLocaleString('de-DE')} km</b></span><span>Schichtzeit ohne Pausen <b>{shiftDuration(r.totals.working)}</b></span><span>Pausen <b>{shiftDuration(r.totals.paused)}</b></span><span>Abgeschlossene Schichten <b>{r.totals.closedShifts}</b></span><span>Offene Schichten <b>{r.totals.openShifts}</b></span></div>
 <p>Ohne Fahrerzuordnung: {r.totals.unassignedDriver} Fahrt(en) · Ohne Fahrzeugzuordnung: {r.totals.unassignedVehicle} Fahrt(en). {r.totals.unknown>0&&`Unbekannter Fahrtstatus: ${r.totals.unknown}.`} Geplante Fahrten bleiben getrennt von durchgeführten Fahrten. Kilometer und Zeitsummen enthalten nur abgeschlossene Schichten; offene Schichten werden gezählt. Kilometer umfassen alle erfassten Schichtkilometer einschließlich Leerfahrten. Fahrtzeiten und prozentuale Auslastung werden nicht geschätzt.</p>
 <div className="module-tabs finance-tabs" aria-label="Auslastungsansicht">{[['days','Tage'],['drivers','Fahrer'],['vehicles','Fahrzeuge']].map(([key,label])=><button key={key} className={view===key?'active':''} aria-pressed={view===key} onClick={()=>choose(setView,key)}>{label}</button>)}</div><button className="secondary-button" disabled={!rows.length} onClick={download}>Auslastung CSV herunterladen</button><p>CSV enthält alle Gruppen der gewählten Ansicht und Filter, auch über 50 Anzeigezeilen hinaus.</p>
 <div className="batch-list">{rows.slice(current*50,current*50+50).map(row=><article className="batch-card utilization-card" key={row.id} data-utilization-id={row.id}><div><h3>{view==='days'?row.label.split('-').reverse().join('.'):row.label}</h3><p>{row.completed} durchgeführt · {row.planned} offen/geplant · {row.running} laufend</p><p>{row.cancelled} storniert · {row.noShow} nicht erschienen{row.unknown>0&&` · ${row.unknown} unbekannt`}</p><p>{row.closedShifts} abgeschlossene · {row.openShifts} offene Schicht(en)</p><p>Zeit ohne Pausen: {shiftDuration(row.working)} · Pausen: {shiftDuration(row.paused)}</p></div><strong>{row.km.toLocaleString('de-DE')} km</strong></article>)}</div>{!rows.length&&<p>Keine Fahrten oder Schichten für diese Auswahl.</p>}<div className="shift-buttons"><button className="secondary-button" disabled={!current} onClick={()=>setPage(current-1)}>Vorherige Auslastungsseite</button><span>{rows.length?`${current*50+1}–${Math.min((current+1)*50,rows.length)} von ${rows.length}`:'0 Gruppen'}</span><button className="secondary-button" disabled={current>=maxPage} onClick={()=>setPage(current+1)}>Nächste Auslastungsseite</button></div></>}
 </section>;
}
