begin;
do $$
declare u uuid;org uuid;staff uuid;actor uuid=gen_random_uuid();outsider uuid=gen_random_uuid();entry uuid=gen_random_uuid();customer uuid=gen_random_uuid();inv uuid=gen_random_uuid();st uuid;version timestamptz;day date=(now() at time zone 'Europe/Berlin')::date;reject boolean;dated uuid=gen_random_uuid();refund uuid=gen_random_uuid();
begin
 select b.id,b.organization_id,m.user_id into u,org,staff from public.business_units b join public.memberships m on m.business_unit_id=b.id where b.code='fahrdienst' and b.active and m.active and m.role='admin' limit 1;
 insert into auth.users(id,email) values(actor,'accounting-'||actor||'@example.invalid'),(outsider,'accounting-'||outsider||'@example.invalid');
 insert into public.app_profiles(id,organization_id,email,full_name,active) values(actor,org,'accounting-'||actor||'@example.invalid','Accounting test',true),(outsider,org,'accounting-'||outsider||'@example.invalid','Unauthorized test',true);
 insert into public.memberships(user_id,business_unit_id,role,active) values(actor,u,'office',true);
 perform public.record_accounting_entry(u,actor,entry,'expense',null,null,day,12.50,'card','fuel','Test-Tankstelle','Test tanken','ACCOUNTING-ROLLBACK');
 perform public.record_accounting_entry(u,actor,entry,'expense',null,null,day,12.50,'card','fuel','Test-Tankstelle','Test tanken','ACCOUNTING-ROLLBACK');
 if (select count(*) from public.accounting_entries where id=entry)<>1 then raise exception 'Duplicate retry';end if;
 reject=false;begin perform public.record_accounting_entry(u,actor,entry,'expense',null,null,day,13,'card','fuel','Test-Tankstelle','Test tanken','ACCOUNTING-ROLLBACK');exception when others then reject=true;end;if not reject then raise exception 'Changed retry';end if;
 reject=false;begin perform public.record_accounting_entry(u,outsider,gen_random_uuid(),'expense',null,null,day,12.50,'card','fuel','Test','Test tanken','UNAUTHORIZED');exception when others then reject=true;end;if not reject then raise exception 'Unauthorized actor';end if;
 reject=false;begin perform public.record_accounting_entry(u,actor,gen_random_uuid(),'expense',null,null,day+1,12.50,'card','fuel','Test','Test tanken','FUTURE');exception when others then reject=true;end;if not reject then raise exception 'Future payment';end if;
 reject=false;begin perform public.record_accounting_entry(u,actor,gen_random_uuid(),'expense',null,null,day,12.501,'card','fuel','Test','Test tanken','FRACTION');exception when others then reject=true;end;if not reject then raise exception 'Fractional cents';end if;
 reject=false;begin perform public.record_accounting_entry(u,actor,gen_random_uuid(),'expense',null,null,day,12.50,'card','fuel','Test','Test tanken','accounting-rollback');exception when others then reject=true;end;if not reject then raise exception 'Duplicate expense reference';end if;
 perform set_config('request.jwt.claim.sub',actor::text,true);execute 'set local role authenticated';
 if (select count(*) from public.accounting_entries where id=entry)<>1 then raise exception 'Office cannot read';end if;
 reject=false;begin update public.accounting_entries set amount=100 where id=entry;exception when insufficient_privilege then reject=true;end;if not reject then raise exception 'Direct write granted';end if;
 reject=false;begin perform public.cancel_accounting_entry(u,actor,entry,'Test Korrektur');exception when insufficient_privilege then reject=true;end;if not reject then raise exception 'Browser RPC granted';end if;
 execute 'reset role';perform set_config('request.jwt.claim.sub',outsider::text,true);execute 'set local role authenticated';
 if (select count(*) from public.accounting_entries where id=entry)<>0 then raise exception 'RLS unauthorized read';end if;
 execute 'reset role';execute 'set local role anon';
 reject=false;begin perform count(*) from public.accounting_entries;exception when insufficient_privilege then reject=true;end;if not reject then raise exception 'Anon read granted';end if;execute 'reset role';
 perform public.cancel_accounting_entry(u,actor,entry,'Test doppelt erfasst');perform public.cancel_accounting_entry(u,actor,entry,'Test doppelt erfasst');
 if (select cancelled_at from public.accounting_entries where id=entry) is null then raise exception 'Correction audit missing';end if;
 insert into public.customers(id,organization_id,home_business_unit_id,first_name,last_name) values(customer,org,u,'Accounting','Rollback');
 insert into public.invoices(id,business_unit_id,customer_id,payer_type,payer_name,issue_date,gross_total,net_total,invoice_number,status,paid_at) values(inv,u,customer,'private','Accounting-Test',day-10,100,100,'RE-ACCOUNTING-ROLLBACK','paid',null);
 insert into public.invoice_items(invoice_id,description,quantity,unit_gross,net_total,gross_total) values(inv,'Test Fahrt',1,100,100,100);
 select updated_at into version from public.invoices where id=inv;
 reject=false;begin perform public.record_accounting_entry(u,actor,dated,'payment_date',inv,version-interval '1 second',day,999,'bank',null,null,'Tatsächlicher Eingang','PAY-DATE');exception when others then reject=true;end;if not reject then raise exception 'Stale invoice';end if;
 perform public.record_accounting_entry(u,actor,dated,'payment_date',inv,version,day,999,'bank',null,null,'Tatsächlicher Eingang','PAY-DATE');
 if (select amount from public.accounting_entries where id=dated)<>100 then raise exception 'Client forged amount';end if;
 reject=false;begin perform public.record_accounting_entry(u,actor,gen_random_uuid(),'payment_date',inv,version,day,null,'bank',null,null,'Tatsächlicher Eingang','PAY-DATE-2');exception when others then reject=true;end;if not reject then raise exception 'Duplicate source';end if;
 perform public.cancel_finance_invoice(inv,u,staff,'Test Storno Rollback');select id,updated_at into st,version from public.invoices where reversal_of_id=inv;
 reject=false;begin perform public.record_accounting_entry(u,actor,refund,'refund_date',st,version,day,null,'bank',null,null,'Tatsächliche Rückzahlung','REFUND-DATE');exception when others then reject=true;end;if not reject then raise exception 'Refund without actual confirmation';end if;
 perform public.record_invoice_refund(st,u,staff,'Test Banknachweis Rollback');select updated_at into version from public.invoices where id=st;
 perform public.record_accounting_entry(u,actor,refund,'refund_date',st,version,day,999,'bank',null,null,'Tatsächliche Rückzahlung','REFUND-DATE');
 if (select amount from public.accounting_entries where id=refund)<>100 then raise exception 'Wrong refund amount';end if;
 if (select gross_total from public.invoices where id=inv)<>100 then raise exception 'Original changed';end if;
end;$$;
rollback;
