-- Fully synthetic drivers/users/vehicles/trips; all rows and assertions rolled back.
begin;
do $$
declare u uuid;org uuid;staff uuid;actor uuid=gen_random_uuid();other uuid=gen_random_uuid();driver uuid=gen_random_uuid();driver2 uuid=gen_random_uuid();v uuid=gen_random_uuid();v2 uuid=gen_random_uuid();customer uuid=gen_random_uuid();trip uuid=gen_random_uuid();request uuid=gen_random_uuid();req uuid;shift uuid;version timestamptz;version0 timestamptz;event_time timestamptz;req1 uuid=gen_random_uuid();req2 uuid=gen_random_uuid();req3 uuid=gen_random_uuid();req4 uuid=gen_random_uuid();cancelled uuid=gen_random_uuid();r jsonb;reject boolean;day date=(now() at time zone 'Europe/Berlin')::date;
begin
 select b.id,b.organization_id,m.user_id into u,org,staff from public.business_units b join public.memberships m on m.business_unit_id=b.id join public.app_profiles p on p.id=m.user_id where b.code='fahrdienst' and b.active and m.active and m.role='admin' and p.active limit 1;
 insert into auth.users(id,email) values(actor,'shift-'||actor||'@example.invalid'),(other,'shift-'||other||'@example.invalid');
 insert into public.app_profiles(id,organization_id,email,full_name,active) values(actor,org,'shift-'||actor||'@example.invalid','Shift test',true),(other,org,'shift-'||other||'@example.invalid','Other shift test',true);
 insert into public.drivers(id,organization_id,full_name) values(driver,org,'Schicht-Test Rollback'),(driver2,org,'Schicht-Test 2 Rollback');
 insert into public.driver_business_units(driver_id,business_unit_id) values(driver,u),(driver2,u);
 insert into public.memberships(user_id,business_unit_id,role,driver_id,active) values(actor,u,'driver',driver,true),(other,u,'driver',driver2,true);
 insert into public.vehicles(id,organization_id,registration,mileage) values(v,org,'TEST-'||v,100),(v2,org,'TEST-'||v2,1000);
 insert into public.vehicle_business_units(vehicle_id,business_unit_id) values(v,u),(v2,u);
 perform public.set_office_shift_vehicle(u,staff,driver,v);
 r=public.driver_shift_report(u,actor);if (r->>'assignedVehicleId')::uuid<>v or jsonb_array_length(r->'vehicles')<>1 then raise exception 'Office vehicle not forced';end if;
 reject=false;begin perform public.change_driver_shift(u,staff,request,'start',null,v,100,null);exception when others then reject=true;end;if not reject then raise exception 'Office impersonated driver';end if;
 reject=false;begin perform public.change_driver_shift(u,actor,request,'start',null,v2,1000,null);exception when others then reject=true;end;if not reject then raise exception 'Office assignment bypassed';end if;
 reject=false;begin perform public.change_driver_shift(u,actor,request,'start',null,v,99,null);exception when others then reject=true;end;if not reject then raise exception 'Backwards start';end if;
 reject=false;begin perform public.change_driver_shift(u,actor,request,'start',null,v,null,null);exception when others then reject=true;end;if not reject then raise exception 'Missing mileage';end if;
 insert into public.customers(id,organization_id,home_business_unit_id,first_name,last_name) values(customer,org,u,'Schicht-Test','Rollback');
 insert into public.trips(id,business_unit_id,customer_id,service_date,scheduled_time,trip_type,from_address,to_address,driver_id,vehicle_id,status,customer_name,created_by,updated_by) values(trip,u,customer,day,'12:00','Privatfahrt','Test A','Test B',driver,v,'geplant','Schicht-Test',staff,staff);
 reject=false;begin update public.trips set status='auf_dem_weg',updated_by=actor where id=trip;exception when others then reject=true;end;if not reject then raise exception 'Trip without shift accepted';end if;
 r=public.change_driver_shift(u,actor,request,'start',null,v,101,null);shift=(r->'shift'->>'id')::uuid;version=(r->'shift'->>'updated_at')::timestamptz;
 if r->'shift'->>'state'<>'active' or (select mileage from public.vehicles where id=v)<>101 then raise exception 'Wrong start';end if;
 perform public.change_driver_shift(u,actor,request,'start',null,v,101,null);
 reject=false;begin perform public.change_driver_shift(u,actor,request,'start',null,v,102,null);exception when others then reject=true;end;if not reject then raise exception 'Changed retry';end if;
 reject=false;begin perform public.change_driver_shift(u,actor,gen_random_uuid(),'start',null,v,101,null);exception when others then reject=true;end;if not reject then raise exception 'Duplicate shift';end if;
 reject=false;begin perform public.change_driver_shift(u,other,gen_random_uuid(),'start',null,v,101,null);exception when others then reject=true;end;if not reject then raise exception 'Shared active vehicle';end if;
 reject=false;begin perform public.set_office_shift_vehicle(u,staff,driver,v2);exception when others then reject=true;end;if not reject then raise exception 'Office changed active shift';end if;
 reject=false;begin update public.driver_vehicle_assignments set released_at=clock_timestamp() where driver_id=driver and released_at is null;exception when others then reject=true;end;if not reject then raise exception 'Assignment released while active';end if;

 select updated_at into version0 from public.trips where id=trip;event_time=clock_timestamp()+interval '1 second';
 reject=false;begin perform public.sync_driver_trip_status(u,staff,req1,trip,shift,'geplant','auf_dem_weg',version0,null,event_time);exception when others then reject=true;end;if not reject then raise exception 'Office forged driver event';end if;
 reject=false;begin perform public.sync_driver_trip_status(u,other,req1,trip,shift,'geplant','auf_dem_weg',version0,null,event_time);exception when others then reject=true;end;if not reject then raise exception 'Other driver replayed event';end if;
 reject=false;begin perform public.sync_driver_trip_status(u,actor,req1,trip,shift,'geplant','auf_dem_weg',version0-interval '1 second',null,event_time);exception when others then reject=true;end;if not reject then raise exception 'Stale trip accepted';end if;
 reject=false;begin perform public.sync_driver_trip_status(u,actor,req1,trip,shift,'geplant','auf_dem_weg',version0,null,event_time+interval '1 day');exception when others then reject=true;end;if not reject then raise exception 'Future event accepted';end if;
 reject=false;begin perform public.sync_driver_trip_status(u,actor,req1,trip,shift,'geplant','auf_dem_weg',version0,null,event_time-interval '1 day');exception when others then reject=true;end;if not reject then raise exception 'Before shift accepted';end if;
 reject=false;begin perform public.sync_driver_trip_status(u,actor,req1,trip,shift,'geplant','abgeschlossen',version0,null,event_time);exception when others then reject=true;end;if not reject then raise exception 'Skipped workflow accepted';end if;
 r=public.sync_driver_trip_status(u,actor,req1,trip,shift,'geplant','auf_dem_weg',version0,null,event_time);
 perform public.sync_driver_trip_status(u,actor,req1,trip,shift,'geplant','auf_dem_weg',version0,null,event_time);
 if (select count(*) from public.driver_status_requests where trip_id=trip)<>1 or (select count(*) from public.trip_status_events where trip_id=trip and status='auf_dem_weg')<>1 or (select on_the_way_at from public.trips where id=trip)<>event_time then raise exception 'Duplicated or retimed event';end if;
 reject=false;begin perform public.sync_driver_trip_status(u,actor,req1,trip,shift,'geplant','auf_dem_weg',version0,null,event_time+interval '1 second');exception when others then reject=true;end;if not reject then raise exception 'Changed retry accepted';end if;
 reject=false;begin perform public.sync_driver_trip_status(u,actor,req2,trip,shift,'auf_dem_weg','angekommen',null,gen_random_uuid(),event_time+interval '1 second');exception when others then reject=true;end;if not reject then raise exception 'Missing predecessor accepted';end if;
 r=public.sync_driver_trip_status(u,actor,req2,trip,shift,'auf_dem_weg','angekommen',null,req1,event_time+interval '1 second');
 r=public.sync_driver_trip_status(u,actor,req3,trip,shift,'angekommen','in_fahrt',null,req2,event_time+interval '2 seconds');
 r=public.sync_driver_trip_status(u,actor,req4,trip,shift,'in_fahrt','abgeschlossen',null,req3,event_time+interval '3 seconds');
 perform public.sync_driver_trip_status(u,actor,req4,trip,shift,'in_fahrt','abgeschlossen',null,req3,event_time+interval '3 seconds');
 if (select completed_at from public.trips where id=trip)<>event_time+interval '3 seconds' or (select count(*) from public.driver_status_requests where trip_id=trip)<>4 then raise exception 'Replay completion wrong';end if;
 insert into public.trips(id,business_unit_id,customer_id,service_date,scheduled_time,trip_type,from_address,to_address,driver_id,vehicle_id,status,customer_name,created_by,updated_by) values(cancelled,u,customer,day,'16:00','Privatfahrt','Test A','Test B',driver,v,'geplant','Offline-Test',staff,staff);
 select updated_at into version0 from public.trips where id=cancelled;
 update public.trips set status='storniert',updated_by=staff where id=cancelled;
 reject=false;begin perform public.sync_driver_trip_status(u,actor,gen_random_uuid(),cancelled,shift,'geplant','auf_dem_weg',version0,null,event_time);exception when others then reject=true;end;if not reject then raise exception 'Cancellation overwritten';end if;
 r=public.change_driver_shift(u,actor,gen_random_uuid(),'end',shift,null,121,version);
 perform public.sync_driver_trip_status(u,actor,req4,trip,shift,'in_fahrt','abgeschlossen',null,req3,event_time+interval '3 seconds');
 update public.memberships set active=false where user_id=actor and business_unit_id=u;
 reject=false;begin perform public.sync_driver_trip_status(u,actor,req4,trip,shift,'in_fahrt','abgeschlossen',null,req3,event_time+interval '3 seconds');exception when others then reject=true;end;if not reject then raise exception 'Inactive account replayed';end if;
 if has_table_privilege('authenticated','public.driver_status_requests','INSERT') or has_table_privilege('authenticated','public.driver_status_requests','SELECT') or has_function_privilege('authenticated','public.sync_driver_trip_status(uuid,uuid,uuid,uuid,uuid,text,text,timestamptz,uuid,timestamptz)','EXECUTE') then raise exception 'Browser privileged access';end if;
end;$$;
rollback;
