-- Fully synthetic drivers/users/vehicles/trips; all rows and assertions rolled back.
begin;
do $$
declare u uuid;org uuid;staff uuid;actor uuid=gen_random_uuid();other uuid=gen_random_uuid();driver uuid=gen_random_uuid();driver2 uuid=gen_random_uuid();v uuid=gen_random_uuid();v2 uuid=gen_random_uuid();customer uuid=gen_random_uuid();trip uuid=gen_random_uuid();request uuid=gen_random_uuid();req uuid;shift uuid;version timestamptz;r jsonb;reject boolean;day date=(now() at time zone 'Europe/Berlin')::date;
begin
 select b.id,b.organization_id,m.user_id into u,org,staff from public.business_units b join public.memberships m on m.business_unit_id=b.id join public.app_profiles p on p.id=m.user_id where b.code='fahrdienst' and b.active and m.active and m.role='admin' and p.active limit 1;
 insert into auth.users(id,email) values(actor,'shift-'||actor||'@example.invalid'),(other,'shift-'||other||'@example.invalid');
 insert into public.app_profiles(id,organization_id,email,full_name,active) values(actor,org,'shift-'||actor||'@example.invalid','Shift test',true),(other,org,'shift-'||other||'@example.invalid','Other shift test',true);
 insert into public.drivers(id,organization_id,full_name) values(driver,org,'Schicht-Test Rollback'),(driver2,org,'Schicht-Test 2 Rollback');
 insert into public.driver_business_units(driver_id,business_unit_id) values(driver,u),(driver2,u);
 insert into public.memberships(user_id,business_unit_id,role,driver_id,active) values(actor,u,'driver',driver,true),(other,u,'driver',driver2,true);
 insert into public.vehicles(id,organization_id,registration,mileage) values(v,org,'TEST-'||v,100),(v2,org,'TEST-'||v2,1000);
 insert into public.vehicle_business_units(vehicle_id,business_unit_id) values(v,u),(v2,u);
 perform public.set_office_shift_vehicle(u,staff,driver,v);
 r=public.driver_shift_report(u,actor);if (r->>'assignedVehicleId')::uuid<>v or jsonb_array_length(r->'vehicles')<>1 then raise exception 'Office vehicle not forced';end if;
 reject=false;begin perform public.change_driver_shift(u,staff,request,'start',null,v,100,null);exception when others then reject=true;end;if not reject then raise exception 'Office impersonated driver';end if;
 reject=false;begin perform public.change_driver_shift(u,actor,request,'start',null,v2,1000,null);exception when others then reject=true;end;if not reject then raise exception 'Office assignment bypassed';end if;
 reject=false;begin perform public.change_driver_shift(u,actor,request,'start',null,v,99,null);exception when others then reject=true;end;if not reject then raise exception 'Backwards start';end if;
 reject=false;begin perform public.change_driver_shift(u,actor,request,'start',null,v,null,null);exception when others then reject=true;end;if not reject then raise exception 'Missing mileage';end if;
 insert into public.customers(id,organization_id,home_business_unit_id,first_name,last_name) values(customer,org,u,'Schicht-Test','Rollback');
 insert into public.trips(id,business_unit_id,customer_id,service_date,scheduled_time,trip_type,from_address,to_address,driver_id,vehicle_id,status,customer_name,created_by,updated_by) values(trip,u,customer,day,'12:00','Privatfahrt','Test A','Test B',driver,v,'geplant','Schicht-Test',staff,staff);
 reject=false;begin update public.trips set status='auf_dem_weg',updated_by=actor where id=trip;exception when others then reject=true;end;if not reject then raise exception 'Trip without shift accepted';end if;
 r=public.change_driver_shift(u,actor,request,'start',null,v,101,null);shift=(r->'shift'->>'id')::uuid;version=(r->'shift'->>'updated_at')::timestamptz;
 if r->'shift'->>'state'<>'active' or (select mileage from public.vehicles where id=v)<>101 then raise exception 'Wrong start';end if;
 perform public.change_driver_shift(u,actor,request,'start',null,v,101,null);
 reject=false;begin perform public.change_driver_shift(u,actor,request,'start',null,v,102,null);exception when others then reject=true;end;if not reject then raise exception 'Changed retry';end if;
 reject=false;begin perform public.change_driver_shift(u,actor,gen_random_uuid(),'start',null,v,101,null);exception when others then reject=true;end;if not reject then raise exception 'Duplicate shift';end if;
 reject=false;begin perform public.change_driver_shift(u,other,gen_random_uuid(),'start',null,v,101,null);exception when others then reject=true;end;if not reject then raise exception 'Shared active vehicle';end if;
 reject=false;begin perform public.set_office_shift_vehicle(u,staff,driver,v2);exception when others then reject=true;end;if not reject then raise exception 'Office changed active shift';end if;
 reject=false;begin update public.driver_vehicle_assignments set released_at=clock_timestamp() where driver_id=driver and released_at is null;exception when others then reject=true;end;if not reject then raise exception 'Assignment released while active';end if;
 req=gen_random_uuid();r=public.change_driver_shift(u,actor,req,'pause',shift,null,null,version);if r->'shift'->>'state'<>'paused' then raise exception 'Pause not saved';end if;
 perform public.change_driver_shift(u,actor,req,'pause',shift,null,null,version);
 if (select count(*) from public.driver_shift_breaks where shift_id=shift)<>1 then raise exception 'Duplicate break';end if;
 reject=false;begin perform public.change_driver_shift(u,actor,gen_random_uuid(),'resume',shift,null,null,version);exception when others then reject=true;end;if not reject then raise exception 'Stale version resumed';end if;
 reject=false;begin update public.trips set status='auf_dem_weg',updated_by=actor where id=trip;exception when others then reject=true;end;if not reject then raise exception 'Trip during pause';end if;
 version=(r->'shift'->>'updated_at')::timestamptz;r=public.change_driver_shift(u,actor,gen_random_uuid(),'resume',shift,null,null,version);version=(r->'shift'->>'updated_at')::timestamptz;
 update public.trips set status='auf_dem_weg',updated_by=actor where id=trip;
 reject=false;begin perform public.change_driver_shift(u,actor,gen_random_uuid(),'pause',shift,null,null,version);exception when others then reject=true;end;if not reject then raise exception 'Paused active trip';end if;
 reject=false;begin perform public.change_driver_shift(u,actor,gen_random_uuid(),'end',shift,null,120,version);exception when others then reject=true;end;if not reject then raise exception 'Ended active trip';end if;
 update public.trips set status='storniert',updated_by=staff where id=trip;
 reject=false;begin perform public.change_driver_shift(u,actor,gen_random_uuid(),'end',shift,null,100,version);exception when others then reject=true;end;if not reject then raise exception 'Backwards end';end if;
 r=public.change_driver_shift(u,actor,gen_random_uuid(),'pause',shift,null,null,version);version=(r->'shift'->>'updated_at')::timestamptz;
 req=gen_random_uuid();r=public.change_driver_shift(u,actor,req,'end',shift,null,121,version);
 if r->'shift'<>'null'::jsonb or (r->'lastShift'->>'end_mileage')::integer<>121 or (select mileage from public.vehicles where id=v)<>121 then raise exception 'End not persisted';end if;
 if (select count(*) from public.driver_shift_breaks where shift_id=shift and ended_at is null)<>0 then raise exception 'End left open break';end if;
 if not exists(select 1 from public.driver_vehicle_assignments where driver_id=driver and released_at is null) then raise exception 'Permanent office assignment removed';end if;
 perform public.change_driver_shift(u,actor,req,'end',shift,null,121,version);
 perform public.set_office_shift_vehicle(u,staff,driver,null);
 r=public.change_driver_shift(u,actor,gen_random_uuid(),'start',null,v2,1001,null);shift=(r->'shift'->>'id')::uuid;version=(r->'shift'->>'updated_at')::timestamptz;
 if r->'shift'->>'temporary_assignment_id' is null then raise exception 'Spontaneous assignment not recorded';end if;
 r=public.change_driver_shift(u,actor,gen_random_uuid(),'end',shift,null,1011,version);
 if exists(select 1 from public.driver_vehicle_assignments where driver_id=driver and released_at is null) then raise exception 'Temporary assignment survived shift';end if;
 r=public.staff_shift_report(u,staff,date_trunc('month',day)::date,driver,0);
 if (r->'totals'->>'closed_count')::integer<>2 or (r->'totals'->>'km')::integer<>30 or jsonb_array_length(r->'rows')<>2 then raise exception 'Report totals incorrect';end if;
 reject=false;begin perform public.staff_shift_report(u,actor,date_trunc('month',day)::date,null,0);exception when others then reject=true;end;if not reject then raise exception 'Driver read staff report';end if;
 perform public.set_office_shift_vehicle(u,staff,driver,v);
 update public.drivers set active=false where id=driver;
 perform public.set_office_shift_vehicle(u,staff,driver,v);
 reject=false;begin perform public.set_office_shift_vehicle(u,staff,driver,v2);exception when others then reject=true;end;if not reject then raise exception 'Inactive driver received new vehicle';end if;
 perform public.set_office_shift_vehicle(u,staff,driver,null);
 if exists(select 1 from public.driver_vehicle_assignments where driver_id=driver and released_at is null) then raise exception 'Inactive vehicle release failed';end if;
 update public.drivers set active=true where id=driver;
 r=public.change_driver_shift(u,other,gen_random_uuid(),'start',null,v,121,null);version=(r->'shift'->>'updated_at')::timestamptz;
 perform public.change_driver_shift(u,other,gen_random_uuid(),'end',(r->'shift'->>'id')::uuid,null,131,version);
 perform set_config('request.jwt.claim.sub',actor::text,true);perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated')::text,true);
 execute 'set local role authenticated';
 if (select count(*) from public.driver_shifts where driver_id=driver)<>2 or exists(select 1 from public.driver_shifts where driver_id=driver2) then raise exception 'Driver RLS leaked another driver';end if;
 execute 'set local role postgres';
 perform set_config('request.jwt.claim.sub',other::text,true);perform set_config('request.jwt.claims',jsonb_build_object('sub',other,'role','authenticated')::text,true);
 execute 'set local role authenticated';
 if (select count(*) from public.driver_shifts where driver_id=driver2)<>1 or exists(select 1 from public.driver_shift_breaks) or exists(select 1 from public.driver_shift_events where actor_id=actor) then raise exception 'Break/event RLS leaked another driver';end if;
 execute 'set local role postgres';
 if has_table_privilege('authenticated','public.driver_shifts','INSERT') or has_function_privilege('authenticated','public.change_driver_shift(uuid,uuid,uuid,text,uuid,uuid,numeric,timestamptz)','EXECUTE') then raise exception 'Browser has privileged writes';end if;
end;$$;
rollback;
