-- Synthetic fixtures, full rollback; no real patient payments are changed.
begin;
do $$
declare u uuid;actor uuid;org uuid;insurer uuid;customer uuid=gen_random_uuid();trip1 uuid=gen_random_uuid();trip2 uuid=gen_random_uuid();invoice1 uuid=gen_random_uuid();invoice2 uuid=gen_random_uuid();own_invoice uuid=gen_random_uuid();case1 uuid;case2 uuid;run uuid;request1 uuid=gen_random_uuid();request2 uuid=gen_random_uuid();report jsonb;entries jsonb;initial_entries jsonb;r jsonb;rejected boolean;reversal uuid;
begin
 select b.id,b.organization_id,m.user_id into u,org,actor from public.business_units b join public.memberships m on m.business_unit_id=b.id join public.app_profiles p on p.id=m.user_id where b.code='fahrdienst' and b.active and m.active and m.role in ('admin','office') and p.active limit 1;
 select id into insurer from public.health_insurers where organization_id=org limit 1;
 insert into public.customers(id,organization_id,home_business_unit_id,first_name,last_name) values(customer,org,u,'Payment-Test','Rollback');
 insert into public.trips(id,business_unit_id,customer_id,service_date,scheduled_time,trip_type,from_address,to_address,status,direction) values(trip1,u,customer,current_date,'09:00','Dialyse','A','B','abgeschlossen','outbound'),(trip2,u,customer,current_date,'12:00','Dialyse','B','A','abgeschlossen','return');
 insert into public.invoices(id,business_unit_id,customer_id,insurer_id,payer_type,payer_name,customer_name,service_date,gross_total,net_total,invoice_number,issuer_snapshot) values(invoice1,u,customer,insurer,'insurer','Testkasse','Payment-Test',current_date,110,110,'RE-PAY-1','{"company_name":"Testunternehmen"}'),(invoice2,u,customer,insurer,'insurer','Testkasse','Payment-Test',current_date,115,115,'RE-PAY-2','{"company_name":"Testunternehmen"}');
 insert into public.invoices(id,business_unit_id,customer_id,payer_type,payer_name,gross_total,net_total,invoice_number) values(own_invoice,u,customer,'private','Payment-Test',10,10,'RE-OWN-PAY-TEST');
 insert into public.invoice_items(invoice_id,trip_id,description,unit_gross,net_total,gross_total) values(invoice1,trip1,'Test Hin',110,110,110),(invoice2,trip2,'Test Rück',115,115,115);
 select id into case1 from public.trip_billing_cases where trip_id=trip1;select id into case2 from public.trip_billing_cases where trip_id=trip2;
 if case1 is null then insert into public.trip_billing_cases(business_unit_id,trip_id,customer_id) values(u,trip1,customer) returning id into case1;end if;
 if case2 is null then insert into public.trip_billing_cases(business_unit_id,trip_id,customer_id) values(u,trip2,customer) returning id into case2;end if;
 update public.trip_billing_cases set insurer_id=insurer,payer_type='insurer',billing_status='invoiced',invoice_id=case when id=case1 then invoice1 else invoice2 end,copay_rule_version=1,direction_count=1,gross_amount=120,own_share_amount=case when id=case1 then 10 else 5 end,insurer_amount=case when id=case1 then 110 else 115 end where id in(case1,case2);
 select jsonb_agg(jsonb_build_object('id',c.id,'updatedAt',c.updated_at,'invoice',to_jsonb(i),'lines',(select jsonb_agg(to_jsonb(l) order by l.sort_order,l.id) from public.invoice_items l where invoice_id=i.id)) order by c.id) into entries from public.trip_billing_cases c join public.invoices i on i.id=c.invoice_id where c.id in(case1,case2);
 r=public.create_billing_submission(u,actor,entries);run=(r->>'id')::uuid;
 rejected=false;begin perform public.record_insurer_payment(u,actor,run,request1,current_date,60,'BANK-TEST-1','', '[]');exception when others then rejected=true;end;if not rejected then raise exception 'Prepared run accepted payment';end if;
 update public.billing_submissions set status='web_entered',web_date=current_date,web_recorded_at=now(),web_recorded_by=actor where id=run;
 report=public.insurer_payment_report(u,actor,run);
 select jsonb_agg(jsonb_build_object('invoiceId',x->>'invoiceId','amount',case when (x->>'invoiceId')::uuid=invoice1 then 40 else 15 end,'version',x->>'version') order by x->>'invoiceId') into entries from jsonb_array_elements(report->'rows') x;initial_entries=entries;
 rejected=false;begin perform public.record_insurer_payment(u,gen_random_uuid(),run,request1,current_date,60,'BANK-TEST-1','',entries);exception when others then rejected=true;end;if not rejected then raise exception 'Unauthorized actor accepted';end if;
 rejected=false;begin perform public.record_insurer_payment(u,actor,run,request1,current_date,50,'BANK-TEST-1','',entries);exception when others then rejected=true;end;if not rejected then raise exception 'Allocation exceeds bank receipt';end if;
 rejected=false;begin perform public.record_insurer_payment(u,actor,run,request1,current_date+1,60,'BANK-TEST-1','',entries);exception when others then rejected=true;end;if not rejected then raise exception 'Future payment accepted';end if;
 rejected=false;begin perform public.record_insurer_payment(u,actor,run,request1,current_date,60,'BANK-TEST-1','',jsonb_set(entries,'{0,invoiceId}',to_jsonb(own_invoice::text)));exception when others then rejected=true;end;if not rejected then raise exception 'Patient invoice entered in insurer register';end if;
 perform public.record_insurer_payment(u,actor,run,request1,current_date,60,'BANK-TEST-1','5 EUR noch nicht zugeordnet',entries);
 report=public.insurer_payment_report(u,actor,run);
 if (report->>'receivedCents')::integer<>6000 or (report->>'allocatedCents')::integer<>5500 or (report->>'unallocatedCents')::integer<>500 or (report->>'openCents')::integer<>17000 then raise exception 'Incorrect partial totals: %',report;end if;
 if exists(select 1 from public.invoices where id in(invoice1,invoice2) and status<>'open') then raise exception 'Partial invoice marked paid';end if;
 if (select credited_amount from public.insurer_invoice_balances where id=invoice1)<>40 then raise exception 'Invoice balance view wrong';end if;
 r=public.record_insurer_payment(u,actor,run,request1,current_date,60,'BANK-TEST-1','5 EUR noch nicht zugeordnet',initial_entries);if not (r->>'alreadyRecorded')::boolean then raise exception 'Retry not idempotent';end if;
 if (select count(*) from public.insurer_payment_entries where submission_id=run)<>1 then raise exception 'Duplicate payment recorded';end if;
 rejected=false;begin perform public.record_insurer_payment(u,actor,run,gen_random_uuid(),current_date,60,'bank-test-1','',entries);exception when others then rejected=true;end;if not rejected then raise exception 'Duplicate bank reference accepted';end if;
 rejected=false;begin perform public.record_insurer_payment(u,actor,run,gen_random_uuid(),current_date,60,'BANK-STALE','',initial_entries);exception when others then rejected=true;end;if not rejected then raise exception 'Stale balances accepted';end if;
 rejected=false;begin perform public.mark_finance_invoice_paid(invoice1,u,actor);exception when others then rejected=true;end;if not rejected then raise exception 'Old paid action bypassed partial ledger';end if;
 select jsonb_agg(jsonb_build_object('invoiceId',x->>'invoiceId','amount',(x->>'openCents')::numeric/100,'version',x->>'version') order by x->>'invoiceId') into entries from jsonb_array_elements(report->'rows') x;
 perform public.record_insurer_payment(u,actor,run,request2,current_date,170,'BANK-TEST-2','',entries);
 if exists(select 1 from public.invoices where id in(invoice1,invoice2) and status<>'paid') then raise exception 'Fully balanced invoice not paid';end if;
 if exists(select 1 from public.trip_billing_cases where id in(case1,case2) and own_share_paid) or (select status from public.invoices where id=own_invoice)<>'open' then raise exception 'Own shares affected by insurer payment';end if;
 perform public.cancel_insurer_payment(u,actor,request2,'Falsche Zuordnung testen');
 if exists(select 1 from public.invoices where id in(invoice1,invoice2) and (status<>'open' or paid_at is not null)) then raise exception 'Correction did not reopen invoices';end if;
 report=public.insurer_payment_report(u,actor,run);if (report->>'openCents')::integer<>17000 or (report->>'receivedCents')::integer<>6000 then raise exception 'Correction lost original payment';end if;
 perform public.cancel_insurer_payment(u,actor,request2,'Wiederholte Korrektur');
 r=public.cancel_finance_invoice(invoice1,u,actor,'Teilbezahlte Rechnung korrigieren');reversal=(r->>'id')::uuid;
 if (select refund_amount from public.invoices where id=reversal)<>40 or (select gross_total from public.invoices where id=reversal)<>-110 or (select refund_status from public.invoices where id=reversal)<>'due' then raise exception 'Wrong partial refund amount';end if;
 report=public.insurer_payment_report(u,actor,run);if (report->>'refundDueCents')::integer<>4000 or (report->>'openCents')::integer<>10000 then raise exception 'Refund/outstanding totals incorrect';end if;
 rejected=false;begin perform public.cancel_insurer_payment(u,actor,request1,'Cannot erase refund source');exception when others then rejected=true;end;if not rejected then raise exception 'Payment erased after invoice cancellation';end if;
 perform public.record_invoice_refund(reversal,u,actor,'Tatsächlich rückgezahlt: TEST');
 report=public.insurer_payment_report(u,actor,run);if (report->>'refundDueCents')::integer<>0 then raise exception 'Actual refund not reflected';end if;
end;$$;
rollback;
