-- Synthetic financial fixtures; all changes rolled back, including reminder history.
begin;
do $$
declare u uuid;org uuid;actor uuid;customer uuid=gen_random_uuid();inv uuid=gen_random_uuid();request uuid=gen_random_uuid();r jsonb;expected jsonb;reject boolean;day date=(now() at time zone 'Europe/Berlin')::date;message text='Bitte den offenen Betrag bis zur Zahlungsfrist überweisen.';
begin
 select b.id,b.organization_id,m.user_id into u,org,actor from public.business_units b join public.memberships m on m.business_unit_id=b.id join public.app_profiles p on p.id=m.user_id where b.code='fahrdienst' and b.active and m.active and m.role in ('admin','office') and p.active limit 1;
 insert into public.customers(id,organization_id,home_business_unit_id,first_name,last_name) values(customer,org,u,'Reminder-Test','Rollback');
 insert into public.invoices(id,business_unit_id,customer_id,payer_type,payer_name,payer_address,customer_name,service_date,issue_date,due_date,gross_total,net_total,invoice_number,own_share_month,issuer_snapshot) values(inv,u,customer,'private','Testpatient','Teststraße 1, 12345 Teststadt','Testpatient',day-30,day-20,day-1,30,30,'RE-REMINDER-ROLLBACK',date_trunc('month',day)::date,'{"company_name":"Testunternehmen","iban":"DE123"}');
 select to_jsonb(i) into expected from public.invoices i where id=inv;
 reject=false;begin perform public.prepare_patient_reminder(u,gen_random_uuid(),request,inv,expected,day+14,message);exception when others then reject=true;end;if not reject then raise exception 'Unauthorized accepted';end if;
 reject=false;begin perform public.prepare_patient_reminder(u,actor,request,inv,expected,day,message);exception when others then reject=true;end;if not reject then raise exception 'Expired deadline accepted';end if;
 reject=false;begin perform public.prepare_patient_reminder(u,actor,request,inv,jsonb_set(expected,'{gross_total}','1'),day+14,message);exception when others then reject=true;end;if not reject then raise exception 'Forged snapshot accepted';end if;
 update public.invoices set due_date=day where id=inv;select to_jsonb(i) into expected from public.invoices i where id=inv;
 reject=false;begin perform public.prepare_patient_reminder(u,actor,request,inv,expected,day+14,message);exception when others then reject=true;end;if not reject then raise exception 'Due today accepted';end if;
 update public.invoices set due_date=null where id=inv;select to_jsonb(i) into expected from public.invoices i where id=inv;
 reject=false;begin perform public.prepare_patient_reminder(u,actor,request,inv,expected,day+14,message);exception when others then reject=true;end;if not reject then raise exception 'Missing due date accepted';end if;
 update public.invoices set due_date=day-1 where id=inv;select to_jsonb(i) into expected from public.invoices i where id=inv;
 r=public.prepare_patient_reminder(u,actor,request,inv,expected,day+14,message);
 if r->>'status'<>'draft' or (r->'invoice_snapshot'->>'gross_total')::numeric<>30 or (select status from public.invoices where id=inv)<>'open' then raise exception 'Wrong draft or altered invoice';end if;
 perform public.prepare_patient_reminder(u,actor,request,inv,expected,day+14,message);
 if(select count(*) from public.patient_payment_reminders where invoice_id=inv)<>1 then raise exception 'Duplicate retry';end if;
 reject=false;begin perform public.prepare_patient_reminder(u,actor,gen_random_uuid(),inv,expected,day+14,message);exception when others then reject=true;end;if not reject then raise exception 'Second draft accepted';end if;
 perform public.inspect_patient_reminder(u,actor,request);
 update public.invoices set status='paid' where id=inv;
 reject=false;begin perform public.inspect_patient_reminder(u,actor,request);exception when others then reject=true;end;if not reject then raise exception 'Paid draft preview accepted';end if;
 reject=false;begin perform public.update_patient_reminder(u,actor,request,'sent',day,'post','Teststraße 1','','');exception when others then reject=true;end;if not reject then raise exception 'Paid draft sent accepted';end if;
 update public.invoices set status='open' where id=inv;
 reject=false;begin perform public.update_patient_reminder(u,actor,request,'sent',day+1,'post','Teststraße 1','','');exception when others then reject=true;end;if not reject then raise exception 'Future send accepted';end if;
 r=public.update_patient_reminder(u,actor,request,'sent',day,'post','Teststraße 1','Beleg A','');
 if r->>'status'<>'sent' or (select status from public.invoices where id=inv)<>'open' then raise exception 'Send changed payment';end if;
 perform public.update_patient_reminder(u,actor,request,'sent',day,'post','Teststraße 1','Beleg A','');
 reject=false;begin perform public.update_patient_reminder(u,actor,request,'sent',day,'email','other@test.invalid','','');exception when others then reject=true;end;if not reject then raise exception 'Changed send retry accepted';end if;
 reject=false;begin perform public.update_patient_reminder(u,actor,request,'void',null,null,null,'','Already sent');exception when others then reject=true;end;if not reject then raise exception 'Sent history erased';end if;
 reject=false;begin perform public.prepare_patient_reminder(u,actor,gen_random_uuid(),inv,expected,day+14,message);exception when others then reject=true;end;if not reject then raise exception 'Active payment deadline ignored';end if;
 update public.patient_payment_reminders set letter_date=day-20,deadline=day-1 where id=request;
 request=gen_random_uuid();r=public.prepare_patient_reminder(u,actor,request,inv,expected,day+14,message,2,(public.patient_reminder_config(u,actor)->>'version')::integer);
 if(r->>'reminder_number')::integer<>2 then raise exception 'Wrong follow-up number';end if;
 update public.invoices set status='cancelled' where id=inv;
 reject=false;begin perform public.update_patient_reminder(u,actor,request,'sent',day,'post','Teststraße 1','','');exception when others then reject=true;end;if not reject then raise exception 'Cancelled draft send accepted';end if;
 reject=false;begin perform public.update_patient_reminder(u,actor,request,'void',null,null,null,'','');exception when others then reject=true;end;if not reject then raise exception 'Void without reason accepted';end if;
 r=public.update_patient_reminder(u,actor,request,'void',null,null,null,'','Rechnung inzwischen storniert');
 if r->>'status'<>'void' then raise exception 'Void failed';end if;
 perform public.update_patient_reminder(u,actor,request,'void',null,null,null,'','Rechnung inzwischen storniert');
 update public.invoices set status='open' where id=inv;
 request=gen_random_uuid();r=public.prepare_patient_reminder(u,actor,request,inv,expected,day+14,message,2,(public.patient_reminder_config(u,actor)->>'version')::integer);
 update public.patient_payment_reminders set letter_date=day-20,deadline=day-1 where id=request;
 reject=false;begin perform public.inspect_patient_reminder(u,actor,request);exception when others then reject=true;end;if not reject then raise exception 'Expired draft preview accepted';end if;
 reject=false;begin perform public.update_patient_reminder(u,actor,request,'sent',day,'post','Teststraße 1','','');exception when others then reject=true;end;if not reject then raise exception 'Send after deadline accepted';end if;
 r=public.update_patient_reminder(u,actor,request,'sent',day-2,'post','Teststraße 1','Nachträglich dokumentierter Versand','');
 if r->>'status'<>'sent' or (r->>'sent_date')::date<>day-2 then raise exception 'Actual historical send lost';end if;
 if (select count(*) from public.invoices where id=inv)<>1 or (select count(*) from public.patient_payment_reminders where invoice_id=inv)<>3 then raise exception 'Financial side effect or missing audit';end if;
 if has_table_privilege('authenticated','public.patient_payment_reminders','INSERT') or has_function_privilege('authenticated','public.prepare_patient_reminder(uuid,uuid,uuid,uuid,jsonb,date,text)','EXECUTE') then raise exception 'Browser may write ledger';end if;
end;$$;
rollback;
