-- Synthetic monthly and single patient invoices; no real payment survives ROLLBACK.
begin;
do $$
declare u uuid;org uuid;actor uuid;customer uuid=gen_random_uuid();trip1 uuid=gen_random_uuid();trip2 uuid=gen_random_uuid();case1 uuid;case2 uuid;inv uuid=gen_random_uuid();kasse uuid=gen_random_uuid();request1 uuid=gen_random_uuid();request2 uuid=gen_random_uuid();reminder uuid=gen_random_uuid();report jsonb;version text;expected jsonb;r jsonb;rejected boolean;storno uuid;day date=(now() at time zone 'Europe/Berlin')::date;single uuid=gen_random_uuid();
begin
 select b.id,b.organization_id,m.user_id into u,org,actor from public.business_units b join public.memberships m on m.business_unit_id=b.id join public.app_profiles p on p.id=m.user_id where b.code='fahrdienst' and b.active and m.active and m.role in ('admin','office') and p.active limit 1;
 insert into public.customers(id,organization_id,home_business_unit_id,first_name,last_name) values(customer,org,u,'Own-Payment-Test','Rollback');
 insert into public.trips(id,business_unit_id,customer_id,service_date,scheduled_time,trip_type,from_address,to_address,status) values(trip1,u,customer,day-30,'09:00','Dialyse','A','B','abgeschlossen'),(trip2,u,customer,day-29,'10:00','Dialyse','B','A','abgeschlossen');
 select id into case1 from public.trip_billing_cases where trip_id=trip1;select id into case2 from public.trip_billing_cases where trip_id=trip2;
 if case1 is null then insert into public.trip_billing_cases(business_unit_id,trip_id,customer_id) values(u,trip1,customer) returning id into case1;end if;
 if case2 is null then insert into public.trip_billing_cases(business_unit_id,trip_id,customer_id) values(u,trip2,customer) returning id into case2;end if;
 insert into public.invoices(id,business_unit_id,customer_id,payer_type,payer_name,payer_address,customer_name,issue_date,service_date,due_date,gross_total,net_total,invoice_number,own_share_month,issuer_snapshot) values(inv,u,customer,'private','Testpatient','Teststraße 1','Testpatient',day-20,day-30,day-1,30,30,'RE-OWN-PAY-MONTH',date_trunc('month',day-30)::date,'{"company_name":"Testbetrieb","iban":"DE123"}');
 insert into public.invoices(id,business_unit_id,customer_id,payer_type,payer_name,issue_date,gross_total,net_total,invoice_number) values(kasse,u,customer,'insurer','Testkasse',day-20,110,110,'RE-KASSE-UNCHANGED');
 insert into public.invoice_items(invoice_id,trip_id,description,unit_gross,gross_total,net_total) values(inv,trip1,'Eigenanteil Hin',10,10,10),(inv,trip2,'Eigenanteil Rück',20,20,20);
 update public.trip_billing_cases set own_share_invoice_id=inv,invoice_id=kasse,payer_type='insurer',billing_status='invoiced',own_share_paid=false,own_share_amount=case when id=case1 then 10 else 20 end where id in(case1,case2);
 select to_jsonb(i) into expected from public.invoices i where id=inv;
 perform public.prepare_patient_reminder(u,actor,reminder,inv,expected,day+14,'Bitte den offenen Betrag überweisen.');
 report=public.patient_payment_report(u,actor,inv);version=report->>'version';
 rejected=false;begin perform public.record_patient_payment(u,gen_random_uuid(),inv,request1,version,day,10,'bank','TEST-PAT-1','');exception when others then rejected=true;end;if not rejected then raise exception 'Unauthorized payment accepted';end if;
 rejected=false;begin perform public.record_patient_payment(u,actor,inv,request1,version,day+1,10,'bank','TEST-PAT-1','');exception when others then rejected=true;end;if not rejected then raise exception 'Future payment accepted';end if;
 rejected=false;begin perform public.record_patient_payment(u,actor,inv,request1,version,day,10.001,'bank','TEST-PAT-1','');exception when others then rejected=true;end;if not rejected then raise exception 'Fractional cents accepted';end if;
 perform public.record_patient_payment(u,actor,inv,request1,version,day,10,'bank','TEST-PAT-1','Tatsächlicher Eingang');
 r=public.record_patient_payment(u,actor,inv,request1,version,day,10,'bank','TEST-PAT-1','Tatsächlicher Eingang');if not(r->>'alreadyRecorded')::boolean then raise exception 'Retry duplicated';end if;
 report=public.patient_payment_report(u,actor,inv);
 if(report->>'creditedCents')::integer<>1000 or(report->>'openCents')::integer<>2000 or(report->'invoice'->>'status')<>'open' then raise exception 'Partial balance incorrect';end if;
 if exists(select 1 from public.trip_billing_cases where id in(case1,case2) and own_share_paid) then raise exception 'Partial payment falsely settled cases';end if;
 if(select open_amount from public.patient_invoice_balances where id=inv)<>20 then raise exception 'RLS balance view wrong';end if;
 rejected=false;begin perform public.inspect_patient_reminder(u,actor,reminder);exception when others then rejected=true;end;if not rejected then raise exception 'Reminder ignored partial payment';end if;
 rejected=false;begin perform public.update_patient_reminder(u,actor,reminder,'sent',day,'post','Teststraße 1','','');exception when others then rejected=true;end;if not rejected then raise exception 'Old full-amount reminder sent';end if;
 perform public.update_patient_reminder(u,actor,reminder,'void',null,null,null,'','Restbetrag hat sich geändert');
 rejected=false;begin perform public.record_patient_payment(u,actor,inv,gen_random_uuid(),version,day,10,'bank','STALE','');exception when others then rejected=true;end;if not rejected then raise exception 'Stale state accepted';end if;
 rejected=false;begin perform public.record_patient_payment(u,actor,inv,gen_random_uuid(),report->>'version',day,21,'bank','TOO-MUCH','');exception when others then rejected=true;end;if not rejected then raise exception 'Overpayment accepted';end if;
 rejected=false;begin perform public.record_patient_payment(u,actor,inv,gen_random_uuid(),report->>'version',day,1,'bank','test-pat-1','');exception when others then rejected=true;end;if not rejected then raise exception 'Duplicate reference accepted';end if;
 rejected=false;begin perform public.mark_finance_invoice_paid(inv,u,actor);exception when others then rejected=true;end;if not rejected then raise exception 'Old paid action skipped remainder';end if;
 select to_jsonb(i) into expected from public.invoices i where id=inv;reminder=gen_random_uuid();r=public.prepare_patient_reminder(u,actor,reminder,inv,expected,day+14,'Bitte den offenen Restbetrag überweisen.');
 if(r->>'open_amount')::numeric<>20 or(r->>'credited_amount')::numeric<>10 or(r->'invoice_snapshot'->>'gross_total')::numeric<>30 then raise exception 'Reminder snapshot changed original or ignored payments';end if;
 perform public.inspect_patient_reminder(u,actor,reminder);perform public.update_patient_reminder(u,actor,reminder,'sent',day,'post','Teststraße 1','','');
 perform public.record_patient_payment(u,actor,inv,request2,report->>'version',day,20,'card','TEST-PAT-2','');
 if(select status from public.invoices where id=inv)<>'paid' or exists(select 1 from public.trip_billing_cases where id in(case1,case2) and not own_share_paid) then raise exception 'Full monthly payment not atomic';end if;
 if(select status from public.invoices where id=kasse)<>'open' then raise exception 'Insurer falsely paid';end if;
 perform public.cancel_patient_payment(u,actor,request2,'Falscher Zahlungseintrag');perform public.cancel_patient_payment(u,actor,request2,'Falscher Zahlungseintrag');
 if(select status from public.invoices where id=inv)<>'open' or exists(select 1 from public.trip_billing_cases where id in(case1,case2) and own_share_paid) then raise exception 'Correction did not reopen all cases';end if;
 if(select open_amount from public.patient_payment_reminders where id=reminder)<>20 then raise exception 'Sent archive changed';end if;
 r=public.cancel_finance_invoice(inv,u,actor,'Rechnung nach Teilzahlung korrigieren');storno=(r->>'id')::uuid;
 if(select refund_amount from public.invoices where id=storno)<>10 or(select gross_total from public.invoices where id=storno)<>-30 then raise exception 'Partial refund wrong';end if;
 if exists(select 1 from public.trip_billing_cases where id in(case1,case2) and own_share_invoice_id is distinct from inv) then raise exception 'Cases released before real refund';end if;
 rejected=false;begin perform public.cancel_patient_payment(u,actor,request1,'Cannot undo real paid cancellation');exception when others then rejected=true;end;if not rejected then raise exception 'Cancelled invoice payment erased';end if;
 perform public.record_invoice_refund(storno,u,actor,'Tatsächliche Rückzahlung TEST-REFUND');
 if exists(select 1 from public.trip_billing_cases where id in(case1,case2) and (own_share_invoice_id is not null or own_share_paid)) then raise exception 'Refund did not release cases';end if;
 insert into public.invoices(id,business_unit_id,customer_id,payer_type,payer_name,issue_date,gross_total,net_total,invoice_number,own_share_case_id) values(single,u,customer,'private','Testpatient',day,10,10,'RE-OWN-PAY-SINGLE',case1);
 update public.trip_billing_cases set own_share_invoice_id=single where id=case1;
 report=public.patient_payment_report(u,actor,single);perform public.record_patient_payment(u,actor,single,gen_random_uuid(),report->>'version',day,5,'cash','TEST-SINGLE-1','');report=public.patient_payment_report(u,actor,single);perform public.record_patient_payment(u,actor,single,gen_random_uuid(),report->>'version',day,5,'cash','TEST-SINGLE-2','');
 if not(select own_share_paid from public.trip_billing_cases where id=case1) or(select own_share_paid from public.trip_billing_cases where id=case2) then raise exception 'Single payment settled wrong cases';end if;
 if has_table_privilege('authenticated','public.patient_invoice_payments','INSERT') or has_function_privilege('authenticated','public.record_patient_payment(uuid,uuid,uuid,uuid,text,date,numeric,text,text,text)','EXECUTE') then raise exception 'Browser write privilege leaked';end if;
end;$$;
rollback;
